[[features.ssl]]
= SSL

Spring Boot cung cấp khả năng cấu hình SSL trust material có thể áp dụng cho nhiều loại kết nối để hỗ trợ giao tiếp an toàn.
Các configuration property có prefix `spring.ssl.bundle` có thể được dùng để chỉ định các tập trust material có tên cùng thông tin liên quan.



[[features.ssl.jks]]
== Cấu hình SSL với Java KeyStore file

Các configuration property có prefix `spring.ssl.bundle.jks` có thể được dùng để cấu hình các bundle trust material được tạo bằng Java utility `keytool` và lưu trong Java KeyStore file định dạng JKS hoặc PKCS12.
Mỗi bundle có một tên do user cung cấp để dùng khi tham chiếu bundle.

Khi dùng để bảo vệ embedded web server, `keystore` thường được cấu hình bằng Java KeyStore chứa certificate và private key như ví dụ sau:

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          jks:
            mybundle:
              key:
                alias: "application"
              keystore:
                location: "classpath:application.p12"
                password: "secret"
                type: "PKCS12"
----

Khi dùng để bảo vệ client-side connection, `truststore` thường được cấu hình bằng Java KeyStore chứa server certificate như ví dụ sau:

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          jks:
            mybundle:
              truststore:
                location: "classpath:server.p12"
                password: "secret"
----

[TIP]
====
Thay vì location tới file, có thể cung cấp xref:features/external-config.adoc#features.external-config.typesafe-configuration-properties.conversion.base64[nội dung được encode Base64] của file đó.
Nếu chọn cách này, giá trị property nên bắt đầu bằng `base64:`.
====

Xem javadoc:org.springframework.boot.autoconfigure.ssl.JksSslBundleProperties[] để biết đầy đủ các property được hỗ trợ.

NOTE: Nếu dùng environment variable để cấu hình bundle, tên bundle xref:features/external-config.adoc#features.external-config.typesafe-configuration-properties.relaxed-binding.maps-from-environment-variables[luôn được chuyển thành chữ thường].



[[features.ssl.pem]]
== Cấu hình SSL với certificate được encode PEM

Các configuration property có prefix `spring.ssl.bundle.pem` có thể được dùng để cấu hình bundle trust material ở dạng text được encode PEM.
Mỗi bundle có một tên do user cung cấp để dùng khi tham chiếu bundle.

Khi dùng để bảo vệ embedded web server, `keystore` thường được cấu hình bằng certificate và private key như ví dụ sau:

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          pem:
            mybundle:
              keystore:
                certificate: "classpath:application.crt"
                private-key: "classpath:application.key"
----

Khi dùng để bảo vệ client-side connection, `truststore` thường được cấu hình bằng server certificate như ví dụ sau:

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          pem:
            mybundle:
              truststore:
                certificate: "classpath:server.crt"
----

[TIP]
====
Thay vì location tới file, có thể cung cấp xref:features/external-config.adoc#features.external-config.typesafe-configuration-properties.conversion.base64[nội dung được encode Base64] của file đó.
Nếu chọn cách này, giá trị property nên bắt đầu bằng `base64:`.

PEM content cũng có thể được dùng trực tiếp cho cả property `certificate` và `private-key`.
Nếu giá trị property chứa marker `BEGIN` và `END` thì chúng sẽ được xử lý như PEM content thay vì resource location.

Ví dụ sau cho thấy cách định nghĩa truststore certificate:

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          pem:
            mybundle:
              truststore:
                certificate: |
                  -----BEGIN CERTIFICATE-----
                  MIID1zCCAr+gAwIBAgIUNM5QQv8IzVQsgSmmdPQNaqyzWs4wDQYJKoZIhvcNAQEL
                  BQAwezELMAkGA1UEBhMCWFgxEjAQBgNVBAgMCVN0YXRlTmFtZTERMA8GA1UEBwwI
                  ...
                  V0IJjcmYjEZbTvpjFKznvaFiOUv+8L7jHQ1/Yf+9c3C8gSjdUfv88m17pqYXd+Ds
                  HEmfmNNjht130UyjNCITmLVXyy5p35vWmdf95U3uEbJSnNVtXH8qRmN9oK9mUpDb
                  ngX6JBJI7fw7tXoqWSLHNiBODM88fUlQSho8
                  -----END CERTIFICATE-----
----
====

Xem javadoc:org.springframework.boot.autoconfigure.ssl.PemSslBundleProperties[] để biết đầy đủ các property được hỗ trợ.

NOTE: Nếu dùng environment variable để cấu hình bundle, tên bundle xref:features/external-config.adoc#features.external-config.typesafe-configuration-properties.relaxed-binding.maps-from-environment-variables[luôn được chuyển thành chữ thường].



[[features.ssl.applying]]
== Áp dụng SSL Bundle

Sau khi được cấu hình bằng property, SSL bundle có thể được tham chiếu theo tên trong configuration property cho nhiều loại kết nối được Spring Boot auto-configure.
Xem các phần về xref:how-to:webserver.adoc#howto.webserver.configure-ssl[embedded web server], xref:data/index.adoc[data technology] và xref:io/rest-client.adoc[REST client] để biết thêm thông tin.



[[features.ssl.bundles]]
== Sử dụng SSL Bundle

Spring Boot auto-configure một bean type javadoc:org.springframework.boot.ssl.SslBundles[] cung cấp quyền truy cập tới từng named bundle được cấu hình bằng property `spring.ssl.bundle`.

Có thể lấy một javadoc:org.springframework.boot.ssl.SslBundle[] từ bean javadoc:org.springframework.boot.ssl.SslBundles[] đã được auto-configure và dùng nó để tạo các object phục vụ cấu hình SSL connectivity trong client library.
javadoc:org.springframework.boot.ssl.SslBundle[] cung cấp cách tiếp cận theo layer để lấy các SSL object này:

- `getStores()` cung cấp quyền truy cập tới các instance javadoc:java.security.KeyStore[] của key store và trust store cũng như mọi key store password cần thiết.
- `getManagers()` cung cấp quyền truy cập tới các instance javadoc:javax.net.ssl.KeyManagerFactory[] và javadoc:javax.net.ssl.TrustManagerFactory[] cũng như các array javadoc:javax.net.ssl.KeyManager[] và javadoc:javax.net.ssl.TrustManager[] mà chúng tạo.
- `createSslContext()` cung cấp cách thuận tiện để lấy instance javadoc:javax.net.ssl.SSLContext[] mới.

Ngoài ra, javadoc:org.springframework.boot.ssl.SslBundle[] cung cấp thông tin chi tiết về key đang được dùng, protocol cần dùng và mọi option nên được áp dụng cho SSL engine.

Ví dụ sau cho thấy cách lấy javadoc:org.springframework.boot.ssl.SslBundle[] và dùng nó để tạo javadoc:javax.net.ssl.SSLContext[]:

include-code::MyComponent[]



[[features.ssl.reloading]]
== Reload SSL Bundle

SSL bundle có thể được reload khi key material thay đổi.
Component sử dụng bundle phải tương thích với reloadable SSL bundle.
Hiện tại các component sau tương thích:

* Tomcat web server
* Netty web server
* LDAP client

Để bật reload, bạn cần opt-in qua configuration property như ví dụ sau:

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          pem:
            mybundle:
              reload-on-update: true
              keystore:
                certificate: "file:/some/directory/application.crt"
                private-key: "file:/some/directory/application.key"
----

Một file watcher sau đó sẽ theo dõi các file và nếu chúng thay đổi, SSL bundle sẽ được reload.
Điều này tiếp tục trigger reload trong component đang sử dụng bundle; ví dụ Tomcat sẽ rotate certificate trong các connector đã bật SSL.

Bạn có thể cấu hình quiet period của file watcher (để đảm bảo không còn thay đổi nào nữa) bằng property configprop:spring.ssl.bundle.watch.file.quiet-period[].

[[features.ssl.reloading.lets-encrypt]]
=== Reload SSL Bundle với Let's Encrypt

Nếu dùng certificate được cấp bởi https://letsencrypt.org/[Let's Encrypt] và được renew bởi external tool như https://certbot.eff.org/[Certbot], bạn có thể cấu hình PEM bundle để dùng các file được generate và bật reload.
Certbot thường lưu chúng trong `/etc/letsencrypt/live/` dưới directory được đặt theo domain của bạn.
Ví dụ sau cho thấy cách cấu hình PEM bundle cho `example.com`:

[configprops,yaml]
----
    spring:
      ssl:
        bundle:
          pem:
            webserver:
              reload-on-update: true
              keystore:
                certificate: "file:/etc/letsencrypt/live/example.com/fullchain.pem"
                private-key: "file:/etc/letsencrypt/live/example.com/privkey.pem"
    server:
      ssl:
        bundle: "webserver"
----

Spring Boot không request hoặc renew certificate Let's Encrypt.
Khi Certbot hoặc ACME client khác cập nhật các file đã cấu hình, SSL bundle sẽ được reload.
Các consumer tương thích như Tomcat và Netty web server sau đó có thể dùng certificate mới mà không cần restart ứng dụng.

Các file trong `/etc/letsencrypt/live` thường là symbolic link tới file trong `/etc/letsencrypt/archive`.
File watcher đi theo symbolic link để thay đổi ở target file có thể trigger reload.
