[[messaging.pulsar]]
= Hỗ trợ Apache Pulsar

https://pulsar.apache.org/[Apache Pulsar] được hỗ trợ thông qua auto-configuration của project {url-spring-pulsar-site}[Spring for Apache Pulsar].

Spring Boot sẽ auto-configure và register các component Spring for Apache Pulsar khi `org.springframework.pulsar:spring-pulsar` có trên classpath.

Starter `spring-boot-starter-pulsar` được cung cấp để gom các dependency cần dùng một cách thuận tiện.



[[messaging.pulsar.connecting]]
== Kết nối Pulsar

Khi dùng Pulsar starter, Spring Boot sẽ auto-configure và register một bean javadoc:org.apache.pulsar.client.api.PulsarClient[].

Mặc định, application thử kết nối tới Pulsar instance local tại `pulsar://localhost:6650`.
Có thể điều chỉnh bằng cách đặt configprop:spring.pulsar.client.service-url[] thành một value khác.

NOTE: Value phải là URL https://pulsar.apache.org/docs/client-libraries-java/#connection-urls[Pulsar Protocol] hợp lệ.

Bạn có thể cấu hình client bằng cách chỉ định bất kỳ application property nào có prefix `spring.pulsar.client.*`.

Nếu cần kiểm soát nhiều hơn đối với configuration, hãy cân nhắc register một hoặc nhiều bean javadoc:org.springframework.pulsar.core.PulsarClientBuilderCustomizer[].



[[messaging.pulsar.connecting.auth]]
=== Authentication

Để kết nối tới Pulsar cluster yêu cầu authentication, bạn cần chỉ định authentication plugin sẽ dùng bằng cách đặt `pluginClassName` và mọi parameter mà plugin yêu cầu.
Bạn có thể đặt các parameter dưới dạng map của parameter name và parameter value.
Ví dụ sau đây cho thấy cách cấu hình plugin `AuthenticationOAuth2`.

[configprops,yaml]
----
spring:
  pulsar:
    client:
      authentication:
        plugin-class-name: org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2
        param:
          issuerUrl: https://auth.server.cloud/
          privateKey: file:///Users/some-key.json
          audience: urn:sn:acme:dev:my-instance
----

[NOTE]
====
Bạn cần đảm bảo các name được định nghĩa dưới `+spring.pulsar.client.authentication.param.*+` khớp chính xác với name mà auth plugin mong đợi (thường được viết theo camel case).
Spring Boot không áp dụng relaxed binding cho các entry này.

Ví dụ, nếu muốn cấu hình issuer URL cho auth plugin `AuthenticationOAuth2`, bạn phải dùng `+spring.pulsar.client.authentication.param.issuerUrl+`.
Nếu dùng các dạng khác như `issuerurl` hoặc `issuer-url`, setting sẽ không được áp dụng cho plugin.

Việc không có relaxed binding cũng khiến việc dùng environment variable cho authentication parameter trở nên có vấn đề vì case sensitivity bị mất trong quá trình chuyển đổi.
Nếu dùng environment variable cho các parameter, bạn cần làm theo {url-spring-pulsar-docs}/reference/pulsar/pulsar-client.html#client-authentication-env-vars[các bước này] trong reference documentation của Spring for Apache Pulsar để hoạt động chính xác.
====



[[messaging.pulsar.connecting.ssl]]
=== SSL

Mặc định, Pulsar client giao tiếp với Pulsar service bằng plain text.
Bạn có thể làm theo {url-spring-pulsar-docs}/reference/pulsar/pulsar-client.html#tls-encryption[các bước này] trong reference documentation của Spring for Apache Pulsar để bật TLS encryption.

Để biết đầy đủ chi tiết về client và authentication, hãy xem {url-spring-pulsar-docs}/reference/pulsar/pulsar-client.html[reference documentation] của Spring for Apache Pulsar.



[[messaging.pulsar.admin]]
== Kết nối Pulsar Administration

Client javadoc:org.springframework.pulsar.core.PulsarAdministration[] của Spring for Apache Pulsar cũng được auto-configure.

Mặc định, application thử kết nối tới Pulsar instance local tại `\http://localhost:8080`.
Có thể điều chỉnh bằng cách đặt configprop:spring.pulsar.admin.service-url[] thành một value khác theo form `(http|https)://<host>:<port>`.

Nếu cần kiểm soát nhiều hơn đối với configuration, hãy cân nhắc register một hoặc nhiều bean javadoc:org.springframework.pulsar.core.PulsarAdminBuilderCustomizer[].



[[messaging.pulsar.admin.auth]]
=== Authentication

Khi truy cập Pulsar cluster yêu cầu authentication, admin client cần security configuration giống regular Pulsar client.
Bạn có thể dùng xref:messaging/pulsar.adoc#messaging.pulsar.connecting.auth[authentication configuration] nêu trên bằng cách thay `spring.pulsar.client.authentication` bằng `spring.pulsar.admin.authentication`.

TIP: Để tạo topic khi startup, thêm một bean thuộc type javadoc:org.springframework.pulsar.core.PulsarTopic[].
Nếu topic đã tồn tại, bean bị bỏ qua.



[[messaging.pulsar.sending]]
== Gửi Message

javadoc:org.springframework.pulsar.core.PulsarTemplate[] được auto-configure và bạn có thể dùng nó để gửi message như trong ví dụ sau:

include-code::MyBean[]

javadoc:org.springframework.pulsar.core.PulsarTemplate[] dựa trên javadoc:org.springframework.pulsar.core.PulsarProducerFactory[] để tạo underlying Pulsar producer.
Spring Boot auto-configuration cũng cung cấp producer factory này và mặc định cache các producer mà nó tạo ra.
Bạn có thể cấu hình producer factory và cache settings bằng cách chỉ định bất kỳ application property nào có prefix `spring.pulsar.producer.\*` và `spring.pulsar.producer.cache.*`.

Nếu cần kiểm soát nhiều hơn đối với producer factory configuration, hãy cân nhắc register một hoặc nhiều bean javadoc:org.springframework.pulsar.core.ProducerBuilderCustomizer[].
Các customizer này được áp dụng cho mọi producer được tạo.
Khi gửi message, bạn cũng có thể truyền javadoc:org.springframework.pulsar.core.ProducerBuilderCustomizer[] để chỉ ảnh hưởng tới producer hiện tại.

Nếu cần kiểm soát nhiều hơn đối với message được gửi, bạn có thể truyền javadoc:org.springframework.pulsar.core.TypedMessageBuilderCustomizer[] khi gửi message.



[[messaging.pulsar.receiving]]
== Nhận Message

Khi Apache Pulsar infrastructure có mặt, bất kỳ bean nào cũng có thể annotate javadoc:org.springframework.pulsar.annotation.PulsarListener[format=annotation] để tạo listener endpoint.
Component sau đây tạo một listener endpoint trên topic `someTopic`:

include-code::MyBean[]

Spring Boot auto-configuration cung cấp mọi component cần thiết cho javadoc:org.springframework.pulsar.annotation.PulsarListener[], chẳng hạn như javadoc:org.springframework.pulsar.config.PulsarListenerContainerFactory[] và consumer factory mà nó dùng để construct các Pulsar consumer underlying.
Bạn có thể cấu hình các component này bằng cách chỉ định bất kỳ application property nào có prefix `spring.pulsar.listener.\*` và `spring.pulsar.consumer.*`.

Nếu cần kiểm soát nhiều hơn đối với configuration của consumer factory, hãy cân nhắc register một hoặc nhiều bean javadoc:org.springframework.pulsar.core.ConsumerBuilderCustomizer[].
Các customizer này được áp dụng cho mọi consumer do factory tạo, và do đó cho mọi instance của javadoc:org.springframework.pulsar.annotation.PulsarListener[format=annotation].
Bạn cũng có thể customize một listener riêng lẻ bằng cách đặt attribute `consumerCustomizer` của annotation javadoc:org.springframework.pulsar.annotation.PulsarListener[format=annotation].

Nếu cần kiểm soát nhiều hơn đối với actual container factory configuration, hãy cân nhắc register một hoặc nhiều bean `PulsarContainerFactoryCustomizer<ConcurrentPulsarListenerContainerFactory<?>>`.



[[messaging.pulsar.reading]]
== Đọc Message

Pulsar reader interface cho phép application quản lý cursor thủ công.
Khi dùng reader để kết nối tới một topic, bạn cần chỉ định message mà reader sẽ bắt đầu đọc khi kết nối tới topic đó.

Khi Apache Pulsar infrastructure có mặt, bất kỳ bean nào cũng có thể được annotate với javadoc:org.springframework.pulsar.annotation.PulsarReader[format=annotation] để consume message bằng reader.
Component sau đây tạo một reader endpoint bắt đầu đọc message từ đầu topic `someTopic`:

include-code::MyBean[]

javadoc:org.springframework.pulsar.annotation.PulsarReader[format=annotation] dựa trên javadoc:org.springframework.pulsar.core.PulsarReaderFactory[] để tạo underlying Pulsar reader.
Spring Boot auto-configuration cung cấp reader factory này, có thể customize bằng cách đặt bất kỳ application property nào có prefix `spring.pulsar.reader.*`.

Nếu cần kiểm soát nhiều hơn đối với configuration của reader factory, hãy cân nhắc register một hoặc nhiều bean javadoc:org.springframework.pulsar.core.ReaderBuilderCustomizer[].
Các customizer này được áp dụng cho mọi reader do factory tạo, và do đó cho mọi instance của javadoc:org.springframework.pulsar.annotation.PulsarReader[format=annotation].
Bạn cũng có thể customize một listener riêng lẻ bằng cách đặt attribute `readerCustomizer` của annotation javadoc:org.springframework.pulsar.annotation.PulsarReader[format=annotation].

Nếu cần kiểm soát nhiều hơn đối với actual container factory configuration, hãy cân nhắc register một hoặc nhiều bean `PulsarContainerFactoryCustomizer<DefaultPulsarReaderContainerFactory<?>>`.

TIP: Để biết thêm chi tiết về bất kỳ component nào ở trên và khám phá các feature khả dụng khác, hãy xem {url-spring-pulsar-docs}[reference documentation] của Spring for Apache Pulsar.



[[messaging.pulsar.transactions]]
== Hỗ trợ transaction

Spring for Apache Pulsar hỗ trợ transaction khi dùng javadoc:org.springframework.pulsar.core.PulsarTemplate[] và javadoc:org.springframework.pulsar.annotation.PulsarListener[format=annotation].

Đặt configprop:spring.pulsar.transaction.enabled[] thành `true` sẽ:

* Configure một bean javadoc:org.springframework.pulsar.transaction.PulsarTransactionManager[]
* Enable transaction support cho javadoc:org.springframework.pulsar.core.PulsarTemplate[]
* Enable transaction support cho các method javadoc:org.springframework.pulsar.annotation.PulsarListener[format=annotation]

Attribute `transactional` của javadoc:org.springframework.pulsar.annotation.PulsarListener[format=annotation] có thể dùng để fine-tune thời điểm transaction được dùng với listener.

Để kiểm soát nhiều hơn các transaction feature của Spring for Apache Pulsar, bạn nên tự định nghĩa bean javadoc:org.springframework.pulsar.core.PulsarTemplate[] và/hoặc javadoc:org.springframework.pulsar.config.ConcurrentPulsarListenerContainerFactory[].
Bạn cũng có thể định nghĩa bean javadoc:org.springframework.pulsar.transaction.PulsarAwareTransactionManager[] nếu javadoc:org.springframework.pulsar.transaction.PulsarTransactionManager[] được auto-configure mặc định không phù hợp.



[[messaging.pulsar.additional-properties]]
== Pulsar property bổ sung

Các property được auto-configuration hỗ trợ được hiển thị trong mục xref:appendix:application-properties/index.adoc#appendix.application-properties.integration[Integration Properties] của Appendix.
Lưu ý rằng phần lớn các property này (dạng hyphen hoặc camelCase) map trực tiếp tới các configuration property của Apache Pulsar.
Xem tài liệu Apache Pulsar để biết chi tiết.

Chỉ một subset các property mà Pulsar hỗ trợ được cung cấp trực tiếp thông qua class javadoc:org.springframework.boot.pulsar.autoconfigure.PulsarProperties[].
Nếu muốn tune các auto-configured component bằng additional property không được hỗ trợ trực tiếp, bạn có thể dùng customizer được component tương ứng nêu trên hỗ trợ.
