[[messaging.spring-integration]]
= Spring Integration

Spring Boot cung cấp nhiều tiện ích khi làm việc với {url-spring-integration-site}[Spring Integration], gồm starter `spring-boot-starter-integration`.
Spring Integration cung cấp abstraction trên messaging và các transport khác như HTTP, TCP.
Nếu Spring Integration có trên classpath, nó được initialize qua annotation javadoc:org.springframework.integration.config.EnableIntegration[format=annotation].

Polling logic của Spring Integration dựa xref:features/task-execution-and-scheduling.adoc[trên auto-configured javadoc:org.springframework.scheduling.TaskScheduler[]].
Default javadoc:org.springframework.integration.scheduling.PollerMetadata[] (poll không giới hạn số message mỗi giây) có thể customize bằng property `spring.integration.poller.*`.

Spring Boot cũng cấu hình một số feature được trigger khi có thêm Spring Integration module.
Nếu `spring-integration-jmx` có trên classpath, message processing statistic được publish qua JMX.
Nếu `spring-integration-jdbc` có sẵn, default database schema có thể được tạo khi startup:

[configprops,yaml]
----
spring:
  integration:
    jdbc:
      initialize-schema: "always"
----

Nếu `spring-integration-rsocket` có sẵn, developer có thể cấu hình RSocket server bằng property `spring.rsocket.server.*` và dùng javadoc:org.springframework.integration.rsocket.IntegrationRSocketEndpoint[] hoặc javadoc:org.springframework.integration.rsocket.outbound.RSocketOutboundGateway[] để xử lý incoming RSocket message.
Infrastructure này có thể xử lý Spring Integration RSocket channel adapter và handler javadoc:org.springframework.messaging.handler.annotation.MessageMapping[format=annotation] nếu `spring.integration.rsocket.server.message-mapping-enabled` được cấu hình.

Spring Boot cũng có thể auto-configure javadoc:org.springframework.integration.rsocket.ClientRSocketConnector[] bằng configuration property:

[configprops,yaml]
----
# Connecting to a RSocket server over TCP
spring:
  integration:
    rsocket:
      client:
        host: "example.org"
        port: 9898
----

[configprops,yaml]
----
# Connecting to a RSocket Server over WebSocket
spring:
  integration:
    rsocket:
      client:
        uri: "ws://example.org"
----

Xem {code-spring-boot-integration-src}/autoconfigure/IntegrationAutoConfiguration.java[`IntegrationAutoConfiguration`] và class javadoc:org.springframework.boot.integration.autoconfigure.IntegrationProperties[] để biết thêm.
