[appendix]
[[appendix.configuration-metadata]]
= Configuration Metadata

Các JAR của Spring Boot bao gồm các file metadata cung cấp thông tin chi tiết về tất cả các configuration property được hỗ trợ.
Các file này được thiết kế để giúp các nhà phát triển IDE cung cấp trợ giúp theo ngữ cảnh và "`code completion`" khi người dùng làm việc với các file `application.properties` hoặc `application.yaml`.

Phần lớn file metadata được tạo tự động tại compile time bằng cách xử lý tất cả các item được annotate bằng javadoc:org.springframework.boot.context.properties.ConfigurationProperties[format=annotation].
Với các trường hợp đặc biệt hoặc use case nâng cao hơn, có thể xref:configuration-metadata/annotation-processor.adoc#appendix.configuration-metadata.annotation-processor.automatic-metadata-generation.source[lấy metadata từ các type bên ngoài] hoặc xref:configuration-metadata/annotation-processor.adoc#appendix.configuration-metadata.annotation-processor.adding-additional-metadata[viết thủ công một phần metadata].
