[[using.build-systems]]
= Build Systems

Bạn rất nên chọn build system hỗ trợ xref:using/build-systems.adoc#using.build-systems.dependency-management[dependency management] và có thể sử dụng artifact được phát hành lên Maven Central repository.
Chúng tôi khuyến nghị chọn Maven hoặc Gradle.
Spring Boot có thể hoạt động với build system khác (ví dụ Ant), nhưng chúng không được hỗ trợ tốt bằng.



[[using.build-systems.dependency-management]]
== Dependency Management

Mỗi bản phát hành Spring Boot cung cấp một danh sách dependency được chọn lọc mà Spring Boot hỗ trợ.
Trong thực tế, bạn không cần khai báo phiên bản cho các dependency này trong cấu hình build, vì Spring Boot quản lý việc đó.
Khi nâng cấp Spring Boot, các dependency này cũng được nâng cấp một cách nhất quán.

NOTE: Bạn vẫn có thể chỉ định phiên bản và ghi đè khuyến nghị của Spring Boot khi cần.

Danh sách được chọn lọc này bao gồm tất cả Spring module có thể dùng với Spring Boot, cùng với danh sách các thư viện bên thứ ba được chọn lọc kỹ.
Danh sách này được cung cấp dưới dạng Bill of Materials tiêu chuẩn (`spring-boot-dependencies`), có thể dùng với cả xref:using/build-systems.adoc#using.build-systems.maven[Maven] và xref:using/build-systems.adoc#using.build-systems.gradle[Gradle].

WARNING: Mỗi bản phát hành Spring Boot gắn với một phiên bản cơ sở của Spring Framework.
Chúng tôi **đặc biệt** khuyến nghị bạn không chỉ định phiên bản Spring Framework.



[[using.build-systems.maven]]
== Maven

Để tìm hiểu cách sử dụng Spring Boot với Maven, xem tài liệu Maven plugin của Spring Boot:

* xref:maven-plugin:index.adoc[Tài liệu tham khảo]
* xref:maven-plugin:api/java/index.html[API]



[[using.build-systems.gradle]]
== Gradle

Để tìm hiểu cách sử dụng Spring Boot với Gradle, xem tài liệu Gradle plugin của Spring Boot:

* xref:gradle-plugin:index.adoc[Tài liệu tham khảo]
* xref:gradle-plugin:api/java/index.html[API]



[[using.build-systems.ant]]
==  Ant

Có thể build một project Spring Boot bằng Apache Ant+Ivy.
Module `spring-boot-antlib` "`AntLib`" cũng có sẵn để giúp Ant tạo các executable jar.

Để khai báo dependency, file `ivy.xml` thông thường có dạng như ví dụ sau:

[source,xml]
----
<ivy-module version="2.0">
	<info organisation="org.springframework.boot" module="spring-boot-sample-ant" />
	<configurations>
		<conf name="compile" description="everything needed to compile this module" />
		<conf name="runtime" extends="compile" description="everything needed to run this module" />
	</configurations>
	<dependencies>
		<dependency org="org.springframework.boot" name="spring-boot-starter"
			rev="${spring-boot.version}" conf="compile" />
	</dependencies>
</ivy-module>
----

File `build.xml` thông thường có dạng như ví dụ sau:

[source,xml,subs="verbatim,attributes"]
----
<project
	xmlns:ivy="antlib:org.apache.ivy.ant"
	xmlns:spring-boot="antlib:org.springframework.boot.ant"
	name="myapp" default="build">

	<property name="spring-boot.version" value="{version-spring-boot}" />

	<target name="resolve" description="--> retrieve dependencies with ivy">
		<ivy:retrieve pattern="lib/[conf]/[artifact]-[type]-[revision].[ext]" />
	</target>

	<target name="classpaths" depends="resolve">
		<path id="compile.classpath">
			<fileset dir="lib/compile" includes="*.jar" />
		</path>
	</target>

	<target name="init" depends="classpaths">
		<mkdir dir="build/classes" />
	</target>

	<target name="compile" depends="init" description="compile">
		<javac srcdir="src/main/java" destdir="build/classes" classpathref="compile.classpath" />
	</target>

	<target name="build" depends="compile">
		<spring-boot:exejar destfile="build/myapp.jar" classes="build/classes">
			<spring-boot:lib>
				<fileset dir="lib/runtime" />
			</spring-boot:lib>
		</spring-boot:exejar>
	</target>
</project>
----

TIP: Nếu không muốn dùng module `spring-boot-antlib`, xem phần xref:how-to:build.adoc#howto.build.build-an-executable-archive-with-ant-without-using-spring-boot-antlib[] trong "`Hướng dẫn How-to`".



[[using.build-systems.starters]]
== Starters

Starters là một tập hợp các descriptor dependency tiện dụng mà bạn có thể đưa vào application.
Bạn có được đầy đủ Spring và các công nghệ liên quan cần thiết tại một nơi, không phải tìm trong code mẫu rồi sao chép hàng loạt descriptor dependency.
Ví dụ, nếu muốn bắt đầu sử dụng Spring và JPA cho việc truy cập database, hãy thêm dependency `spring-boot-starter-data-jpa` vào project.

Các starter chứa nhiều dependency cần thiết để project nhanh chóng hoạt động, cùng một tập hợp transitive dependency được quản lý nhất quán và được hỗ trợ.

.Ý nghĩa cách đặt tên
****
Mọi starter **chính thức** đều theo mẫu tên tương tự: `+spring-boot-starter-*+`, trong đó `+*+` là một loại ứng dụng cụ thể.
Cấu trúc tên này nhằm giúp bạn tìm starter dễ dàng hơn.
Tích hợp Maven trong nhiều IDE cho phép tìm dependency theo tên.
Ví dụ, khi đã cài Eclipse plugin hoặc Spring Tools plugin phù hợp, bạn có thể nhấn `ctrl-space` trong trình soạn thảo POM và gõ "`spring-boot-starter`" để xem danh sách đầy đủ.

Như giải thích trong phần xref:features/developing-auto-configuration.adoc#features.developing-auto-configuration.custom-starter[], starter bên thứ ba không nên bắt đầu bằng `spring-boot`, vì tiền tố này dành cho artifact Spring Boot chính thức.
Thay vào đó, starter bên thứ ba thường bắt đầu bằng tên project.
Ví dụ, một project starter bên thứ ba tên `thirdpartyproject` thường được đặt tên `thirdpartyproject-spring-boot-starter`.
****

Spring Boot cung cấp các application starter sau trong group `org.springframework.boot`:

.Các application starter của Spring Boot
include::ROOT:partial$starters/application-starters.adoc[]

Ngoài các application starter, có thể dùng các starter sau để thêm tính năng xref:how-to:actuator.adoc[sẵn sàng cho production]:

.Các production starter của Spring Boot
include::ROOT:partial$starters/production-starters.adoc[]

Cuối cùng, Spring Boot còn có các starter sau để bạn loại trừ hoặc thay thế một số thành phần kỹ thuật cụ thể:

.Các technical starter của Spring Boot
include::ROOT:partial$starters/technical-starters.adoc[]

Để tìm hiểu cách thay thế thành phần kỹ thuật, xem tài liệu How-to về xref:how-to:webserver.adoc#howto.webserver.use-another[thay web server] và xref:how-to:logging.adoc#howto.logging.log4j[hệ thống logging].

TIP: Để xem danh sách các starter bổ sung do cộng đồng đóng góp, xem {code-spring-boot-latest}/starter/README.adoc[file README] trong module `spring-boot-starters` trên GitHub.
