[[using.spring-beans-and-dependency-injection]]
= Spring Bean và Dependency Injection

Bạn có thể sử dụng bất kỳ kỹ thuật tiêu chuẩn nào của Spring Framework để định nghĩa bean và các dependency được inject.
Chúng tôi thường khuyến nghị dùng constructor injection để kết nối dependency và javadoc:org.springframework.context.annotation.ComponentScan[format=annotation] để tìm bean.

Nếu tổ chức code như gợi ý ở trên (đặt class ứng dụng trong package cấp trên cùng), bạn có thể thêm javadoc:org.springframework.context.annotation.ComponentScan[format=annotation] không có đối số hoặc dùng annotation javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation], vốn ngầm bao gồm nó.
Mọi component của ứng dụng (javadoc:org.springframework.stereotype.Component[format=annotation], javadoc:org.springframework.stereotype.Service[format=annotation], javadoc:org.springframework.stereotype.Repository[format=annotation], javadoc:org.springframework.stereotype.Controller[format=annotation] và các component khác) được tự động đăng ký thành Spring Bean.

Ví dụ sau minh họa bean javadoc:org.springframework.stereotype.Service[format=annotation] sử dụng constructor injection để nhận bean `RiskAssessor` bắt buộc:

include-code::singleconstructor/MyAccountService[]

Nếu bean có nhiều constructor, bạn cần đánh dấu constructor muốn Spring sử dụng bằng javadoc:org.springframework.beans.factory.annotation.Autowired[format=annotation]:

include-code::multipleconstructors/MyAccountService[]

TIP: Lưu ý rằng constructor injection cho phép đánh dấu field `riskAssessor` là `final`, thể hiện nó không thể bị thay đổi sau đó.
