[[cli.using-the-cli]]
= Dùng CLI

Sau khi cài CLI, bạn có thể chạy bằng cách gõ `spring` rồi nhấn Enter tại command line.
Nếu chạy `spring` không kèm argument nào, màn hình help sẽ hiển thị như sau:

[source,shell]
----
$ spring
usage: spring [--help] [--version]
       <command> [<args>]

Available commands are:

  init [options] [location]
    Initialize a new project using Spring Initializr (start.spring.io)

  encodepassword [options] <password to encode>
    Encode a password for use with Spring Security

  shell
    Start a nested shell

Common options:

  --debug Verbose mode
    Print additional status information for the command you are running


See 'spring help <command>' for more information on a specific command.
----

Bạn có thể gõ `spring help` để xem chi tiết hơn về bất kỳ command nào được hỗ trợ, như ví dụ sau:

[source,shell]
----
$ spring help init
spring init - Initialize a new project using Spring Initializr (start.spring.io)

usage: spring init [options] [location]

Option                       Description
------                       -----------
-a, --artifact-id <String>   Project coordinates; infer archive name (for
                               example 'test')
-b, --boot-version <String>  Spring Boot version (for example '1.2.0.RELEASE')
--build <String>             Build system to use (for example 'maven' or
                               'gradle') (default: maven)
-d, --dependencies <String>  Comma-separated list of dependency identifiers to
                               include in the generated project
--description <String>       Project description
-f, --force                  Force overwrite of existing files
--format <String>            Format of the generated content (for example
                               'build' for a build file, 'project' for a
                               project archive) (default: project)
-g, --group-id <String>      Project coordinates (for example 'org.test')
-j, --java-version <String>  Language level (for example '1.8')
-l, --language <String>      Programming language  (for example 'java')
--list                       List the capabilities of the service. Use it to
                               discover the dependencies and the types that are
                               available
-n, --name <String>          Project name; infer application name
-p, --packaging <String>     Project packaging (for example 'jar')
--package-name <String>      Package name
-t, --type <String>          Project type. Not normally needed if you use --
                               build and/or --format. Check the capabilities of
                               the service (--list) for more details
--target <String>            URL of the service to use (default: https://start.
                               spring.io)
-v, --version <String>       Project version (for example '0.0.1-SNAPSHOT')
-x, --extract                Extract the project archive. Inferred if a
                               location is specified without an extension

examples:

    To list all the capabilities of the service:
        $ spring init --list

    To creates a default project:
        $ spring init

    To create a web my-app.zip:
        $ spring init -d=web my-app.zip

    To create a web/data-jpa gradle project unpacked:
        $ spring init -d=web,jpa --build=gradle my-dir
----

Command `version` cung cấp cách nhanh chóng để kiểm tra bạn đang dùng version Spring Boot nào, như sau:

[source,shell,subs="verbatim,attributes"]
----
$ spring version
Spring CLI v{version-spring-boot}
----

[[cli.using-the-cli.initialize-new-project]]
== Khởi tạo project mới

Command `init` cho phép tạo project mới bằng https://start.spring.io mà không cần rời shell, như ví dụ sau:

[source,shell]
----
$ spring init --dependencies=web,data-jpa my-project
Using service at https://start.spring.io
Project extracted to '/Users/developer/example/my-project'
----

Ví dụ trên tạo thư mục `my-project` chứa project dựa trên Maven dùng `spring-boot-starter-web` và `spring-boot-starter-data-jpa`.
Bạn có thể liệt kê capability của service bằng flag `--list`, như ví dụ sau:

[source,shell]
----
$ spring init --list
=======================================
Capabilities of https://start.spring.io
=======================================

Available dependencies:
-----------------------
actuator - Actuator: Production ready features to help you monitor and manage your application
...
web - Web: Support for full-stack web development, including Tomcat and spring-webmvc
websocket - Websocket: Support for WebSocket development
ws - WS: Support for Spring Web Services

Available project types:
------------------------
gradle-build -  Gradle Config [format:build, build:gradle]
gradle-project -  Gradle Project [format:project, build:gradle]
maven-build -  Maven POM [format:build, build:maven]
maven-project -  Maven Project [format:project, build:maven] (default)

...
----

Command `init` hỗ trợ nhiều option.
Xem output của `help` để biết thêm chi tiết.
Ví dụ, command sau tạo Gradle project dùng Java 17 và packaging `war`:

[source,shell]
----
$ spring init --build=gradle --java-version=17 --dependencies=websocket --packaging=war sample-app.zip
Using service at https://start.spring.io
Content saved to 'sample-app.zip'
----

[[cli.using-the-cli.embedded-shell]]
== Dùng Embedded Shell

Spring Boot bao gồm các command-line completion script cho shell BASH và zsh.
Nếu bạn không dùng một trong hai shell này (có thể bạn là người dùng Windows), bạn có thể dùng command `shell` để khởi chạy một integrated shell, như ví dụ sau:

[source,shell,subs="verbatim,quotes,attributes"]
----
$ spring shell
*Spring Boot* (v{version-spring-boot})
Hit TAB to complete. Type \'help' and hit RETURN for help, and \'exit' to quit.
----

Từ bên trong embedded shell, bạn có thể chạy trực tiếp các command khác:

[source,shell,subs="verbatim,attributes"]
----
$ version
Spring CLI v{version-spring-boot}
----

Embedded shell hỗ trợ output màu ANSI cũng như `tab` completion.
Nếu cần chạy native command, bạn có thể dùng prefix `!`.
Để thoát embedded shell, nhấn `ctrl-c`.
