[[packaging.aot-cache]]
= AOT Cache
:page-aliases: class-data-sharing.adoc

AOT cache là https://openjdk.org/jeps/483[JVM feature] giúp giảm startup time và memory footprint của Java application.

Nếu chưa dùng Java 25 trở lên, hãy đọc phần CDS.
CDS là predecessor của AOT cache nhưng hoạt động tương tự.

NOTE: Spring Boot hỗ trợ cả CDS và AOT cache, tuy nhiên khuyến nghị dùng AOT cache khi có thể.

[[packaging.aot-cache.aot-cache]]
== AOT Cache

NOTE: Spring Boot hỗ trợ AOT cache với Java 25 trở lên.
Nếu dùng Java version cũ hơn, phải dùng CDS.

Để dùng AOT cache, trước tiên thực hiện training run trên application ở extracted form:

[source,shell]
----
$ java -Djarmode=tools -jar my-app.jar extract --destination application
$ cd application
$ java -XX:AOTCacheOutput=app.aot -Dspring.context.exit=onRefresh -jar my-app.jar
----

Lệnh tạo file cache `app.aot` có thể reuse miễn là application không update và dùng cùng Java version.

Để dùng cache file, thêm parameter khi start application:

[source,shell]
----
$ java -XX:AOTCache=app.aot -jar my-app.jar
----

NOTE: Phải dùng cache file với extracted form của application, nếu không nó không có tác dụng.

Để biết cách tận dụng AOT Cache với Buildpacks, xem xref:how-to:aot-cache.adoc[AOT Cache How-to guide].

[[packaging.aot-cache.cds]]
== CDS

NOTE: Nếu dùng Java 25 trở lên, hãy dùng AOT cache thay CDS.

Để dùng CDS, trước tiên thực hiện training run trên application ở extracted form:

[source,shell]
----
$ java -Djarmode=tools -jar my-app.jar extract --destination application
$ cd application
$ java -XX:ArchiveClassesAtExit=application.jsa -Dspring.context.exit=onRefresh -jar my-app.jar
----

Lệnh tạo archive `application.jsa` có thể reuse miễn là application không update.

Để dùng archive file, thêm parameter:

[source,shell]
----
$ java -XX:SharedArchiveFile=application.jsa -jar my-app.jar
----

NOTE: Phải dùng cache file với extracted form của application, nếu không nó không có tác dụng.

NOTE: Chi tiết về CDS xem https://docs.oracle.com/en/java/javase/17/vm/class-data-sharing.html[Class Data Sharing documentation của JDK].
