[[packaging.aot-cache]]
= AOT Cache
:page-aliases: class-data-sharing.adoc

AOT cache là một https://openjdk.org/jeps/483[tính năng của JVM] có thể giúp giảm startup time và memory footprint của Java application.

Nếu chưa dùng Java 25 trở lên, hãy đọc phần CDS.
CDS là predecessor của AOT cache nhưng hoạt động tương tự.

NOTE: Spring Boot hỗ trợ cả CDS và AOT cache, tuy nhiên khuyến nghị dùng AOT cache khi có thể.



[[packaging.aot-cache.aot-cache]]
== AOT Cache

NOTE: Spring Boot hỗ trợ AOT cache với Java 25 trở lên.
Nếu dùng Java version cũ hơn, phải dùng CDS.

Để dùng tính năng AOT cache, trước tiên bạn nên thực hiện training run trên application ở extracted form:

[source,shell]
----
$ java -Djarmode=tools -jar my-app.jar extract --destination application
$ cd application
$ java -XX:AOTCacheOutput=app.aot -Dspring.context.exit=onRefresh -jar my-app.jar
----

Thao tác này tạo file cache `app.aot`, có thể được reuse miễn là application không được update và dùng cùng Java version.

Để dùng cache file, cần thêm một parameter khi start application:

[source,shell]
----
$ java -XX:AOTCache=app.aot -jar my-app.jar
----

NOTE: Bạn phải dùng cache file với extracted form của application, nếu không cache file sẽ không có tác dụng.

Để biết cách tận dụng AOT Cache với Buildpacks, xem xref:how-to:aot-cache.adoc[hướng dẫn How-to về AOT Cache].



[[packaging.aot-cache.cds]]
== CDS

NOTE: Nếu dùng Java 25 trở lên, hãy dùng AOT cache thay CDS.

Để dùng CDS, trước tiên bạn nên thực hiện training run trên application ở extracted form:

[source,shell]
----
$ java -Djarmode=tools -jar my-app.jar extract --destination application
$ cd application
$ java -XX:ArchiveClassesAtExit=application.jsa -Dspring.context.exit=onRefresh -jar my-app.jar
----

Thao tác này tạo archive `application.jsa`, có thể được reuse miễn là application không được update.

Để dùng archive file, cần thêm một parameter khi start application:

[source,shell]
----
$ java -XX:SharedArchiveFile=application.jsa -jar my-app.jar
----

NOTE: Bạn phải dùng cache file với extracted form của application, nếu không cache file sẽ không có tác dụng.

NOTE: Để biết thêm chi tiết về CDS, xem https://docs.oracle.com/en/java/javase/17/vm/class-data-sharing.html[tài liệu Class Data Sharing của JDK].
