[[packaging.aot]]
= Xử lý Ahead-of-Time với JVM

Việc chạy application bằng initialization code được AOT generate giúp cải thiện startup time.
Trước tiên, cần đảm bảo JAR đang được build có chứa code được AOT generate.

NOTE: Có thể kết hợp AOT cache và Spring AOT để tiếp tục cải thiện startup time.

Với Maven, cần build bằng `-Pnative` để activate profile `native`:

[source,shell]
----
$ mvn -Pnative package
----

Với Gradle, cần đảm bảo build có plugin `org.springframework.boot.aot`.

Khi JAR đã được build, chạy với system property `spring.aot.enabled` được set thành `true`. Ví dụ:

[source,shell]
----
$ java -Dspring.aot.enabled=true -jar myapplication.jar

........ Starting AOT-processed MyApplication ...
----

Lưu ý rằng việc sử dụng ahead-of-time processing có một số bất lợi.
Điều này kéo theo các hạn chế sau:

* Classpath được cố định và xác định đầy đủ tại build time
* Các bean được định nghĩa trong application không thể thay đổi tại runtime, nghĩa là:
- Annotation Spring javadoc:org.springframework.context.annotation.Profile[format=annotation] và configuration theo profile xref:how-to:aot.adoc#howto.aot.conditions[có những hạn chế].
- Không hỗ trợ các property thay đổi tùy theo việc một bean có được tạo hay không (ví dụ javadoc:org.springframework.boot.autoconfigure.condition.ConditionalOnProperty[format=annotation] và các property `.enabled`).

Để tìm hiểu thêm về ahead-of-time processing, xem section xref:packaging/native-image/introducing-graalvm-native-images.adoc#packaging.native-image.introducing-graalvm-native-images.understanding-aot-processing[].
