[[packaging.aot]]
= Ahead-of-Time Processing với JVM

Chạy application bằng AOT-generated initialization code có lợi cho startup time.
Trước tiên cần đảm bảo jar được build có AOT-generated code.

NOTE: Có thể kết hợp AOT cache và Spring AOT để cải thiện startup time hơn nữa.

Với Maven, build bằng `-Pnative` để activate profile `native`:

[source,shell]
----
$ mvn -Pnative package
----

Với Gradle, đảm bảo build có plugin `org.springframework.boot.aot`.

Khi JAR đã build, chạy với system property `spring.aot.enabled=true`:

[source,shell]
----
$ java -Dspring.aot.enabled=true -jar myapplication.jar

........ Starting AOT-processed MyApplication ...
----

Ahead-of-time processing có các hạn chế:

* Classpath cố định và được định nghĩa hoàn toàn tại build time.
* Bean trong application không thể thay đổi runtime, nghĩa là:
- Annotation Spring javadoc:org.springframework.context.annotation.Profile[format=annotation] và profile-specific configuration xref:how-to:aot.adoc#howto.aot.conditions[có hạn chế].
- Property thay đổi việc bean có được tạo hay không không được hỗ trợ (ví dụ javadoc:org.springframework.boot.autoconfigure.condition.ConditionalOnProperty[format=annotation] và property `.enabled`).

Để tìm hiểu thêm, xem xref:packaging/native-image/introducing-graalvm-native-images.adoc#packaging.native-image.introducing-graalvm-native-images.understanding-aot-processing[].
