[[howto.traditional-deployment]]
= Deploy truyền thống

Spring Boot hỗ trợ traditional deployment cũng như các hình thức deployment hiện đại hơn.
Phần này trả lời các câu hỏi phổ biến về traditional deployment.

[[howto.traditional-deployment.war]]
== Tạo Deployable War File

WARNING: Vì Spring WebFlux không phụ thuộc chặt vào servlet API và các application mặc định được deploy trên embedded Reactor Netty server, War deployment không được hỗ trợ cho WebFlux application.

Bước đầu để tạo deployable war file là cung cấp subclass của javadoc:org.springframework.boot.web.servlet.support.SpringBootServletInitializer[] và override method `configure`.
Cách này sử dụng servlet 3.0 support của Spring Framework và cho phép bạn configure application khi servlet container launch application.
Thông thường, bạn nên update main class của application để extend javadoc:org.springframework.boot.web.servlet.support.SpringBootServletInitializer[], như trong ví dụ sau:

include-code::MyApplication[]

Bước tiếp theo là update build configuration để project tạo war file thay vì jar file.
Nếu dùng Maven và `spring-boot-starter-parent` (vốn configure Maven war plugin cho bạn), bạn chỉ cần modify `pom.xml` để đổi packaging thành war, như sau:

[source,xml]
----
<packaging>war</packaging>
----

Nếu dùng Gradle, bạn cần modify `build.gradle` để apply war plugin cho project, như sau:

[source,gradle]
----
apply plugin: 'war'
----

Bước cuối là đảm bảo embedded servlet container không interfere với servlet container mà war file được deploy vào.

Với Maven, bạn cần mark embedded servlet container dependency là `provided`.
Ví dụ:

[source,xml]
----
<dependencies>
	<!-- ... -->
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-tomcat</artifactId>
		<scope>provided</scope>
	</dependency>
	<!-- ... -->
</dependencies>
----

Nếu dùng Gradle, bạn cần chỉ move các runtime dependency vào configuration `providedRuntime`.
Ví dụ:

[source,gradle]
----
dependencies {
	// ...
	providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat-runtime'
	// ...
}
----

TIP: `providedRuntime` được ưu tiên hơn configuration `compileOnly` của Gradle.
Ngoài các limitation khác, `compileOnly` dependency không có trên test classpath, vì vậy mọi web-based integration test đều fail.

Nếu dùng Spring Boot xref:build-tool-plugin:index.adoc[], việc mark embedded servlet container dependency là provided sẽ tạo executable war file với các provided dependency được package trong directory `lib-provided`.
Điều này nghĩa là ngoài việc deploy vào servlet container, bạn cũng có thể chạy application bằng `java -jar` trên command line.

[[howto.traditional-deployment.convert-existing-application]]
== Chuyển application hiện có sang Spring Boot

Để convert existing non-web Spring application thành Spring Boot application, hãy replace code tạo javadoc:org.springframework.context.ApplicationContext[] bằng các call tới javadoc:org.springframework.boot.SpringApplication[] hoặc javadoc:org.springframework.boot.builder.SpringApplicationBuilder[].
Spring MVC web application thường phù hợp với việc trước tiên tạo deployable war application rồi migrate sau sang executable war hoặc jar.

Để tạo deployable war bằng cách extend javadoc:org.springframework.boot.web.servlet.support.SpringBootServletInitializer[] (ví dụ trong class có tên `Application`) và thêm annotation javadoc:org.springframework.boot.autoconfigure.SpringBootApplication[format=annotation] của Spring Boot, hãy sử dụng code tương tự ví dụ sau:

include-code::MyApplication[tag=!main]

Hãy nhớ rằng mọi thứ bạn đặt trong `sources` chỉ đơn giản là một Spring javadoc:org.springframework.context.ApplicationContext[].
Thông thường, bất cứ thứ gì đã hoạt động thì cũng nên hoạt động ở đây.
Có thể sau này bạn sẽ remove một số bean và để Spring Boot cung cấp default tương ứng, nhưng trước khi cần làm vậy thì bạn vẫn có thể làm cho application hoạt động.

Static resource có thể được move tới `/public` (hoặc `/static`, `/resources` hoặc `/META-INF/resources`) tại classpath root.
Điều tương tự cũng áp dụng cho `messages.properties`, file mà Spring Boot tự động detect tại root của classpath.

Vanilla usage của Spring javadoc:org.springframework.web.servlet.DispatcherServlet[] và Spring Security không cần thêm thay đổi nào.
Nếu application có các feature khác (chẳng hạn sử dụng servlet hoặc filter khác), bạn có thể cần thêm configuration vào context `Application` để replace các element trong `web.xml`, như sau:

* Một javadoc:org.springframework.context.annotation.Bean[format=annotation] có type là javadoc:jakarta.servlet.Servlet[] hoặc javadoc:org.springframework.boot.web.servlet.ServletRegistrationBean[] sẽ install bean đó vào container giống như `<servlet/>` và `<servlet-mapping/>` trong `web.xml`.
* Một javadoc:org.springframework.context.annotation.Bean[format=annotation] có type là javadoc:jakarta.servlet.Filter[] hoặc javadoc:org.springframework.boot.web.servlet.FilterRegistrationBean[] có behavior tương tự như `<filter/>` và `<filter-mapping/>`.
* javadoc:org.springframework.context.ApplicationContext[] trong XML file có thể được thêm thông qua javadoc:org.springframework.context.annotation.ImportResource[format=annotation] trong `+Application+`.
  Ngoài ra, các trường hợp đã sử dụng nhiều annotation configuration có thể được recreate bằng vài dòng javadoc:org.springframework.context.annotation.Bean[format=annotation] definition.

Khi war file đã hoạt động, bạn có thể làm cho nó executable bằng cách thêm method `main` vào `Application`, như trong ví dụ sau:

include-code::MyApplication[tag=main]

[NOTE]
====
Nếu định start application dưới dạng war hoặc executable application, bạn cần share customization của builder trong một method có thể được sử dụng cả bởi callback javadoc:org.springframework.boot.web.servlet.support.SpringBootServletInitializer[] và method `main` trong một class tương tự như sau:

include-code::both/MyApplication[]
====

Application có thể thuộc nhiều category:

* Servlet 3.0+ application không có `web.xml`.
* Application có `web.xml`.
* Application có context hierarchy.
* Application không có context hierarchy.

Tất cả các loại này đều có thể được chuyển đổi, nhưng mỗi loại có thể cần technique hơi khác.

Servlet 3.0+ application có thể được chuyển đổi khá dễ nếu đã sử dụng Spring Servlet 3.0+ initializer support class.
Thông thường, toàn bộ code từ existing javadoc:org.springframework.web.WebApplicationInitializer[] có thể được move vào javadoc:org.springframework.boot.web.servlet.support.SpringBootServletInitializer[].
Nếu existing application có nhiều hơn một javadoc:org.springframework.context.ApplicationContext[] (ví dụ sử dụng javadoc:org.springframework.web.servlet.support.AbstractDispatcherServletInitializer[]) thì bạn có thể combine toàn bộ context source vào một javadoc:org.springframework.boot.SpringApplication[].
Complication chính có thể xảy ra khi việc combine không hoạt động và bạn cần maintain context hierarchy.
Xem xref:application.adoc#howto.application.context-hierarchy[mục về xây dựng hierarchy] để biết các ví dụ.
Existing parent context chứa các web-specific feature thường cần được tách ra để tất cả component javadoc:org.springframework.web.context.ServletContextAware[] nằm trong child context.

Các application chưa phải là Spring application cũng có thể được convert sang Spring Boot application, và hướng dẫn đã nêu ở trên có thể hữu ích.
Tuy nhiên, bạn vẫn có thể gặp vấn đề.
Trong trường hợp đó, chúng tôi đề xuất https://stackoverflow.com/questions/tagged/spring-boot[đặt câu hỏi trên Stack Overflow với tag `spring-boot`].

[[howto.traditional-deployment.weblogic]]
== Deploy WAR lên WebLogic

Để deploy Spring Boot application lên WebLogic, bạn phải đảm bảo servlet initializer *trực tiếp* implement javadoc:org.springframework.web.WebApplicationInitializer[], kể cả khi bạn extend một base class đã implement interface đó.

Một initializer điển hình cho WebLogic như sau:

include-code::MyApplication[]

Nếu dùng Logback, bạn cũng cần cấu hình để WebLogic ưu tiên packaged version thay vì version được cài sẵn trên server.
Bạn có thể thực hiện việc này bằng cách thêm file `WEB-INF/weblogic.xml` với nội dung sau:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<wls:weblogic-web-app
	xmlns:wls="http://xmlns.oracle.com/weblogic/weblogic-web-app"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
		https://java.sun.com/xml/ns/javaee/ejb-jar_3_0.xsd
		http://xmlns.oracle.com/weblogic/weblogic-web-app
		https://xmlns.oracle.com/weblogic/weblogic-web-app/1.4/weblogic-web-app.xsd">
	<wls:container-descriptor>
		<wls:prefer-application-packages>
			<wls:package-name>org.slf4j</wls:package-name>
		</wls:prefer-application-packages>
	</wls:container-descriptor>
</wls:weblogic-web-app>
----
