[[aot]]
= Xử lý Ahead-of-Time

Spring AOT là process phân tích code tại build-time để tạo ra version được optimize.
Process này thường được dùng để hỗ trợ generate các native image của GraalVM.

Gradle plugin `org.springframework.boot.aot` cung cấp các task có thể dùng để thực hiện AOT processing trên cả application code và test code.
Plugin này tự động được apply khi {url-native-build-tools-docs-gradle-plugin}[GraalVM Native Image plugin] được apply:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$aot/apply-native-image-plugin.gradle[]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$aot/apply-native-image-plugin.gradle.kts[]
----
======

Nếu muốn xref:reference:packaging/aot.adoc[chạy một application đã được process bằng AOT trên JVM] thay vì dưới dạng native image, hãy apply plugin `org.springframework.boot.aot` trực tiếp:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$aot/apply-aot-plugin.gradle[]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$aot/apply-aot-plugin.gradle.kts[]
----
======

[[aot.processing-applications]]
== Xử lý application

Dựa trên main class được annotate bằng `@SpringBootApplication`, task `processAot` generate một persistent view của các bean sẽ được contribute tại runtime, để bean instantiation đơn giản nhất có thể.
Có thể thực hiện post-processing bổ sung trên factory bằng các callback.
Ví dụ, các callback này được dùng để generate reflection configuration cần thiết để GraalVM initialize context trong native image.

Vì `BeanFactory` được prepare hoàn toàn tại build-time, các condition cũng được evaluate.
Điều này tạo ra khác biệt quan trọng so với cách một Spring Boot application thông thường hoạt động tại runtime.
Ví dụ, nếu muốn opt-in hoặc opt-out một số feature, bạn cần configure environment được sử dụng tại build-time để thực hiện việc đó.
Để làm điều này, task `processAot` là {url-gradle-dsl}/org.gradle.api.tasks.JavaExec.html[`JavaExec`] task và có thể được configure bằng environment variable, system property và argument khi cần.

Task `nativeCompile` của GraalVM Native Image plugin được tự động configure để sử dụng output của task `processAot`.

[[aot.processing-tests]]
== Xử lý test

AOT engine có thể được apply cho các test JUnit 5 sử dụng Spring Test Context Framework.
Task `processTestAot` sẽ process các test phù hợp để generate code `ApplicationContextInitializer`.
Cũng như application AOT processing, `BeanFactory` được prepare hoàn toàn tại build-time.
Cũng như `processAot`, task `processTestAot` là subclass của `JavaExec` và có thể được configure khi cần để tác động đến processing này.

Task `nativeTest` của GraalVM Native Image plugin được tự động configure để sử dụng output của task `processAot` và `processTestAot`.
