[[getting-started]]
= Bắt đầu

Để bắt đầu sử dụng plugin, cần apply plugin vào project.

ifeval::["{build-type}" == "commercial"]
Plugin được publish lên Spring Commercial repository.
Cần configure build để access repository này.
Thông thường, việc này được thực hiện thông qua một local artifact repository dùng để mirror content của Spring Commercial repository.
Ngoài ra, dù không được khuyến nghị, có thể access trực tiếp Spring Commercial repository.
Trong cả hai trường hợp, xem https://docs.vmware.com/en/Tanzu-Spring-Runtime/Commercial/Tanzu-Spring-Runtime/spring-enterprise-subscription.html[tài liệu Tanzu Spring Runtime] để biết thêm chi tiết.

Sau khi configure access tới Spring Commercial repository trong `settings.gradle` hoặc `settings.gradle.kts`, có thể apply plugin bằng block `plugins`:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/apply-plugin-commercial.gradle[]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/apply-plugin-commercial.gradle.kts[]
----
======
endif::[]


ifeval::["{build-and-artifact-release-type}" == "opensource-release"]
Plugin được https://plugins.gradle.org/plugin/org.springframework.boot[publish lên plugin portal của Gradle] và có thể apply bằng block `plugins`:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/apply-plugin-release.gradle[]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/apply-plugin-release.gradle.kts[]
----
======
endif::[]

ifeval::["{build-and-artifact-release-type}" == "opensource-milestone"]
Plugin được publish lên Spring milestones repository.
Có thể configure Gradle để sử dụng milestones repository, sau đó apply plugin bằng block `plugins`.
Để configure Gradle sử dụng milestones repository, thêm vào `settings.gradle` (Groovy) hoặc `settings.gradle.kts` (Kotlin):

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/milestone-settings.gradle[]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/milestone-settings.gradle.kts[]
----
======

Sau đó có thể apply plugin bằng block `plugins`:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/apply-plugin-release.gradle[]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/apply-plugin-release.gradle.kts[]
----
======
endif::[]

ifeval::["{build-and-artifact-release-type}" == "opensource-snapshot"]
Plugin được publish lên Spring snapshots repository.
Có thể configure Gradle để sử dụng snapshots repository, sau đó apply plugin bằng block `plugins`.
Để configure Gradle sử dụng snapshots repository, thêm vào `settings.gradle` (Groovy) hoặc `settings.gradle.kts` (Kotlin):

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/snapshot-settings.gradle[]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/snapshot-settings.gradle.kts[]
----
======

Sau đó có thể apply plugin bằng block `plugins`:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/apply-plugin-release.gradle[]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/apply-plugin-release.gradle.kts[]
----
======
endif::[]

Khi được apply riêng lẻ, plugin chỉ thực hiện một vài thay đổi trên project.
Thay vào đó, plugin detect khi một số plugin khác được apply và react tương ứng.
Ví dụ, khi `java` plugin được apply, một task để build executable jar sẽ được auto-configure.
Một Spring Boot project điển hình tối thiểu sẽ apply {url-gradle-docs-groovy-plugin}[`groovy`], {url-gradle-docs-java-plugin}[`java`] hoặc {url-kotlin-docs-kotlin-plugin}[`org.jetbrains.kotlin.jvm`], đồng thời dùng {url-dependency-management-plugin-site}[`io.spring.dependency-management`] hoặc native bom support của Gradle cho dependency management.
Ví dụ:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/typical-plugins.gradle[tags=apply]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$getting-started/typical-plugins.gradle.kts[tags=apply]
----
======

Để tìm hiểu thêm về cách Spring Boot plugin react khi các plugin khác được apply, xem section xref:reacting.adoc[react với các plugin khác].
