[[managing-dependencies]]
= Managing Dependencies

Để manage dependency trong Spring Boot application, có thể apply {url-dependency-management-plugin-site}[`io.spring.dependency-management`] plugin hoặc dùng native bom support của Gradle.
Benefit chính của cách đầu là hỗ trợ property-based customization của managed version, còn cách sau thường cho build nhanh hơn.

[[managing-dependencies.dependency-management-plugin]]
== Managing Dependencies bằng Dependency Management Plugin

Khi apply {url-dependency-management-plugin-site}[`io.spring.dependency-management`] plugin, Spring Boot plugin tự động xref:reacting.adoc#reacting-to-other-plugins.dependency-management[import bom `spring-boot-dependencies`] từ version Spring Boot đang dùng.
Điều này cung cấp dependency management experience tương tự Maven.
Ví dụ cho phép omit version number khi declare dependency được manage trong bom.
Để dùng, declare dependency như bình thường nhưng omit version:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/dependencies.gradle[tags=dependencies]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/dependencies.gradle.kts[tags=dependencies]
----
======

[[managing-dependencies.dependency-management-plugin.customizing]]
=== Customize Managed Versions

Bom `spring-boot-dependencies` tự động import khi dependency management plugin apply dùng property để control version dependency nó manage.
Xem xref:appendix:dependency-versions/properties.adoc[Dependency Versions Properties] trong Spring Boot reference để biết complete list.

Để customize managed version, set property tương ứng.
Ví dụ customize SLF4J version được control bởi `slf4j.version`:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/custom-version.gradle[tags=custom-version]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/custom-version.gradle.kts[tags=custom-version]
----
======

WARNING: Mỗi Spring Boot release được design và test với specific set third-party dependency.
Override version có thể gây compatibility issue và cần cẩn thận.

[[managing-dependencies.dependency-management-plugin.using-in-isolation]]
=== Dùng Spring Boot Dependency Management riêng lẻ

Dependency management của Spring Boot có thể dùng trong project mà không apply Spring Boot plugin vào project đó.
Class `SpringBootPlugin` cung cấp constant `BOM_COORDINATES` dùng import bom mà không cần biết group ID, artifact ID hoặc version.

Đầu tiên configure project depend vào Spring Boot plugin nhưng không apply:

ifeval::["{build-type}" == "commercial"]
[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/depend-on-plugin-commercial.gradle[]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/depend-on-plugin-commercial.gradle.kts[]
----
======
endif::[]

ifeval::["{build-and-artifact-release-type}" == "opensource-release"]
[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/depend-on-plugin-release.gradle[]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/depend-on-plugin-release.gradle.kts[]
----
======
endif::[]

ifeval::["{build-and-artifact-release-type}" == "opensource-milestone"]
[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/depend-on-plugin-milestone.gradle[]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/depend-on-plugin-release.gradle.kts[]
----
======
endif::[]

ifeval::["{build-and-artifact-release-type}" == "opensource-snapshot"]
[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/depend-on-plugin-snapshot.gradle[]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/depend-on-plugin-release.gradle.kts[]
----
======
endif::[]

Dependency của Spring Boot plugin lên dependency management plugin nghĩa là có thể dùng dependency management plugin mà không cần declare dependency vào nó.
Điều này cũng nghĩa là tự động dùng cùng version dependency management plugin Spring Boot dùng.

Apply dependency management plugin rồi configure import Spring Boot bom:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/configure-bom.gradle[tags=configure-bom]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/configure-bom.gradle.kts[tags=configure-bom]
----
======

Kotlin code trên hơi awkward vì dùng imperative way apply dependency management plugin.

Có thể giảm awkward bằng cách apply plugin từ root parent project hoặc dùng block `plugins` như với Spring Boot plugin.
Downside là bắt buộc specify version của dependency management plugin:

[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/configure-bom-with-plugins.gradle.kts[tags=configure-bom]
----

[[managing-dependencies.dependency-management-plugin.learning-more]]
=== Learning More

Để biết thêm capability của dependency management plugin, xem {url-dependency-management-plugin-docs}[documentation].

[[managing-dependencies.gradle-bom-support]]
== Managing Dependencies bằng Gradle Bom Support

Gradle cho phép dùng bom manage project version bằng cách declare nó như dependency `platform` hoặc `enforcedPlatform`.
Dependency `platform` xem version trong bom như recommendation; version/constraint khác trong dependency graph có thể khiến dùng version khác với bom.
Dependency `enforcedPlatform` xem version trong bom như requirement và override mọi version khác trong dependency graph.

Class `SpringBootPlugin` cung cấp constant `BOM_COORDINATES` dùng declare dependency lên Spring Boot bom mà không cần biết group ID, artifact ID hoặc version:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/configure-platform.gradle[tags=configure-platform]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/configure-platform.gradle.kts[tags=configure-platform]
----
======

Platform hoặc enforced platform chỉ constrain version của configuration nơi nó declare hoặc configuration extend từ đó.
Do vậy có thể cần declare cùng dependency trong nhiều configuration.

[[managing-dependencies.gradle-bom-support.customizing]]
=== Customize Managed Versions

Khi dùng Gradle bom support, không thể dùng property từ `spring-boot-dependencies` để control version dependency nó manage.
Thay vào đó phải dùng mechanism Gradle cung cấp.
Một mechanism là resolution strategy.
Module SLF4J đều ở group `org.slf4j` nên version có thể control bằng cách configure mọi dependency trong group đó dùng particular version:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/custom-version-with-platform.gradle[tags=custom-version]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$managing-dependencies/custom-version-with-platform.gradle.kts[tags=custom-version]
----
======

WARNING: Mỗi Spring Boot release được design và test với specific set third-party dependency.
Override version có thể gây compatibility issue và cần cẩn thận.
