[[publishing-your-application]]
= Publishing Application

[[publishing-your-application.maven-publish]]
== Publishing bằng Maven-publish Plugin

Để publish Spring Boot jar hoặc war, thêm nó vào publication bằng method `artifact` trên `MavenPublication`.
Truyền task tạo artifact muốn publish vào method `artifact`.
Ví dụ để publish artifact do default task `bootJar` tạo:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$publishing/maven-publish.gradle[tags=publishing]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$publishing/maven-publish.gradle.kts[tags=publishing]
----
======

[[publishing-your-application.distribution]]
== Distributing bằng Application Plugin

Khi {url-gradle-docs-application-plugin}[`application` plugin] được apply, distribution tên `boot` được tạo.
Distribution này chứa archive do task `bootJar` hoặc `bootWar` tạo và script để launch nó trên Unix-like platform và Windows.
Zip và tar distribution có thể build bằng task `bootDistZip` và `bootDistTar` tương ứng.
Để dùng `application` plugin, property `mainClassName` phải configure với name của main class application.
