[[running-your-application]]
= Running your Application with Gradle

Để chạy application mà không build archive trước, dùng task `bootRun`:

[source,shell]
----
$ ./gradlew bootRun
----

Task `bootRun` là instance của {apiref-gradle-plugin-boot-run}[`BootRun`], subclass của `JavaExec`.
Do đó mọi {url-gradle-dsl}/org.gradle.api.tasks.JavaExec.html[usual configuration option] để execute Java process trong Gradle đều available.
Task tự động configure dùng runtime classpath của main source set.

Mặc định main class tự động configure bằng cách tìm class có method `public static void main(String[])` trong output main source set.

Main class cũng có thể explicit configure bằng property `main` của task:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-main.gradle[tags=main]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-main.gradle.kts[tags=main]
----
======

Ngoài ra main class name có thể configure project-wide bằng property `mainClass` của Spring Boot DSL:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/spring-boot-dsl-main-class-name.gradle[tags=main-class]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/spring-boot-dsl-main-class-name.gradle.kts[tags=main-class]
----
======

Mặc định `bootRun` configure JVM optimize launch để startup nhanh hơn trong development.
Disable behavior bằng property `optimizedLaunch`:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-disable-optimized-launch.gradle[tags=launch]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-disable-optimized-launch.gradle.kts[tags=launch]
----
======

Nếu {url-gradle-docs-application-plugin}[`application` plugin] được apply, property `mainClass` của nó phải configure và có thể dùng cùng mục đích:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/application-plugin-main-class-name.gradle[tags=main-class]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/application-plugin-main-class-name.gradle.kts[tags=main-class]
----
======

[[running-your-application.passing-arguments]]
== Passing Arguments tới Application

Giống mọi task `JavaExec`, argument có thể pass vào `bootRun` từ command line bằng `--args='<arguments>'` khi dùng Gradle 4.9 trở lên.
Ví dụ chạy application với profile `dev` active:

[source,shell]
----
$ ./gradlew bootRun --args='--spring.profiles.active=dev'
----

Xem {url-gradle-javadoc}/org/gradle/api/tasks/JavaExec.html#setArgsString(java.lang.String)[javadoc của `JavaExec.setArgsString`].

[[running-your-application.passing-system-properties]]
== Passing System Properties tới Application

Vì `bootRun` là standard `JavaExec` task, system property có thể pass tới JVM application bằng cách specify trong build script.
Để value system property configurable, set value bằng {url-gradle-dsl}/org.gradle.api.Project.html#N14FE1[project property].
Để project property optional, reference bằng `findProperty`.
Cách này cũng cho phép cung cấp default bằng Elvis operator `?:`:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-system-property.gradle[tags=system-property]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-system-property.gradle.kts[tags=system-property]
----
======

Ví dụ trên set system property `com.example.property` bằng value của project property `example`.
Nếu `example` không set, system property value là `default`.

Gradle cho phép set project property theo nhiều cách, gồm command line với flag `-P`:

[source,bash,indent=0,subs="verbatim,attributes"]
----
$ ./gradlew bootRun -Pexample=custom
----

Ví dụ set project property `example` thành `custom`.
`bootRun` sau đó dùng value này cho system property `com.example.property`.

[[running-your-application.reloading-resources]]
== Reloading Resources

Nếu devtools được add vào project, nó tự động monitor application classpath để phát hiện change.
Modified file cần recompile để classpath update và trigger reload với devtools.
Chi tiết xem xref:reference:using/devtools.adoc#using.devtools.restart[reference documentation].

Ngoài ra có thể configure `bootRun` để static resource của application load từ source location:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-source-resources.gradle[tags=source-resources]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-source-resources.gradle.kts[tags=source-resources]
----
======

Điều này làm resource reloadable trong live application, hữu ích ở development time.

[[running-your-application.using-a-test-main-class]]
== Dùng Test Main Class

Ngoài `bootRun`, task `bootTestRun` cũng được register.
Giống `bootRun`, `bootTestRun` là instance `BootRun` nhưng configure dùng main class tìm trong output test source set thay vì main source set.
Nó cũng dùng runtime classpath của test source set thay vì main source set.
Vì `bootTestRun` là instance BootRun, mọi configuration option mô tả ở trên cho `bootRun` cũng dùng được với `bootTestRun`.
