[[running-your-application]]
= Chạy Application với Gradle

Để chạy application mà không build archive trước, hãy dùng task `bootRun`:

[source,shell]
----
$ ./gradlew bootRun
----

Task `bootRun` là một instance của {apiref-gradle-plugin-boot-run}[`BootRun`], vốn là subclass của `JavaExec`.
Do đó, tất cả {url-gradle-dsl}/org.gradle.api.tasks.JavaExec.html[các configuration options thông thường] để execute một Java process trong Gradle đều khả dụng.
Task này tự động được configure để dùng runtime classpath của main source set.

Mặc định, main class sẽ được tự động configure bằng cách tìm một class có method `public static void main(String[])` trong output của main source set.

Main class cũng có thể được configure một cách explicit bằng property `main` của task:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-main.gradle[tags=main]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-main.gradle.kts[tags=main]
----
======

Ngoài ra, tên main class có thể được configure ở cấp project bằng property `mainClass` của Spring Boot DSL:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/spring-boot-dsl-main-class-name.gradle[tags=main-class]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/spring-boot-dsl-main-class-name.gradle.kts[tags=main-class]
----
======

Mặc định, `bootRun` configure JVM để optimize việc launch nhằm startup nhanh hơn trong quá trình development.
Có thể disable behavior này bằng property `optimizedLaunch`, như trong ví dụ sau:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-disable-optimized-launch.gradle[tags=launch]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-disable-optimized-launch.gradle.kts[tags=launch]
----
======

Nếu {url-gradle-docs-application-plugin}[`application` plugin] đã được apply, phải configure property `mainClass` của plugin này; property đó có thể được dùng cho cùng mục đích:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/application-plugin-main-class-name.gradle[tags=main-class]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/application-plugin-main-class-name.gradle.kts[tags=main-class]
----
======



[[running-your-application.passing-arguments]]
== Truyền Arguments vào Application

Giống như mọi task `JavaExec`, có thể truyền arguments vào `bootRun` từ command line bằng `--args='<arguments>'` khi dùng Gradle 4.9 trở lên.
Ví dụ, để chạy application với profile `dev` active, có thể dùng command sau:

[source,shell]
----
$ ./gradlew bootRun --args='--spring.profiles.active=dev'
----

Xem {url-gradle-javadoc}/org/gradle/api/tasks/JavaExec.html#setArgsString(java.lang.String)[javadoc của `JavaExec.setArgsString`] để biết thêm chi tiết.



[[running-your-application.passing-system-properties]]
== Truyền System Properties vào Application

Vì `bootRun` là một `JavaExec` task chuẩn, có thể truyền system properties vào JVM của application bằng cách chỉ định chúng trong build script.
Để value của một system property có thể được configure, hãy set value đó bằng {url-gradle-dsl}/org.gradle.api.Project.html#N14FE1[project property].
Để một project property là optional, hãy reference property đó bằng `findProperty`.
Cách này cũng cho phép cung cấp default value bằng Elvis operator `?:`, như trong ví dụ sau:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-system-property.gradle[tags=system-property]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-system-property.gradle.kts[tags=system-property]
----
======

Ví dụ trên set system property `com.example.property` thành value của project property `example`.
Nếu project property `example` chưa được set, value của system property sẽ là `default`.

Gradle cho phép set project properties theo nhiều cách, trong đó có command line với flag `-P`, như trong ví dụ sau:

[source,bash,indent=0,subs="verbatim,attributes"]
----
$ ./gradlew bootRun -Pexample=custom
----

Ví dụ trên set value của project property `example` thành `custom`.
Sau đó, `bootRun` sẽ dùng value này làm value của system property `com.example.property`.



[[running-your-application.reloading-resources]]
== Reload Resources

Nếu devtools đã được add vào project, devtools sẽ tự động monitor classpath của application để phát hiện các thay đổi.
Lưu ý rằng các file đã sửa cần được recompile để classpath được update, từ đó trigger reload bằng devtools.
Để biết thêm chi tiết về cách dùng devtools, hãy xem xref:reference:using/devtools.adoc#using.devtools.restart[section này trong reference documentation].

Ngoài ra, bạn có thể configure `bootRun` để static resources của application được load từ source location:

[tabs]
======
Groovy::
+
[source,groovy,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-source-resources.gradle[tags=source-resources]
----
Kotlin::
+
[source,kotlin,indent=0,subs="verbatim,attributes"]
----
include::example$running/boot-run-source-resources.gradle.kts[tags=source-resources]
----
======

Điều này khiến các resource có thể reload trong live application, hữu ích trong quá trình development.



[[running-your-application.using-a-test-main-class]]
== Sử dụng Test Main Class

Ngoài `bootRun`, một task `bootTestRun` cũng được register.
Giống `bootRun`, `bootTestRun` là một instance của `BootRun`, nhưng được configure để dùng main class được tìm thấy trong output của test source set thay vì main source set.
Task này cũng dùng runtime classpath của test source set thay vì runtime classpath của main source set.
Vì `bootTestRun` là một instance của `BootRun`, mọi configuration option được mô tả ở trên cho `bootRun` cũng có thể được dùng với `bootTestRun`.
