[[howto.actuator]]
= Actuator

Spring Boot bao gồm Spring Boot Actuator.
Phần này giải đáp những câu hỏi thường phát sinh khi sử dụng nó.



[[howto.actuator.change-http-port-or-address]]
== Thay đổi HTTP Port hoặc Address của Actuator Endpoints

Trong standalone application, Actuator HTTP port mặc định bằng main HTTP port.
Để application listen trên port khác, hãy set external property: configprop:management.server.port[].
Để listen trên một network address hoàn toàn khác (chẳng hạn khi có một internal network cho management và một external network cho user application), bạn cũng có thể set `management.server.address` thành một valid IP address mà server có thể bind vào.

Để biết thêm chi tiết, xem source code javadoc:org.springframework.boot.actuate.autoconfigure.web.server.ManagementServerProperties[] và xref:reference:actuator/monitoring.adoc#actuator.monitoring.customizing-management-server-port[Tùy chỉnh Management Server Port] trong section "`Các tính năng sẵn sàng cho production`".



[[howto.actuator.customizing-sanitization]]
== Tùy chỉnh Sanitization

Để kiểm soát sanitization, hãy define một bean javadoc:org.springframework.boot.actuate.endpoint.SanitizingFunction[].
javadoc:org.springframework.boot.actuate.endpoint.SanitizableData[] được truyền vào function cung cấp access tới key và value, cũng như javadoc:org.springframework.core.env.PropertySource[] mà chúng được lấy từ đó.
Điều này cho phép bạn, chẳng hạn, sanitize mọi value đến từ một property source cụ thể.
Mỗi javadoc:org.springframework.boot.actuate.endpoint.SanitizingFunction[] được gọi lần lượt cho đến khi một function thay đổi value của sanitizable data.



[[howto.actuator.map-health-indicators-to-metrics]]
== Map Health Indicators thành Micrometer Metrics

Các health indicator của Spring Boot trả về một type javadoc:org.springframework.boot.health.contributor.Status[] để biểu thị overall system health.
Nếu muốn monitor hoặc alert theo các health level của một application cụ thể, bạn có thể export các status này thành metrics bằng Micrometer.
Theo mặc định, Spring Boot sử dụng các status code "`UP`", "`DOWN`", "`OUT_OF_SERVICE`" và "`UNKNOWN`".
Để export các status này, bạn cần convert các state này thành một tập hợp số để có thể sử dụng với một Micrometer javadoc:io.micrometer.core.instrument.Gauge[].

Ví dụ sau cho thấy một cách viết exporter như vậy:

include-code::MyHealthMetricsExportConfiguration[]
