[[howto.aot]]
= Xử lý Ahead-of-Time

Một số câu hỏi thường phát sinh khi sử dụng ahead-of-time processing cho ứng dụng Spring Boot.
Phần này giải đáp các câu hỏi đó.



[[howto.aot.conditions]]
== Conditions

Ahead-of-time processing tối ưu hóa application và evaluate các annotation javadoc:org.springframework.context.annotation.Conditional[format=annotation] dựa trên environment tại build time.
xref:reference:features/profiles.adoc[Profiles] được implement thông qua các condition nên cũng chịu ảnh hưởng.

Nếu muốn các bean được tạo dựa trên condition trong application được tối ưu hóa bằng ahead-of-time processing, phải setup environment khi build application.
Các bean được tạo trong quá trình ahead-of-time processing tại build time sau đó sẽ luôn được tạo khi chạy application và không thể tắt.
Để làm vậy, có thể set các profile cần dùng khi build application.

Đối với Maven, việc này được thực hiện bằng cách set configuration `profiles` của execution `spring-boot-maven-plugin:process-aot`:

[source,xml]
----
<profile>
    <id>native</id>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>process-aot</id>
                            <configuration>
                                <profiles>profile-a,profile-b</profiles>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</profile>
----

Đối với Gradle, cần configure task `ProcessAot`:

[source,gradle]
----
tasks.withType(org.springframework.boot.gradle.tasks.aot.ProcessAot).configureEach {
    args('--spring.profiles.active=profile-a,profile-b')
}
----

Các profile chỉ thay đổi configuration properties không ảnh hưởng đến các condition vẫn được hỗ trợ đầy đủ khi chạy application được tối ưu hóa bằng ahead-of-time processing.
