[[howto.data-initialization]]
= Khởi tạo Database

SQL database có thể được khởi tạo theo nhiều cách tùy thuộc stack bạn đang dùng.
Tất nhiên, bạn cũng có thể thực hiện thủ công nếu database là một process riêng.
Khuyến nghị sử dụng một mechanism duy nhất để schema generation.



[[howto.data-initialization.using-hibernate]]
== Khởi tạo Database bằng Hibernate

Bạn có thể set configprop:spring.jpa.hibernate.ddl-auto[] để control database initialization của Hibernate.
Các value được hỗ trợ là `none`, `validate`, `update`, `create` và `create-drop`.
Spring Boot chọn default value dựa trên việc bạn có sử dụng embedded database hay không.
Embedded database được xác định bằng cách kiểm tra type javadoc:java.sql.Connection[] và JDBC URL.
`hsqldb`, `h2` hoặc `derby` (deprecated) là embedded database; các database khác thì không.
Nếu xác định được embedded database và chưa detect schema manager (Flyway hoặc Liquibase), `ddl-auto` default là `create-drop`.
Trong mọi trường hợp khác, default là `none`.

Hãy cẩn thận khi switch từ in-memory sang database '`real`' để không assume rằng các table và data tồn tại trên platform mới.
Bạn phải set `ddl-auto` một cách explicit hoặc sử dụng một trong các mechanism khác để initialize database.

NOTE: Bạn có thể output schema creation bằng cách enable logger `org.hibernate.SQL`.
Việc này được tự động thực hiện nếu bạn enable xref:reference:features/logging.adoc#features.logging.console-output[debug mode].

Ngoài ra, file `import.sql` ở root của classpath được execute khi startup nếu Hibernate tạo schema from scratch (nghĩa là property `ddl-auto` được set thành `create` hoặc `create-drop`).
Điều này có thể hữu ích cho demo và testing nếu bạn cẩn thận, nhưng có lẽ bạn không muốn file này nằm trên classpath trong production.
Đây là feature của Hibernate và không liên quan đến Spring.



[[howto.data-initialization.using-basic-sql-scripts]]
== Khởi tạo Database bằng Basic SQL Scripts

Spring Boot có thể tự động tạo schema (DDL scripts) cho JDBC javadoc:javax.sql.DataSource[] hoặc R2DBC javadoc:io.r2dbc.spi.ConnectionFactory[] và initialize data (DML scripts) của chúng.

Theo mặc định, Spring Boot load schema scripts từ `optional:classpath*:schema.sql` và data scripts từ `optional:classpath*:data.sql`.
Bạn có thể customize location của các schema và data script này lần lượt bằng configprop:spring.sql.init.schema-locations[] và configprop:spring.sql.init.data-locations[].
Prefix `optional:` nghĩa là application vẫn start ngay cả khi các file không tồn tại.
Để application fail khi start nếu các file bị thiếu, hãy remove prefix `optional:`.

Ngoài ra, Spring Boot process các file `optional:classpath*:schema-$\{platform}.sql` và `optional:classpath*:data-$\{platform}.sql` (nếu có), trong đó `$\{platform}` là value của configprop:spring.sql.init.platform[].
Điều này cho phép bạn switch sang database-specific scripts khi cần.
Ví dụ, bạn có thể set value này thành vendor name của database (`hsqldb`, `h2`, `oracle`, `mysql`, `postgresql`, v.v.).

Theo mặc định, SQL database initialization chỉ được thực hiện khi sử dụng embedded in-memory database.
Để luôn initialize SQL database bất kể type của nó, set configprop:spring.sql.init.mode[] thành `always`.
Tương tự, để disable initialization, set configprop:spring.sql.init.mode[] thành `never`.
Theo mặc định, Spring Boot enable fail-fast feature của script-based database initializer.
Điều này có nghĩa là nếu các script gây ra exception, application sẽ fail khi start.
Bạn có thể tune behavior này bằng cách set configprop:spring.sql.init.continue-on-error[].

Script-based javadoc:javax.sql.DataSource[] initialization mặc định được thực hiện trước khi bất kỳ JPA javadoc:jakarta.persistence.EntityManagerFactory[] bean nào được tạo.
Bạn có thể sử dụng `schema.sql` để tạo schema cho JPA-managed entities và `data.sql` để populate schema đó.
Mặc dù không khuyến nghị sử dụng nhiều data source initialization technologies, nếu muốn script-based javadoc:javax.sql.DataSource[] initialization build trên schema do Hibernate tạo, hãy set configprop:spring.jpa.defer-datasource-initialization[] thành `true`.
Việc này sẽ defer data source initialization cho đến sau khi mọi javadoc:jakarta.persistence.EntityManagerFactory[] bean đã được tạo và initialized.
Sau đó, `schema.sql` có thể được sử dụng để bổ sung vào schema do Hibernate tạo và `data.sql` có thể được sử dụng để populate schema đó.

NOTE: Initialization scripts hỗ trợ `--` cho single-line comments và `/++*++ ++*++/` cho block comments.
Các comment format khác không được hỗ trợ.

Nếu bạn sử dụng xref:data-initialization.adoc#howto.data-initialization.migration-tool[higher-level database migration tool] như Flyway hoặc Liquibase, bạn nên chỉ sử dụng tool đó để create và initialize schema.
Không khuyến nghị sử dụng các basic `schema.sql` và `data.sql` cùng với Flyway hoặc Liquibase; support cho cách này sẽ bị remove trong một future release.

Nếu cần initialize test data bằng higher-level database migration tool, hãy xem các section về xref:data-initialization.adoc#howto.data-initialization.migration-tool.flyway-tests[Flyway] và xref:data-initialization.adoc#howto.data-initialization.migration-tool.liquibase-tests[Liquibase].



[[howto.data-initialization.batch]]
== Khởi tạo Spring Batch Database

Nếu sử dụng Spring Batch, bạn sẽ có sẵn các SQL initialization scripts cho hầu hết database platform phổ biến.
Spring Boot có thể detect database type và execute các script đó khi startup.
Nếu sử dụng embedded database, việc này được thực hiện by default.
Bạn cũng có thể enable việc này cho mọi database type, như trong ví dụ sau:

[configprops,yaml]
----
spring:
  batch:
    jdbc:
      initialize-schema: "always"
----

Bạn cũng có thể switch off initialization một cách explicit bằng cách set `spring.batch.jdbc.initialize-schema` thành `never`.



[[howto.data-initialization.migration-tool]]
== Sử dụng Higher-level Database Migration Tool

Spring Boot hỗ trợ hai higher-level migration tool: https://flywaydb.org/[Flyway] và https://www.liquibase.org/[Liquibase].



[[howto.data-initialization.migration-tool.flyway]]
=== Chạy Flyway Database Migrations khi Startup

Để tự động chạy Flyway database migrations khi startup, hãy add Flyway module phù hợp vào classpath.
In-memory và file-based databases được hỗ trợ bởi starter `spring-boot-starter-flyway`.
Các trường hợp khác cũng yêu cầu một database-specific module.
Ví dụ, sử dụng `org.flywaydb:flyway-database-postgresql` với PostgreSQL và `org.flywaydb:flyway-mysql` với MySQL.
Xem https://documentation.red-gate.com/fd/supported-databases-and-versions-143754067.html[Tài liệu Flyway] để biết thêm chi tiết.

Thông thường, migrations là các script có dạng `V<VERSION>__<NAME>.sql` (trong đó `<VERSION>` là một version phân tách bằng underscore, chẳng hạn '`1`' hoặc '`2_1`').
Theo mặc định, chúng nằm trong directory `classpath:db/migration`, nhưng bạn có thể thay đổi location đó bằng cách set `spring.flyway.locations`.
Đây là một comma-separated list gồm một hoặc nhiều location `classpath:` hoặc `filesystem:`.
Ví dụ, configuration sau sẽ search các script trong cả default classpath location và directory `/opt/migration`:

[configprops,yaml]
----
spring:
  flyway:
    locations: "classpath:db/migration,filesystem:/opt/migration"
----

Bạn cũng có thể thêm placeholder đặc biệt `\{vendor}` để sử dụng vendor-specific scripts.
Giả sử có configuration sau:

[configprops,yaml]
----
spring:
  flyway:
    locations: "classpath:db/migration/{vendor}"
----

Thay vì sử dụng `db/migration`, configuration trước đó set directory cần dùng dựa trên type của database (chẳng hạn `db/migration/mysql` cho MySQL).
Danh sách các database được hỗ trợ có trong javadoc:org.springframework.boot.jdbc.DatabaseDriver[].

Bạn cũng có thể viết migrations bằng Java.
Flyway sẽ được auto-configure với mọi bean implement javadoc:org.flywaydb.core.api.migration.JavaMigration[].

javadoc:org.springframework.boot.flyway.autoconfigure.FlywayProperties[] cung cấp hầu hết Flyway settings và một tập hợp nhỏ các additional properties có thể dùng để disable migrations hoặc switch off location checking.
Nếu cần control configuration nhiều hơn, hãy cân nhắc register một bean javadoc:org.springframework.boot.flyway.autoconfigure.FlywayConfigurationCustomizer[].

Spring Boot gọi `Flyway.migrate()` để thực hiện database migration.
Nếu muốn nhiều control hơn, hãy cung cấp một javadoc:org.springframework.context.annotation.Bean[format=annotation] implement javadoc:org.springframework.boot.flyway.autoconfigure.FlywayMigrationStrategy[].

Flyway hỗ trợ https://documentation.red-gate.com/fd/callbacks-275218509.html[callbacks] bằng SQL và Java.
Để sử dụng SQL-based callbacks, đặt các callback scripts trong directory `classpath:db/migration`.
Để sử dụng Java-based callbacks, tạo một hoặc nhiều bean implement javadoc:org.flywaydb.core.api.callback.Callback[].
Mọi bean như vậy đều được tự động register với javadoc:org.flywaydb.core.Flyway[].
Bạn có thể order chúng bằng javadoc:org.springframework.core.annotation.Order[format=annotation] hoặc bằng cách implement javadoc:org.springframework.core.Ordered[].

Theo mặc định, Flyway autowire (`@Primary`) javadoc:javax.sql.DataSource[] trong context của bạn và sử dụng nó cho migrations.
Nếu muốn sử dụng một javadoc:javax.sql.DataSource[] khác, bạn có thể tạo một DataSource và đánh dấu javadoc:org.springframework.context.annotation.Bean[format=annotation] của nó bằng javadoc:org.springframework.boot.flyway.autoconfigure.FlywayDataSource[format=annotation].
Nếu làm vậy và muốn có hai data source (chẳng hạn vẫn giữ main auto-configured javadoc:javax.sql.DataSource[]), hãy nhớ set attribute `defaultCandidate` của javadoc:org.springframework.context.annotation.Bean[format=annotation] annotation thành `false`.
Ngoài ra, bạn có thể sử dụng native javadoc:javax.sql.DataSource[] của Flyway bằng cách set `spring.flyway.[url,user,password]` trong external properties.
Chỉ cần set `spring.flyway.url` hoặc `spring.flyway.user` là Flyway sẽ sử dụng javadoc:javax.sql.DataSource[] của riêng nó.
Nếu chưa set property nào trong ba properties này, value của `spring.datasource` property tương ứng sẽ được sử dụng.

Bạn cũng có thể sử dụng Flyway để cung cấp data cho các specific scenarios.
Ví dụ, bạn có thể đặt test-specific migrations trong `src/test/resources`; chúng chỉ được run khi application start để testing.
Bạn cũng có thể sử dụng profile-specific configuration để customize `spring.flyway.locations` sao cho một số migrations chỉ run khi một profile cụ thể active.
Ví dụ, trong `application-dev.properties`, bạn có thể chỉ định setting sau:

[configprops,yaml]
----
spring:
  flyway:
    locations: "classpath:/db/migration,classpath:/dev/db/migration"
----

Với setup này, các migrations trong `dev/db/migration` chỉ run khi profile `dev` active.



[[howto.data-initialization.migration-tool.liquibase]]
=== Chạy Liquibase Database Migrations khi Startup

Để tự động run Liquibase database migrations khi startup, hãy add starter `spring-boot-starter-liquibase` vào classpath.

[NOTE]
====
Khi add `spring-boot-starter-liquibase` vào classpath, database migrations mặc định run cả trong application startup và trước khi tests run.
Bạn có thể customize behavior này bằng property configprop:spring.liquibase.enabled[], set các value khác nhau trong `main` và `test` configurations.
Không thể sử dụng hai cách khác nhau để initialize database (chẳng hạn Liquibase cho application startup và JPA cho test runs).
====

Theo mặc định, master change log được đọc từ `db/changelog/db.changelog-master.yaml`, nhưng bạn có thể thay đổi location bằng cách set `spring.liquibase.change-log`.
Ngoài YAML, Liquibase cũng hỗ trợ các change log format là JSON, XML và SQL.

Theo mặc định, Liquibase autowire (`@Primary`) javadoc:javax.sql.DataSource[] trong context của bạn và sử dụng nó cho migrations.
Nếu cần sử dụng một javadoc:javax.sql.DataSource[] khác, bạn có thể tạo một DataSource và đánh dấu javadoc:org.springframework.context.annotation.Bean[format=annotation] của nó bằng javadoc:org.springframework.boot.liquibase.autoconfigure.LiquibaseDataSource[format=annotation].
Nếu làm vậy và muốn có hai data source (chẳng hạn vẫn giữ main auto-configured javadoc:javax.sql.DataSource[]), hãy nhớ set attribute `defaultCandidate` của javadoc:org.springframework.context.annotation.Bean[format=annotation] annotation thành `false`.
Ngoài ra, bạn có thể sử dụng native javadoc:javax.sql.DataSource[] của Liquibase bằng cách set `spring.liquibase.[driver-class-name,url,user,password]` trong external properties.
Chỉ cần set `spring.liquibase.url` hoặc `spring.liquibase.user` là Liquibase sẽ sử dụng javadoc:javax.sql.DataSource[] của riêng nó.
Nếu chưa set property nào trong ba properties này, value của `spring.datasource` property tương ứng sẽ được sử dụng.

Xem javadoc:org.springframework.boot.liquibase.autoconfigure.LiquibaseProperties[] để biết chi tiết về các settings hiện có, chẳng hạn contexts, default schema và các settings khác.

Bạn cũng có thể sử dụng bean `Customizer<Liquibase>` nếu muốn customize instance javadoc:{url-liquibase-javadoc}/liquibase.Liquibase[] trước khi instance đó được sử dụng.



[[howto.data-initialization.migration-tool.flyway-tests]]
=== Sử dụng Flyway cho Test-only Migrations

Nếu muốn tạo Flyway migrations để populate test database, hãy đặt chúng trong `src/test/resources/db/migration`.
Ví dụ, file `src/test/resources/db/migration/V9999__test-data.sql` sẽ được execute sau production migrations và chỉ khi bạn đang run tests.
Bạn có thể sử dụng file này để tạo test data cần thiết.
File này sẽ không được package vào uber jar hoặc container.



[[howto.data-initialization.migration-tool.liquibase-tests]]
=== Sử dụng Liquibase cho Test-only Migrations

Nếu muốn tạo Liquibase migrations để populate test database, bạn có thể tận dụng https://docs.liquibase.com/reference-guide/changelog-attributes/what-are-contexts[Liquibase contexts].
Xem thêm https://www.liquibase.com/blog/contexts-vs-labels[bài blog] liên quan.

Về thực tế, việc này có nghĩa là thêm attribute `context:@test` vào các changeset chứa test data, như sau:

[source,sql]
----
--liquibase formatted sql

--changeset alice:1 context:@test
insert into project (id, name) values (1, 'Spring Boot');
----

Và sử dụng `spring.liquibase.contexts=test` trong các environments nơi bạn muốn apply các changeset chứa test data.



[[howto.data-initialization.dependencies]]
== Phụ thuộc vào Database đã được khởi tạo

Database initialization được thực hiện khi application startup, như một phần của application context refresh.
Để một initialized database có thể được access khi startup, các bean đóng vai trò database initializers và các bean yêu cầu database đã được initialized sẽ được tự động detect.
Các bean có initialization phụ thuộc vào database đã được initialized sẽ được configure để phụ thuộc vào các bean initialize database đó.
Nếu trong khi startup, application của bạn cố access database nhưng database chưa được initialized, bạn có thể configure additional detection cho các bean initialize database và các bean yêu cầu database đã được initialized.



[[howto.data-initialization.dependencies.initializer-detection]]
=== Phát hiện Database Initializer

Spring Boot sẽ tự động detect các bean thuộc những type sau, vốn initialize SQL database:

- javadoc:org.springframework.boot.jdbc.init.DataSourceScriptDatabaseInitializer[]
- javadoc:jakarta.persistence.EntityManagerFactory[]
- javadoc:org.flywaydb.core.Flyway[]
- javadoc:org.springframework.boot.flyway.autoconfigure.FlywayMigrationInitializer[]
- javadoc:org.springframework.boot.r2dbc.init.R2dbcScriptDatabaseInitializer[]
- javadoc:liquibase.integration.spring.SpringLiquibase[]

Nếu sử dụng third-party starter cho database initialization library, starter đó có thể cung cấp một detector để các bean thuộc type khác cũng được tự động detect.
Để các bean khác được detect, hãy register một implementation của javadoc:org.springframework.boot.sql.init.dependency.DatabaseInitializerDetector[] trong `META-INF/spring.factories`.



[[howto.data-initialization.dependencies.depends-on-initialization-detection]]
=== Phát hiện Bean Phụ thuộc Database Initialization

Spring Boot sẽ tự động detect các bean thuộc những type sau, vốn phụ thuộc vào database initialization:

- javadoc:org.springframework.orm.jpa.AbstractEntityManagerFactoryBean[] (trừ khi configprop:spring.jpa.defer-datasource-initialization[] được set thành `true`)
- javadoc:org.jooq.DSLContext[] (jOOQ)
- javadoc:jakarta.persistence.EntityManagerFactory[] (trừ khi configprop:spring.jpa.defer-datasource-initialization[] được set thành `true`)
- javadoc:org.springframework.jdbc.core.simple.JdbcClient[]
- javadoc:org.springframework.jdbc.core.JdbcOperations[]
- javadoc:org.springframework.jdbc.core.namedparam.NamedParameterJdbcOperations[]

Nếu sử dụng third-party starter cho data access library, starter đó có thể cung cấp một detector để các bean thuộc type khác cũng được tự động detect.
Để các bean khác được detect, hãy register một implementation của javadoc:org.springframework.boot.sql.init.dependency.DependsOnDatabaseInitializationDetector[] trong `META-INF/spring.factories`.
Ngoài ra, hãy annotate class của bean hoặc method javadoc:org.springframework.context.annotation.Bean[format=annotation] bằng javadoc:org.springframework.boot.sql.init.dependency.DependsOnDatabaseInitialization[format=annotation].
