[[howto.docker-compose]]
= Docker Compose

Phần này gồm các chủ đề liên quan đến hỗ trợ Docker Compose trong Spring Boot.



[[howto.docker-compose.jdbc-url]]
== Tùy chỉnh JDBC URL

Khi dùng javadoc:org.springframework.boot.jdbc.autoconfigure.JdbcConnectionDetails[] với Docker Compose, các parameter của JDBC URL có thể được tùy chỉnh bằng cách áp dụng label `org.springframework.boot.jdbc.parameters` cho service.
Ví dụ:

[source,yaml]
----
services:
  postgres:
    image: 'postgres:15.3'
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=mydb'
    ports:
      - '5432:5432'
    labels:
      org.springframework.boot.jdbc.parameters: 'ssl=true&sslmode=require'
----

Với file Docker Compose này, JDBC URL được sử dụng là `jdbc:postgresql://127.0.0.1:5432/mydb?ssl=true&sslmode=require`.



[[howto.docker-compose.sharing-services]]
== Chia sẻ service giữa nhiều application

Nếu muốn chia sẻ service giữa nhiều application, hãy tạo file `compose.yaml` trong một application rồi dùng configuration property configprop:spring.docker.compose.file[] trong các application khác để tham chiếu đến file `compose.yaml`.
Bạn cũng nên set configprop:spring.docker.compose.lifecycle-management[] thành `start-only`, vì giá trị mặc định là `start-and-stop`; việc dừng một application sẽ dừng các service dùng chung của những application khác vẫn đang chạy.
Set thành `start-only` sẽ không dừng các service dùng chung khi application dừng, nhưng cần lưu ý rằng nếu dừng tất cả application thì các service vẫn tiếp tục chạy.
Có thể dừng các service thủ công bằng cách chạy command `docker compose stop` trong directory chứa file `compose.yaml`.
