[[howto.security]]
= Security

Phần này giải đáp các câu hỏi về security khi làm việc với Spring Boot, bao gồm cả các câu hỏi phát sinh khi sử dụng Spring Security với Spring Boot.

Để biết thêm về Spring Security, xem {url-spring-security-site}[trang dự án Spring Security].



[[howto.security.switch-off-spring-boot-configuration]]
== Tắt Spring Boot Security Configuration

Nếu bạn define một javadoc:org.springframework.context.annotation.Configuration[format=annotation] với một bean javadoc:org.springframework.security.web.SecurityFilterChain[] trong application, thao tác này sẽ tắt các webapp security setting mặc định trong Spring Boot.



[[howto.security.change-user-details-service-and-add-user-accounts]]
== Thay đổi UserDetailsService và thêm user account

Nếu bạn cung cấp một bean javadoc:org.springframework.context.annotation.Bean[format=annotation] có type là javadoc:org.springframework.security.authentication.AuthenticationManager[], javadoc:org.springframework.security.authentication.AuthenticationProvider[] hoặc javadoc:org.springframework.security.core.userdetails.UserDetailsService[], bean javadoc:org.springframework.context.annotation.Bean[format=annotation] mặc định cho javadoc:org.springframework.security.provisioning.InMemoryUserDetailsManager[] sẽ không được tạo.
Điều này có nghĩa là bạn có đầy đủ feature set của Spring Security, chẳng hạn {url-spring-security-docs}/servlet/authentication/index.html[các authentication option khác nhau].

Cách dễ nhất để thêm user account là cung cấp bean javadoc:org.springframework.security.core.userdetails.UserDetailsService[] của riêng bạn.



[[howto.security.enable-https]]
== Bật HTTPS khi chạy phía sau proxy server

Đảm bảo mọi main endpoint chỉ có thể truy cập qua HTTPS là một task quan trọng đối với mọi application.
Nếu dùng Tomcat làm servlet container, Spring Boot sẽ tự động thêm javadoc:org.apache.catalina.valves.RemoteIpValve[] của Tomcat khi detect một số environment settings, cho phép dựa vào javadoc:jakarta.servlet.http.HttpServletRequest[] để report request có secure hay không, ngay cả ở phía downstream của một proxy server xử lý SSL termination thực tế.
Hành vi mặc định được xác định bởi việc có hoặc không có một số request headers nhất định (`x-forwarded-for` và `x-forwarded-proto`); tên của chúng mang tính convention nên hoạt động với phần lớn front-end proxies.
Có thể bật valve bằng cách thêm một số entry vào `application.properties`, như ví dụ sau:

[configprops,yaml]
----
server:
  tomcat:
    remoteip:
      remote-ip-header: "x-forwarded-for"
      protocol-header: "x-forwarded-proto"
----

(Sự có mặt của một trong hai property trên sẽ bật valve.
Ngoài ra, có thể thêm javadoc:org.apache.catalina.valves.RemoteIpValve[] bằng cách customize javadoc:org.springframework.boot.tomcat.servlet.TomcatServletWebServerFactory[] thông qua một bean javadoc:org.springframework.boot.web.server.WebServerFactoryCustomizer[].)

Để configure Spring Security yêu cầu secure channel cho tất cả (hoặc một số) request, cân nhắc thêm bean javadoc:org.springframework.security.web.SecurityFilterChain[] của riêng bạn có thêm configuration javadoc:org.springframework.security.config.annotation.web.builders.HttpSecurity[] sau:

include-code::MySecurityConfig[]
