[[actuator.loggers]]
= Loggers

Spring Boot Actuator cho phép xem và cấu hình các log level của application tại runtime.
Có thể xem toàn bộ danh sách hoặc configuration của từng logger, bao gồm logging level được cấu hình rõ ràng và effective logging level do logging framework áp dụng cho logger đó.
Các level này có thể là:

* `TRACE`
* `DEBUG`
* `INFO`
* `WARN`
* `ERROR`
* `FATAL`
* `OFF`
* `null`

`null` cho biết không có explicit configuration.



[[actuator.loggers.configure]]
== Cấu hình Logger

Để configure một logger cụ thể, gửi một partial entity bằng `POST` tới URI của resource, như ví dụ sau:

[source,json]
----
{
	"configuredLevel": "DEBUG"
}
----

TIP: Để "`reset`" level cụ thể của logger (và thay vào đó dùng default configuration), có thể truyền giá trị `null` cho `configuredLevel`.



[[actuator.loggers.opentelemetry]]
== OpenTelemetry
Mặc định logging qua OpenTelemetry chưa được cấu hình.
Để configure logging qua OpenTelemetry, cần cung cấp địa chỉ của OpenTelemetry logs endpoint:

[configprops,yaml]
----
management:
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: "https://otlp.example.com:4318/v1/logs"
----

Các configuration property `management.opentelemetry.logging.export.*` có thể được dùng để configure javadoc:io.opentelemetry.sdk.logs.export.BatchLogRecordProcessor[].
Ví dụ, để thay đổi export interval thành 15 giây:

[configprops,yaml]
----
management:
  opentelemetry:
    logging:
      export:
        schedule-delay: "15s"
----

Các configuration property `management.opentelemetry.logging.limits.*` có thể được dùng để configure các limit của log record.
Ví dụ, để giới hạn số attribute trong mỗi log record ở 64 và độ dài tối đa của attribute value ở 256 ký tự:

[configprops,yaml]
----
management:
  opentelemetry:
    logging:
      limits:
        max-attributes: 64
        max-attribute-value-length: 256
----

Nếu cần toàn quyền kiểm soát, có thể register một custom bean javadoc:io.opentelemetry.sdk.logs.LogLimits[].

NOTE: OpenTelemetry Logback appender và Log4j appender không thuộc Spring Boot.
Để biết thêm chi tiết, xem https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/logback/logback-appender-1.0/library[OpenTelemetry Logback appender] hoặc https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/log4j/log4j-appender-2.17/library[OpenTelemetry Log4j2 appender] trong https://github.com/open-telemetry/opentelemetry-java-instrumentation[GitHub repository về OpenTelemetry Java instrumentation].

TIP: Cần configure appender trong `logback-spring.xml` hoặc `log4j2-spring.xml` để OpenTelemetry logging hoạt động.

`OpenTelemetryAppender` cho cả Logback và Log4j cần access tới một instance javadoc:io.opentelemetry.api.OpenTelemetry[] để hoạt động đúng cách.
Instance này phải được set programmatically trong lúc application startup, có thể thực hiện như sau:

include-code::OpenTelemetryAppenderInitializer[]
