[[packaging.container-images.buildpacks]]
= Cloud Native Buildpacks

Có thể build Docker image trực tiếp từ plugin Maven hoặc Gradle của bạn bằng https://buildpacks.io[Cloud Native Buildpacks].
Nếu từng sử dụng application platform như Cloud Foundry hoặc Heroku thì có lẽ bạn đã từng dùng buildpack.
Buildpack là thành phần của platform nhận application và biến nó thành dạng mà platform có thể thực sự chạy được.
Ví dụ, Java buildpack của Cloud Foundry sẽ nhận biết bạn đang push một file `.jar` và tự động thêm JRE phù hợp.

Với Cloud Native Buildpacks, bạn có thể tạo Docker-compatible image có thể chạy ở bất kỳ đâu.
Spring Boot cung cấp buildpack support trực tiếp cho cả Maven và Gradle.
Điều này nghĩa là bạn chỉ cần gõ một command duy nhất để nhanh chóng đưa một image hợp lý vào Docker daemon đang chạy trên local.

Xem tài liệu của từng plugin để biết cách sử dụng buildpack với xref:maven-plugin:build-image.adoc#build-image[Maven] và xref:gradle-plugin:packaging-oci-image.adoc[Gradle].

NOTE: https://github.com/paketo-buildpacks/spring-boot[Paketo Spring Boot buildpack] hỗ trợ file `layers.idx`, nên mọi xref:packaging/container-images/efficient-images.adoc#packaging.container-images.efficient-images.layering[layer customization] áp dụng cho buildpack này sẽ được phản ánh trong image do buildpacks tạo ra.

NOTE: Để đạt được reproducible builds và container image caching, buildpacks có thể thay đổi metadata của application resources (chẳng hạn như thông tin "last modified" của file).
Bạn nên đảm bảo application không phụ thuộc vào metadata đó tại runtime.
Spring Boot có thể sử dụng thông tin đó khi serve static resources, nhưng có thể disable việc này bằng configprop:spring.web.resources.cache.use-last-modified[].
