[[packaging.container-images.dockerfiles]]
= Dockerfiles

Dù có thể chuyển một Spring Boot uber jar thành Docker image chỉ với vài dòng trong `Dockerfile`, việc sử dụng xref:packaging/container-images/efficient-images.adoc#packaging.container-images.efficient-images.layering[tính năng layering] sẽ tạo ra một image được tối ưu.
Khi tạo một jar chứa layers index file, jar `spring-boot-jarmode-tools` sẽ được thêm làm dependency vào jar của bạn.
Với jar này trên classpath, bạn có thể launch application ở một mode đặc biệt, cho phép bootstrap code chạy một task hoàn toàn khác với application của bạn, chẳng hạn như một công cụ extract các layer.

Sau đây là cách launch jar với `tools` jar mode:

[source,shell]
----
$ java -Djarmode=tools -jar my-app.jar
----

Lệnh này sẽ cho ra output sau:

[subs="verbatim"]
----
Usage:
  java -Djarmode=tools -jar my-app.jar

Available commands:
  extract      Extract the contents from the jar
  list-layers  List layers from the jar that can be extracted
  sbom         Print the SBOM from the jar
  help         Help about any command
----

Có thể dùng command `extract` để dễ dàng tách application thành các layer để thêm vào `Dockerfile`.
Dưới đây là ví dụ về một `Dockerfile` sử dụng `jarmode`.

[source,dockerfile]
----
include::reference:partial$dockerfile[]
# Khởi động application jar - đây không phải uber jar được builder sử dụng
# Jar này chỉ chứa application code và các reference tới những jar file đã được extract
# Layout này giúp startup hiệu quả và thân thiện với AOT cache (và CDS)
ENTRYPOINT ["java", "-jar", "application.jar"]
----

Giả sử `Dockerfile` ở current directory, bạn có thể build Docker image bằng `docker build .`, hoặc chỉ định path tới application jar như trong ví dụ sau:

[source,shell]
----
$ docker build --build-arg JAR_FILE=path/to/myapp.jar .
----

Đây là một multi-stage `Dockerfile`.
Builder stage extract các directory cần dùng ở các bước sau.
Mỗi command `COPY` tương ứng với các layer được jarmode extract.

Tất nhiên, có thể viết một `Dockerfile` mà không dùng `jarmode`.
Có thể dùng một số kết hợp của `unzip` và `mv` để chuyển các thành phần tới layer phù hợp, nhưng `jarmode` đơn giản hóa việc đó.
Ngoài ra, layout do `jarmode` tạo ra ngay từ đầu đã thân thiện với AOT cache (và CDS).



[[packaging.container-images.dockerfiles.aot-cache]]
== AOT cache

Nếu đang dùng Java 25 trở lên và muốn enable thêm xref:reference:packaging/aot-cache.adoc#packaging.aot-cache.aot-cache[AOT cache], bạn có thể dùng `Dockerfile` này:

[source,dockerfile]
----
include::reference:partial$dockerfile[]

# Thực thi training run cho AOT cache
RUN java -XX:AOTCacheOutput=app.aot -Dspring.context.exit=onRefresh -jar application.jar

# Khởi động application jar với AOT cache được enable - đây không phải uber jar được builder sử dụng
# Jar này chỉ chứa application code và các reference tới những jar file đã được extract
# Layout này giúp startup hiệu quả và thân thiện với AOT cache
ENTRYPOINT ["java", "-XX:AOTCache=app.aot", "-jar", "application.jar"]
----

Dockerfile này hầu như giống `Dockerfile` ở trên.
Ở các bước cuối, Dockerfile này tạo file AOT cache bằng cách thực hiện một training run và truyền tham số AOT cache cho `java -jar`.


[[packaging.container-images.dockerfiles.cds]]
== CDS

NOTE: Nếu dùng Java 24 trở lên, hãy dùng AOT cache thay vì CDS.

Nếu muốn enable thêm xref:reference:packaging/aot-cache.adoc#packaging.aot-cache.cds[CDS], bạn có thể dùng `Dockerfile` này:

[source,dockerfile]
----
include::reference:partial$dockerfile[]

# Thực thi training run cho CDS
RUN java -XX:ArchiveClassesAtExit=application.jsa -Dspring.context.exit=onRefresh -jar application.jar

# Khởi động application jar với CDS được enable - đây không phải uber jar được builder sử dụng
# Jar này chỉ chứa application code và các reference tới những jar file đã được extract
# Layout này giúp startup hiệu quả và thân thiện với CDS
ENTRYPOINT ["java", "-XX:SharedArchiveFile=application.jsa", "-jar", "application.jar"]
----

Dockerfile này hầu như giống `Dockerfile` ở trên.
Ở các bước cuối, Dockerfile này tạo CDS archive bằng cách thực hiện một training run và truyền tham số CDS cho `java -jar`.

NOTE: Nếu dùng Java 25 trở lên, khuyến nghị dùng AOT cache thay vì CDS.
