[[howto.native-image.developing-your-first-application]]
= Phát triển Native Application đầu tiên với GraalVM

Có hai cách chính để build native image application cho Spring Boot:

* Dùng xref:reference:packaging/container-images/cloud-native-buildpacks.adoc[hỗ trợ Cloud Native Buildpacks] của Spring Boot với https://paketo.io/docs/reference/java-native-image-reference/[Paketo Java Native Image buildpack] để tạo lightweight container chứa native executable.
* Dùng GraalVM Native Build Tools để tạo native executable.

TIP: Cách dễ nhất để bắt đầu một project Spring Boot native mới là truy cập https://start.spring.io[start.spring.io], thêm dependency `GraalVM Native Support` và generate project.
File `HELP.md` đi kèm sẽ cung cấp các hướng dẫn getting started.

[[howto.native-image.developing-your-first-application.sample-application]]
== Ứng dụng mẫu

Cần có một example application để tạo native image.
Với mục đích này, web application "Hello World!" đơn giản được đề cập trong section xref:tutorial:first-application/index.adoc[] là đủ.

Tóm lại, main application code như sau:

include-code::MyApplication[]

Application này dùng Spring MVC và embedded Tomcat; cả hai đều đã được test và verify là hoạt động với GraalVM native image.

[[howto.native-image.developing-your-first-application.buildpacks]]
== Build Native Image bằng Buildpacks

Spring Boot hỗ trợ build Docker image chứa native executable bằng integration của Cloud Native Buildpacks (CNB) với cả Maven và Gradle, cùng với https://paketo.io/docs/reference/java-native-image-reference/[Paketo Java Native Image buildpack].
Điều này nghĩa là bạn chỉ cần nhập một command để nhanh chóng có được một image phù hợp trong Docker daemon đang chạy trên local machine.
Image tạo ra không chứa JVM; thay vào đó, native image được compile tĩnh.
Điều này tạo ra các image nhỏ hơn.

NOTE: CNB builder được dùng cho các image là `paketobuildpacks/builder-noble-java-tiny:latest`.
Builder này có footprint nhỏ và attack surface được giảm thiểu. Nó không include shell và chỉ chứa một tập system library rút gọn.
Nếu cần thêm tool trong image tạo ra, có thể dùng `paketobuildpacks/ubuntu-noble-run:latest` làm *run* image.

NOTE: Phải build application bằng ít nhất JDK 25, vì Buildpacks dùng cùng GraalVM native-image version với Java version được dùng để compile.

[[howto.native-image.developing-your-first-application.buildpacks.system-requirements]]
=== Yêu cầu hệ thống

Docker cần được install. Xem https://docs.docker.com/installation/#installation[Cài đặt Docker] để biết thêm chi tiết.
Nếu dùng Linux, hãy https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user[cấu hình để non-root user có thể sử dụng Docker].

NOTE: Có thể chạy `docker run hello-world` mà không dùng `sudo` để kiểm tra Docker daemon có thể truy cập như mong đợi.
Xem documentation của Spring Boot plugin cho xref:maven-plugin:build-image.adoc#build-image.docker-daemon[Maven] hoặc xref:gradle-plugin:packaging-oci-image.adoc#build-image.docker-daemon[Gradle] để biết thêm chi tiết.

TIP: Trên macOS, khuyến nghị tăng memory được cấp cho Docker lên ít nhất `8GB`, và có thể thêm CPU nếu cần.
Xem https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container/44533437#44533437[câu trả lời trên Stack Overflow] để biết thêm chi tiết.
Trên Microsoft Windows, hãy đảm bảo enable https://docs.docker.com/docker-for-windows/wsl/[Docker WSL 2 backend] để có performance tốt hơn.

[[howto.native-image.developing-your-first-application.buildpacks.maven]]
=== Dùng Maven

Để build native image container bằng Maven, cần đảm bảo file `pom.xml` sử dụng `spring-boot-starter-parent` và `org.graalvm.buildtools:native-maven-plugin`.
Section `<parent>` cần có dạng như sau:

[source,xml,subs="verbatim,attributes"]
----
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>{version-spring-boot}</version>
</parent>
----

Ngoài ra, trong section `<build> <plugins>` cần có:

[source,xml,subs="verbatim,attributes"]
----
<plugin>
	<groupId>org.graalvm.buildtools</groupId>
	<artifactId>native-maven-plugin</artifactId>
</plugin>
----

`spring-boot-starter-parent` khai báo profile `native`, profile này configure các execution cần chạy để tạo native image.
Có thể activate các profile bằng flag `-P` trên command line.

TIP: Nếu không muốn dùng `spring-boot-starter-parent`, cần configure các execution cho goal `process-aot` của Spring Boot plugin và goal `add-reachability-metadata` của Native Build Tools plugin.

Để build image, có thể chạy goal `spring-boot:build-image` với profile `native` active:

[source,shell]
----
$ mvn -Pnative spring-boot:build-image
----

[[howto.native-image.developing-your-first-application.buildpacks.gradle]]
=== Dùng Gradle

Spring Boot Gradle plugin tự động configure các AOT task khi GraalVM Native Image plugin được apply.
Cần kiểm tra Gradle build có block `plugins` include `org.graalvm.buildtools.native`.

Khi plugin `org.graalvm.buildtools.native` được apply, task `bootBuildImage` sẽ generate native image thay vì JVM image.
Có thể chạy task bằng lệnh sau:

[source,shell]
----
$ gradle bootBuildImage
----

[[howto.native-image.developing-your-first-application.buildpacks.running]]
=== Chạy ví dụ

Sau khi chạy build command phù hợp, Docker image sẽ có sẵn.
Có thể start application bằng `docker run`:

[source,shell]
----
$ docker run --rm -p 8080:8080 docker.io/library/myproject:0.0.1-SNAPSHOT
----

Bạn sẽ thấy output tương tự như sau:

[source,shell]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v{version-spring-boot})
....... . . .
....... . . . (log output here)
....... . . .
........ Started MyApplication in 0.08 seconds (process running for 0.095)
----

NOTE: Startup time khác nhau tùy machine, nhưng thời gian này sẽ nhanh hơn nhiều so với một Spring Boot application chạy trên JVM.

Nếu mở web browser tại `http://localhost:8080`, bạn sẽ thấy output sau:

[source]
----
Hello World!
----

Để thoát application một cách graceful, nhấn `ctrl-c`.

[[howto.native-image.developing-your-first-application.native-build-tools]]
== Build Native Image bằng Native Build Tools

Nếu muốn generate native executable trực tiếp mà không dùng Docker, có thể dùng GraalVM Native Build Tools.
Native Build Tools là các plugin do GraalVM cung cấp cho cả Maven và Gradle.
Có thể dùng chúng để thực hiện nhiều GraalVM task, bao gồm generate native image.

[[howto.native-image.developing-your-first-application.native-build-tools.prerequisites]]
=== Điều kiện tiên quyết

Để build native image bằng Native Build Tools, cần có một GraalVM distribution trên machine.
Có thể download thủ công từ {url-download-liberica-nik}[trang Liberica Native Image Kit] hoặc dùng download manager như SDKMAN!.

[[howto.native-image.developing-your-first-application.native-build-tools.prerequisites.linux-macos]]
==== Linux và macOS

Để install native image compiler trên macOS hoặc Linux, khuyến nghị dùng SDKMAN!.
Lấy SDKMAN! từ https://sdkman.io và install Liberica GraalVM distribution bằng các lệnh sau:

[source,shell,subs="verbatim,attributes"]
----
$ sdk install java 25.r25-nik
$ sdk use java 25.r25-nik
----

Xác minh version đúng đã được configure bằng cách kiểm tra output của `java -version`:

[source,shell,subs="verbatim,attributes"]
----
$ java -version
openjdk version "25" 2025-09-16 LTS
OpenJDK Runtime Environment Liberica-NIK-25.0.0-1 (build 25+37-LTS)
OpenJDK 64-Bit Server VM Liberica-NIK-25.0.0-1 (build 25+37-LTS, mixed mode, sharing)
----

[[howto.native-image.developing-your-first-application.native-build-tools.prerequisites.windows]]
==== Windows

Trên Windows, hãy làm theo https://medium.com/graalvm/using-graalvm-and-native-image-on-windows-10-9954dc071311[các hướng dẫn này] để install https://www.graalvm.org/downloads/[GraalVM] hoặc {url-download-liberica-nik}[Liberica Native Image Kit] version {version-graal}, Visual Studio Build Tools và Windows SDK.
Do https://docs.microsoft.com/en-US/troubleshoot/windows-client/shell-experience/command-line-string-limitation[giới hạn độ dài command line trên Windows], hãy đảm bảo dùng x64 Native Tools Command Prompt thay vì regular Windows command line để chạy Maven hoặc Gradle plugin.

[[howto.native-image.developing-your-first-application.native-build-tools.maven]]
=== Dùng Maven

Tương tự xref:native-image/developing-your-first-application.adoc#howto.native-image.developing-your-first-application.buildpacks.maven[hỗ trợ buildpacks], cần đảm bảo dùng `spring-boot-starter-parent` để inherit profile `native` và sử dụng plugin `org.graalvm.buildtools:native-maven-plugin`.

Khi profile `native` active, có thể invoke goal `native:compile` để trigger việc compile `native-image`:

[source,shell]
----
$ mvn -Pnative native:compile
----

Có thể tìm thấy native image executable trong directory `target`.

[[howto.native-image.developing-your-first-application.native-build-tools.gradle]]
=== Dùng Gradle

Khi Native Build Tools Gradle plugin được apply vào project, Spring Boot Gradle plugin sẽ tự động trigger Spring AOT engine.
Các task dependency được configure tự động, vì vậy chỉ cần chạy standard task `nativeCompile` để generate native image:

[source,shell]
----
$ gradle nativeCompile
----

Có thể tìm thấy native image executable trong directory `build/native/nativeCompile`.

[[howto.native-image.developing-your-first-application.native-build-tools.running]]
=== Chạy ví dụ

Đến đây, application của bạn sẽ hoạt động. Bạn có thể start application bằng cách chạy trực tiếp:

[tabs]
======
Maven::
+
[source,shell]
----
$ target/myproject
----
Gradle::
+
[source,shell]
----
$ build/native/nativeCompile/myproject
----
======

Bạn sẽ thấy output tương tự như sau:

[source,shell,subs="verbatim,attributes"]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::  (v{version-spring-boot})
....... . . .
....... . . . (log output here)
....... . . .
........ Started MyApplication in 0.08 seconds (process running for 0.095)
----

NOTE: Startup time khác nhau tùy machine, nhưng thời gian này sẽ nhanh hơn nhiều so với một Spring Boot application chạy trên JVM.

Nếu mở web browser tại `http://localhost:8080`, bạn sẽ thấy output sau:

[source]
----
Hello World!
----

Để thoát application một cách graceful, nhấn `ctrl-c`.
