[[testing]]
= Testing

Spring Boot cung cấp nhiều utility và annotation để hỗ trợ test application.

Test support được cung cấp bởi hai general-purpose module – `spring-boot-test` chứa core item và `spring-boot-test-autoconfigure` hỗ trợ auto-configuration cho test – cùng một số focused `-test` module hỗ trợ test cho feature cụ thể.

Phần lớn developer dùng starter `spring-boot-starter-test`, import cả hai general-purpose Spring Boot test module cùng JUnit Jupiter, AssertJ, Hamcrest, nhiều library hữu ích khác và focused `-test` module áp dụng cho application cụ thể.

[TIP]
====
Nếu có test dùng JUnit 4, vintage engine của JUnit 6 có thể dùng để chạy chúng.
Để dùng vintage engine, thêm dependency `junit-vintage-engine`:

[source,xml]
----
<dependency>
	<groupId>org.junit.vintage</groupId>
	<artifactId>junit-vintage-engine</artifactId>
	<scope>test</scope>
	<exclusions>
		<exclusion>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-core</artifactId>
		</exclusion>
	</exclusions>
</dependency>
----
====

`hamcrest-core` được exclude để dùng `org.hamcrest:hamcrest`, vốn là một phần của `spring-boot-starter-test`.
