[[testing]]
= Testing

Spring Boot cung cấp nhiều utility và annotation để hỗ trợ khi test application.

Test support được cung cấp bởi hai general-purpose module – `spring-boot-test` chứa các thành phần cốt lõi và `spring-boot-test-autoconfigure` hỗ trợ auto-configuration cho test – cùng một số module `-test` chuyên biệt cung cấp test support cho từng feature cụ thể.

Phần lớn developer sử dụng starter `spring-boot-starter-test`, import cả hai general-purpose Spring Boot test module cũng như JUnit Jupiter, AssertJ, Hamcrest và một số library hữu ích khác, cùng các module `-test` chuyên biệt áp dụng cho application cụ thể của họ.

[TIP]
====
Nếu bạn có các test sử dụng JUnit 4, vintage engine của JUnit 6 có thể được dùng để chạy chúng.
Để sử dụng vintage engine, thêm dependency `junit-vintage-engine`, như trong ví dụ sau:

[source,xml]
----
<dependency>
	<groupId>org.junit.vintage</groupId>
	<artifactId>junit-vintage-engine</artifactId>
	<scope>test</scope>
	<exclusions>
		<exclusion>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-core</artifactId>
		</exclusion>
	</exclusions>
</dependency>
----
====

`hamcrest-core` được exclude để dùng `org.hamcrest:hamcrest` thay cho nó; đây là một phần của `spring-boot-starter-test`.
