[[testing.testcontainers]]
= Testcontainers

Thư viện https://www.testcontainers.com/[Testcontainers] cung cấp cách quản lý các service chạy bên trong Docker container.
Thư viện này tích hợp với JUnit, cho phép bạn viết một test class có thể start một container trước khi bất kỳ test nào chạy.
Testcontainers đặc biệt hữu ích khi viết integration test giao tiếp với một backend service thật như MySQL, MongoDB, Cassandra và các service khác.

Trong các phần sau, chúng tôi sẽ mô tả một số cách bạn có thể dùng để tích hợp Testcontainers với test.


[[testing.testcontainers.spring-beans]]
== Sử dụng Spring bean

Các container do Testcontainers cung cấp có thể được Spring Boot quản lý như bean.

Để khai báo một container là bean, hãy thêm một method javadoc:org.springframework.context.annotation.Bean[format=annotation] vào test configuration:

include-code::MyTestConfiguration[]

Sau đó, bạn có thể inject và sử dụng container bằng cách import configuration class vào test class:

include-code::MyIntegrationTests[]

TIP: Cách quản lý container này thường được dùng kết hợp với xref:#testing.testcontainers.service-connections[các service connection annotation].



[[testing.testcontainers.junit-extension]]
== Sử dụng JUnit Extension

Testcontainers cung cấp một JUnit extension có thể dùng để quản lý container trong test.
Extension được kích hoạt bằng cách áp dụng annotation javadoc:org.testcontainers.junit.jupiter.Testcontainers[format=annotation] của Testcontainers cho test class.

Sau đó, bạn có thể dùng annotation javadoc:org.testcontainers.junit.jupiter.Container[format=annotation] trên các static container field.

Annotation javadoc:org.testcontainers.junit.jupiter.Testcontainers[format=annotation] có thể dùng với vanilla JUnit test hoặc kết hợp với javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation]:

include-code::MyIntegrationTests[]

Ví dụ trên sẽ start một Neo4j container trước khi bất kỳ test nào chạy.
Lifecycle của container instance do Testcontainers quản lý, như được mô tả trong {url-testcontainers-docs}/test_framework_integration/junit_5/#extension[tài liệu chính thức của họ].

Khi dùng JUnit extension, các container instance sẽ bị stop sau khi test class chạy xong (đối với static field) hoặc sau mỗi test method (đối với non-static field).
Điều này có thể gây vấn đề khi dùng với Spring Boot test, vì Spring TestContext Framework có thể cache javadoc:org.springframework.context.ApplicationContext[] lâu hơn thời điểm đó và reuse nó cho một test class hoặc method khác có cùng configuration.
Nếu application context được cache chứa các bean phụ thuộc vào một container đã bị stop, các test chạy sau hoặc các bean destruction callback có thể fail.
Vì lý do này, bạn nên ưu tiên xref:#testing.testcontainers.spring-beans[quản lý các container như Spring bean] hoặc xref:#testing.testcontainers.importing-configuration-interfaces[import các container declaration] khi application context cần tiếp tục usable trong thời gian được cache.

NOTE: Trong hầu hết trường hợp, bạn cũng cần cấu hình application để kết nối với service đang chạy trong container.



[[testing.testcontainers.importing-configuration-interfaces]]
== Import Container Configuration Interfaces

Một pattern phổ biến với Testcontainers là khai báo các container instance dưới dạng static field trong một interface.

Ví dụ, interface sau khai báo hai container: một container tên `mongo` có type javadoc:{url-testcontainers-mongodb-javadoc}/org.testcontainers.mongodb.MongoDBContainer[] và một container tên `neo4j` có type javadoc:{url-testcontainers-neo4j-javadoc}/org.testcontainers.neo4j.Neo4jContainer[]:

include-code::MyContainers[]

Khi khai báo container theo cách này, bạn có thể reuse configuration của chúng trong nhiều test bằng cách để các test class implement interface.

Cũng có thể dùng cùng interface configuration trong Spring Boot test.
Để làm vậy, hãy thêm javadoc:org.springframework.boot.testcontainers.context.ImportTestcontainers[format=annotation] vào test configuration class:

include-code::MyTestConfiguration[]



[[testing.testcontainers.lifecycle]]
== Lifecycle của Managed Containers

Nếu bạn đã dùng các annotation và extension do Testcontainers cung cấp, thì lifecycle của container instance được Testcontainers quản lý hoàn toàn.
Hãy tham khảo {url-testcontainers-docs}[tài liệu Testcontainers chính thức] để biết thêm thông tin.

Khi container được Spring quản lý như bean, lifecycle của nó do Spring quản lý:

* Container bean được tạo và start trước tất cả bean khác.

* Container bean được stop sau khi tất cả bean khác bị destroy.

Quy trình này đảm bảo mọi bean phụ thuộc vào functionality do container cung cấp đều có thể sử dụng functionality đó.
Quy trình này cũng đảm bảo các bean được cleanup trong khi container vẫn available.

TIP: Khi các application bean phụ thuộc vào functionality của container, hãy ưu tiên cấu hình container thành Spring bean để đảm bảo lifecycle behavior chính xác.

NOTE: Việc để Testcontainers quản lý container thay vì quản lý dưới dạng Spring bean không đảm bảo thứ tự shutdown giữa bean và container.
Container có thể bị shutdown trước khi các bean phụ thuộc vào functionality của container được cleanup.
Điều này có thể khiến client bean throw exception, ví dụ do mất connection.
Khi application context cần tiếp tục usable trong thời gian được cache, hãy ưu tiên quản lý các container như Spring bean hoặc import các container declaration bằng javadoc:org.springframework.boot.testcontainers.context.ImportTestcontainers[format=annotation].

Container bean được tạo và start một lần cho mỗi application context do Spring TestContext Framework quản lý.
Để biết chi tiết về cách TestContext Framework quản lý các application context và bean bên trong chúng, hãy tham khảo {url-spring-framework-docs}[tài liệu Spring Framework].

Container bean được stop như một phần của standard application context shutdown process của TestContext Framework.
Khi application context bị shutdown, các container cũng bị shutdown.
Điều này thường xảy ra sau khi tất cả test sử dụng application context được cache tương ứng đã chạy xong.
Tuy nhiên, nó cũng có thể xảy ra sớm hơn, tùy thuộc vào caching behavior được cấu hình trong TestContext Framework.

NOTE: Một test container instance có thể, và thường được, giữ lại trong quá trình chạy test từ nhiều test class.



[[testing.testcontainers.service-connections]]
== Service Connections

Service connection là một connection tới bất kỳ remote service nào.
Spring Boot auto-configuration có thể consume các detail của service connection và dùng chúng để thiết lập connection tới remote service.
Khi làm vậy, các connection detail được ưu tiên hơn mọi connection-related configuration properties.

Khi dùng Testcontainers, connection detail có thể được tự động tạo cho service đang chạy trong container bằng cách annotate container field trong test class.

include-code::MyIntegrationTests[]

Nhờ javadoc:org.springframework.boot.testcontainers.service.connection.ServiceConnection[format=annotation], configuration trên cho phép các Neo4j-related bean trong application giao tiếp với Neo4j đang chạy bên trong Docker container do Testcontainers quản lý.
Điều này được thực hiện bằng cách tự động định nghĩa một bean javadoc:org.springframework.boot.neo4j.autoconfigure.Neo4jConnectionDetails[], sau đó Neo4j auto-configuration sử dụng bean này để override mọi connection-related configuration properties.

NOTE: Bạn cần thêm module `spring-boot-testcontainers` làm test dependency để sử dụng các service connection với Testcontainers.

Các service connection annotation được xử lý bởi các class javadoc:org.springframework.boot.testcontainers.service.connection.ContainerConnectionDetailsFactory[] được đăng ký trong `spring.factories`.
Một javadoc:org.springframework.boot.testcontainers.service.connection.ContainerConnectionDetailsFactory[] có thể tạo một bean javadoc:org.springframework.boot.autoconfigure.service.connection.ConnectionDetails[] dựa trên một subclass javadoc:org.testcontainers.containers.Container[] cụ thể hoặc Docker image name.

Các service connection factory sau được cung cấp trong jar `spring-boot-testcontainers`:

|===
| Connection Details | Khớp theo

| javadoc:org.springframework.boot.activemq.autoconfigure.ActiveMQConnectionDetails[]
| Container tên "symptoma/activemq" hoặc javadoc:org.testcontainers.activemq.ActiveMQContainer[]

| javadoc:org.springframework.boot.amqp.autoconfigure.AmqpConnectionDetails[]
| Container có type javadoc:{url-testcontainers-rabbitmq-javadoc}/org.testcontainers.rabbitmq.RabbitMQContainer[] hoặc javadoc:org.testcontainers.activemq.ActiveMQContainer[] hoặc javadoc:org.testcontainers.activemq.ArtemisContainer[]

| javadoc:org.springframework.boot.artemis.autoconfigure.ArtemisConnectionDetails[]
| Container có type javadoc:org.testcontainers.activemq.ArtemisContainer[]

| javadoc:org.springframework.boot.cassandra.autoconfigure.CassandraConnectionDetails[]
| Container có type javadoc:org.testcontainers.cassandra.CassandraContainer[]

| javadoc:org.springframework.boot.couchbase.autoconfigure.CouchbaseConnectionDetails[]
| Container có type javadoc:org.testcontainers.couchbase.CouchbaseContainer[]

| javadoc:org.springframework.boot.elasticsearch.autoconfigure.ElasticsearchConnectionDetails[]
| Container có type javadoc:org.testcontainers.elasticsearch.ElasticsearchContainer[]

| javadoc:org.springframework.boot.flyway.autoconfigure.FlywayConnectionDetails[]
| Container có type javadoc:{url-testcontainers-jdbc-javadoc}/org.testcontainers.containers.JdbcDatabaseContainer[]

| javadoc:org.springframework.boot.jdbc.autoconfigure.JdbcConnectionDetails[]
| Container có type javadoc:{url-testcontainers-jdbc-javadoc}/org.testcontainers.containers.JdbcDatabaseContainer[]

| javadoc:org.springframework.boot.kafka.autoconfigure.KafkaConnectionDetails[]
| Container có type javadoc:org.testcontainers.kafka.KafkaContainer[], javadoc:org.testcontainers.kafka.ConfluentKafkaContainer[] hoặc javadoc:org.testcontainers.redpanda.RedpandaContainer[]

| javadoc:org.springframework.boot.ldap.autoconfigure.LdapConnectionDetails[]
| Container tên "osixia/openldap" hoặc có type javadoc:org.testcontainers.ldap.LLdapContainer[]

| javadoc:org.springframework.boot.liquibase.autoconfigure.LiquibaseConnectionDetails[]
| Container có type javadoc:{url-testcontainers-jdbc-javadoc}/org.testcontainers.containers.JdbcDatabaseContainer[]

| javadoc:org.springframework.boot.mongodb.autoconfigure.MongoConnectionDetails[]
| Container có type javadoc:{url-testcontainers-mongodb-javadoc}/org.testcontainers.mongodb.MongoDBContainer[] hoặc javadoc:{url-testcontainers-mongodb-javadoc}/org.testcontainers.mongodb.MongoDBAtlasLocalContainer[]

| javadoc:org.springframework.boot.neo4j.autoconfigure.Neo4jConnectionDetails[]
| Container có type javadoc:{url-testcontainers-neo4j-javadoc}/org.testcontainers.neo4j.Neo4jContainer[]

| javadoc:org.springframework.boot.opentelemetry.autoconfigure.logging.otlp.OtlpLoggingConnectionDetails[]
| Container tên "otel/opentelemetry-collector-contrib" hoặc có type javadoc:org.testcontainers.grafana.LgtmStackContainer[]

| javadoc:org.springframework.boot.micrometer.metrics.autoconfigure.export.otlp.OtlpMetricsConnectionDetails[]
| Container tên "otel/opentelemetry-collector-contrib" hoặc có type javadoc:org.testcontainers.grafana.LgtmStackContainer[]

| javadoc:org.springframework.boot.micrometer.tracing.opentelemetry.autoconfigure.otlp.OtlpTracingConnectionDetails[]
| Container tên "otel/opentelemetry-collector-contrib" hoặc có type javadoc:org.testcontainers.grafana.LgtmStackContainer[]

| javadoc:org.springframework.boot.pulsar.autoconfigure.PulsarConnectionDetails[]
| Container có type javadoc:{url-testcontainers-pulsar-javadoc}/org.testcontainers.pulsar.PulsarContainer[]

| javadoc:org.springframework.boot.r2dbc.autoconfigure.R2dbcConnectionDetails[]
| Container có type
javadoc:org.testcontainers.clickhouse.ClickHouseContainer[],
javadoc:{url-testcontainers-mariadb-javadoc}/org.testcontainers.mariadb.MariaDBContainer[], javadoc:{url-testcontainers-mssqlserver-javadoc}/org.testcontainers.mssqlserver.MSSQLServerContainer[], javadoc:{url-testcontainers-mysql-javadoc}/org.testcontainers.mysql.MySQLContainer[],
javadoc:org.testcontainers.oracle.OracleContainer[OracleContainer (free)], javadoc:{url-testcontainers-oracle-xe-javadoc}/org.testcontainers.containers.OracleContainer[OracleContainer (XE)] hoặc javadoc:{url-testcontainers-postgresql-javadoc}/org.testcontainers.postgresql.PostgreSQLContainer[]

| javadoc:org.springframework.boot.rabbitmq.autoconfigure.RabbitConnectionDetails[]
| Container có type javadoc:{url-testcontainers-rabbitmq-javadoc}/org.testcontainers.rabbitmq.RabbitMQContainer[]

| javadoc:org.springframework.boot.rabbitmq.autoconfigure.RabbitStreamConnectionDetails[]
| Container có type javadoc:{url-testcontainers-rabbitmq-javadoc}/org.testcontainers.rabbitmq.RabbitMQContainer[] khi `@ServiceConnection` `type` attribute bao gồm javadoc:org.springframework.boot.rabbitmq.autoconfigure.RabbitStreamConnectionDetails[]

| javadoc:org.springframework.boot.data.redis.autoconfigure.DataRedisConnectionDetails[]
| Container có type javadoc:com.redis.testcontainers.RedisContainer[] hoặc javadoc:com.redis.testcontainers.RedisStackContainer[], hoặc container tên "redis", "redis/redis-stack" hoặc "redis/redis-stack-server"

| javadoc:org.springframework.boot.zipkin.autoconfigure.ZipkinConnectionDetails[]
| Container tên "openzipkin/zipkin"
|===

[TIP]
====
Theo mặc định, ngoại trừ javadoc:org.springframework.boot.rabbitmq.autoconfigure.RabbitStreamConnectionDetails[], mọi applicable connection details bean đều được tạo cho một javadoc:org.testcontainers.containers.Container[].
Ví dụ, một javadoc:{url-testcontainers-postgresql-javadoc}/org.testcontainers.postgresql.PostgreSQLContainer[] sẽ tạo cả javadoc:org.springframework.boot.jdbc.autoconfigure.JdbcConnectionDetails[] và javadoc:org.springframework.boot.r2dbc.autoconfigure.R2dbcConnectionDetails[].

Nếu chỉ muốn tạo một subset của các applicable type, bạn có thể dùng attribute `type` của javadoc:org.springframework.boot.testcontainers.service.connection.ServiceConnection[format=annotation].

Để tạo bean javadoc:org.springframework.boot.rabbitmq.autoconfigure.RabbitStreamConnectionDetails[] từ một javadoc:{url-testcontainers-rabbitmq-javadoc}/org.testcontainers.rabbitmq.RabbitMQContainer[], bạn phải opt in bằng attribute `type` của javadoc:org.springframework.boot.testcontainers.service.connection.ServiceConnection[format=annotation].
Container cũng phải expose port 5552, hoặc port 5551 khi SSL được cấu hình, cho RabbitMQ Streams.
====

Theo mặc định, `Container.getDockerImageName().getRepository()` được dùng để lấy name dùng cho việc tìm các connection details.
Repository portion của Docker image name sẽ bỏ qua registry và version.
Điều này hoạt động miễn là Spring Boot có thể lấy được instance của javadoc:org.testcontainers.containers.Container[], như khi dùng một `static` field.

Nếu bạn dùng một method javadoc:org.springframework.context.annotation.Bean[format=annotation], Spring Boot sẽ không gọi bean method để lấy Docker image name, vì việc đó sẽ gây ra eager initialization issue.
Thay vào đó, return type của bean method được dùng để xác định connection detail nào cần sử dụng.
Điều này hoạt động miễn là bạn dùng các typed container như javadoc:{url-testcontainers-neo4j-javadoc}/org.testcontainers.neo4j.Neo4jContainer[] hoặc javadoc:{url-testcontainers-rabbitmq-javadoc}/org.testcontainers.rabbitmq.RabbitMQContainer[].
Điều này sẽ không hoạt động nếu bạn dùng javadoc:org.testcontainers.containers.GenericContainer[], chẳng hạn với Redis như trong ví dụ sau:

include-code::MyRedisConfiguration[]

Spring Boot không thể biết image container nào được dùng từ javadoc:org.testcontainers.containers.GenericContainer[], nên phải dùng attribute `name` của javadoc:org.springframework.boot.testcontainers.service.connection.ServiceConnection[format=annotation] để cung cấp thông tin đó.

Cũng có thể dùng attribute `name` của javadoc:org.springframework.boot.testcontainers.service.connection.ServiceConnection[format=annotation] để override connection detail được sử dụng, chẳng hạn khi dùng custom image.
Nếu bạn dùng Docker image `registry.mycompany.com/mirror/myredis`, hãy dùng `@ServiceConnection(name="redis")` để đảm bảo javadoc:org.springframework.boot.data.redis.autoconfigure.DataRedisConnectionDetails[] được tạo.



[[testing.testcontainers.service-connections.ssl]]
=== SSL với Service Connections

Bạn có thể dùng các annotation javadoc:org.springframework.boot.testcontainers.service.connection.Ssl[format=annotation], javadoc:org.springframework.boot.testcontainers.service.connection.JksKeyStore[format=annotation], javadoc:org.springframework.boot.testcontainers.service.connection.JksTrustStore[format=annotation], javadoc:org.springframework.boot.testcontainers.service.connection.PemKeyStore[format=annotation] và javadoc:org.springframework.boot.testcontainers.service.connection.PemTrustStore[format=annotation] trên một supported container để enable SSL support cho service connection đó.
Lưu ý rằng bạn vẫn phải tự enable SSL trên service đang chạy bên trong Testcontainer; các annotation chỉ cấu hình SSL ở phía client trong application.

include-code::MyRedisWithSslIntegrationTests[]

Code trên dùng annotation javadoc:org.springframework.boot.testcontainers.service.connection.PemKeyStore[format=annotation] để load client certificate và key vào keystore, đồng thời dùng annotation javadoc:org.springframework.boot.testcontainers.service.connection.PemTrustStore[format=annotation] để load CA certificate vào truststore.
Điều này sẽ authenticate client với server, còn CA certificate trong truststore đảm bảo server certificate hợp lệ và được trusted.

`SecureRedisContainer` trong ví dụ này là một custom subclass của `RedisContainer`, copy các certificate tới đúng location và invoke `redis-server` với các command-line parameter để enable SSL.

Các SSL annotation được hỗ trợ cho những service connection sau:

* Cassandra
* Couchbase
* Elasticsearch
* Kafka
* LDAP
* MongoDB
* OpenTelemetry (OTLP logging, metrics và tracing)
* RabbitMQ
* RabbitMQ Streams
* Redis

`ElasticsearchContainer` còn hỗ trợ automatic detection của server-side SSL.
Để sử dụng feature này, hãy annotate container bằng javadoc:org.springframework.boot.testcontainers.service.connection.Ssl[format=annotation], và Spring Boot sẽ xử lý client-side SSL configuration cho bạn:

include-code::MyElasticsearchWithSslIntegrationTests[]



[[testing.testcontainers.dynamic-properties]]
== Dynamic Properties

Một alternative dài dòng hơn một chút nhưng flexible hơn so với service connection là javadoc:org.springframework.test.context.DynamicPropertySource[format=annotation].
Một static method javadoc:org.springframework.test.context.DynamicPropertySource[format=annotation] cho phép thêm các dynamic property values vào Spring Environment.

include-code::MyIntegrationTests[]

Configuration trên cho phép các Neo4j-related bean trong application giao tiếp với Neo4j đang chạy bên trong Docker container do Testcontainers quản lý.
