[[web.security]]
= Spring Security

Nếu {url-spring-security-site}[Spring Security] có trên classpath, web application mặc định sẽ được bảo vệ.
Điều này bao gồm cả endpoint `/error` của Spring Boot.
Spring Boot dựa vào content-negotiation strategy của Spring Security để xác định nên dùng `httpBasic` hay `formLogin`.
Để thêm method-level security cho web application, bạn cũng có thể thêm javadoc:org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity[format=annotation] với các setting mong muốn.
Thông tin bổ sung có trong {url-spring-security-docs}/servlet/authorization/method-security.html[Spring Security Reference Guide].

javadoc:org.springframework.security.core.userdetails.UserDetailsService[] mặc định có một user duy nhất.
User name là `user`, password được tạo ngẫu nhiên và được in ở level WARN khi application khởi động, như ví dụ sau:

[source]
----
Using generated security password: 78fa095d-3f4c-48b1-ad50-e24c31d5cf35

This generated password is for development use only. Your security configuration must be updated before running your application in production.
----

NOTE: Nếu tinh chỉnh logging configuration, hãy đảm bảo category `org.springframework.boot.security.autoconfigure` được đặt để log message ở level `WARN`.
Nếu không, default password sẽ không được in.

Bạn có thể thay đổi username và password bằng cách cung cấp `spring.security.user.name` và `spring.security.user.password`.

Các feature cơ bản mặc định có trong web application gồm:

* Một bean javadoc:org.springframework.security.core.userdetails.UserDetailsService[] (hoặc javadoc:org.springframework.security.core.userdetails.ReactiveUserDetailsService[] với WebFlux application) sử dụng in-memory store và một user duy nhất với generated password (xem javadoc:org.springframework.boot.security.autoconfigure.SecurityProperties$User[] để biết các property của user).
* Form-based login hoặc HTTP Basic security (tùy thuộc header `Accept` trong request) cho toàn bộ application, bao gồm actuator endpoint nếu actuator có trên classpath.
* Một javadoc:org.springframework.security.authentication.DefaultAuthenticationEventPublisher[] để publish authentication event.

Bạn có thể cung cấp javadoc:org.springframework.security.authentication.AuthenticationEventPublisher[] khác bằng cách thêm bean tương ứng.



[[web.security.spring-mvc]]
== MVC Security

Default security configuration được triển khai trong javadoc:org.springframework.boot.security.autoconfigure.web.servlet.ServletWebSecurityAutoConfiguration[] và javadoc:org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration[].

Để tắt hoàn toàn default web application security configuration, bao gồm Actuator security, hoặc để kết hợp nhiều Spring Security component như OAuth2 Client và Resource Server, hãy thêm bean type javadoc:org.springframework.security.web.SecurityFilterChain[] (việc này không disable configuration javadoc:org.springframework.security.core.userdetails.UserDetailsService[]).
Để đồng thời tắt configuration javadoc:org.springframework.security.core.userdetails.UserDetailsService[], hãy thêm bean type javadoc:org.springframework.security.core.userdetails.UserDetailsService[], javadoc:org.springframework.security.authentication.AuthenticationProvider[], hoặc javadoc:org.springframework.security.authentication.AuthenticationManager[].

Auto-configuration của javadoc:org.springframework.security.core.userdetails.UserDetailsService[] cũng sẽ back off khi bất kỳ Spring Security module nào sau đây có trên classpath:

- `spring-security-oauth2-client`
- `spring-security-oauth2-resource-server`
- `spring-security-saml2-service-provider`

Để dùng javadoc:org.springframework.security.core.userdetails.UserDetailsService[] cùng một hoặc nhiều dependency trên, hãy định nghĩa bean javadoc:org.springframework.security.provisioning.InMemoryUserDetailsManager[] riêng.

Access rule có thể được override bằng cách thêm custom bean javadoc:org.springframework.security.web.SecurityFilterChain[].
Spring Boot cung cấp các convenience method có thể dùng để override access rule cho actuator endpoint và static resource.
javadoc:org.springframework.boot.security.autoconfigure.actuate.web.servlet.EndpointRequest[] có thể dùng để tạo javadoc:org.springframework.security.web.util.matcher.RequestMatcher[] dựa trên property configprop:management.endpoints.web.base-path[].
javadoc:org.springframework.boot.security.autoconfigure.web.servlet.PathRequest[] có thể dùng để tạo javadoc:org.springframework.security.web.util.matcher.RequestMatcher[] cho resource ở các location thường dùng.



[[web.security.spring-webflux]]
== WebFlux Security

Tương tự Spring MVC application, bạn có thể bảo vệ WebFlux application bằng cách thêm dependency `spring-boot-starter-security`.
Default security configuration được triển khai trong javadoc:org.springframework.boot.security.autoconfigure.web.reactive.ReactiveWebSecurityAutoConfiguration[] và javadoc:org.springframework.boot.security.autoconfigure.ReactiveUserDetailsServiceAutoConfiguration[].
Ngoài reactive web application, class thứ hai cũng được auto-configure khi dùng RSocket.
javadoc:org.springframework.boot.security.autoconfigure.web.reactive.ReactiveWebSecurityAutoConfiguration[] import `WebFluxSecurityConfiguration` cho web security.
javadoc:org.springframework.boot.security.autoconfigure.ReactiveUserDetailsServiceAutoConfiguration[] auto-configure authentication.

Để tắt hoàn toàn default web application security configuration, bao gồm Actuator security, hãy thêm bean type javadoc:org.springframework.security.web.server.WebFilterChainProxy[] (việc này không disable configuration javadoc:org.springframework.security.core.userdetails.ReactiveUserDetailsService[]).
Để đồng thời tắt configuration javadoc:org.springframework.security.core.userdetails.ReactiveUserDetailsService[], hãy thêm bean type javadoc:org.springframework.security.core.userdetails.ReactiveUserDetailsService[] hoặc javadoc:org.springframework.security.authentication.ReactiveAuthenticationManager[].

Auto-configuration của javadoc:org.springframework.security.core.userdetails.ReactiveUserDetailsService[] cũng sẽ back off khi bất kỳ Spring Security module nào sau đây có trên classpath:

- `spring-security-oauth2-client`
- `spring-security-oauth2-resource-server`
- `spring-security-saml2-service-provider`

Để dùng javadoc:org.springframework.security.core.userdetails.ReactiveUserDetailsService[] cùng một hoặc nhiều dependency trên, hãy định nghĩa bean javadoc:org.springframework.security.core.userdetails.MapReactiveUserDetailsService[] riêng.

Access rule và việc dùng nhiều Spring Security component như OAuth 2 Client và Resource Server có thể được cấu hình bằng cách thêm custom bean javadoc:org.springframework.security.web.server.SecurityWebFilterChain[].
Spring Boot cung cấp convenience method để override access rule cho actuator endpoint và static resource.
javadoc:org.springframework.boot.security.autoconfigure.actuate.web.reactive.EndpointRequest[] có thể dùng để tạo javadoc:org.springframework.security.web.server.util.matcher.ServerWebExchangeMatcher[] dựa trên property configprop:management.endpoints.web.base-path[].

javadoc:org.springframework.boot.security.autoconfigure.web.reactive.PathRequest[] có thể dùng để tạo javadoc:org.springframework.security.web.server.util.matcher.ServerWebExchangeMatcher[] cho resource ở các location thường dùng.

Ví dụ, bạn có thể customize security configuration bằng cách thêm nội dung như sau:

include-code::MyWebFluxSecurityConfiguration[]



[[web.security.oauth2]]
== [[web.security.oauth2.client]][[web.security.oauth2.client.common-providers]][[web.security.oauth2.server]][[web.security.oauth2.authorization-server]]OAuth2

https://oauth.net/2/[OAuth2] là authorization framework được sử dụng rộng rãi.
Để biết chi tiết cách cấu hình và sử dụng OAuth2 với web application, xem xref:security/oauth2.adoc#security.oauth2[phần "`OAuth2`"] trong mục "`Security`".



[[web.security.saml2]]
== [[web.security.saml2.build]][[web.security.saml2.build.maven]][[web.security.saml2.build.gradle]][[web.security.saml2.relying-party]]SAML 2.0

https://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0.html[SAML v2.0] là framework được áp dụng rộng rãi để trao đổi security information giữa các online business partner.
Để biết chi tiết cách cấu hình và sử dụng SAML 2.0 với web application, xem xref:security/saml2.adoc#security.saml2[phần "`SAML 2.0`"] trong mục "`Security`".
