[[web.spring-session]]
= Spring Session

Spring Boot cung cấp auto-configuration cho {url-spring-session-site}[Spring Session] với nhiều data store.
Với mỗi data store, Spring Boot cung cấp một starter riêng.

Khi xây dựng servlet web application, các store sau có thể được auto-configure:

* Redis (`spring-boot-starter-session-data-redis`)
* JDBC (`spring-boot-starter-session-jdbc`)

Servlet auto-configuration thay thế nhu cầu sử dụng `@Enable*HttpSession`.

Khi xây dựng reactive web application, Redis store có thể được auto-configure bằng dependency `spring-boot-starter-session-data-redis`.
Điều này thay thế nhu cầu sử dụng `@EnableRedisWebSession`.

Mỗi store có các setting bổ sung riêng.
Ví dụ, có thể customize tên table cho JDBC store như sau:

[configprops,yaml]
----
spring:
  session:
    jdbc:
      table-name: "SESSIONS"
----

Để đặt session timeout, bạn có thể dùng property configprop:spring.session.timeout[].
Nếu property đó không được đặt với servlet web application, auto-configuration sẽ fallback về value của configprop:server.servlet.session.timeout[].
Để cung cấp timeout programmatically, định nghĩa bean javadoc:org.springframework.boot.session.autoconfigure.SessionTimeout[].

Bạn có thể kiểm soát configuration của Spring Session bằng `@Enable*HttpSession` (servlet) hoặc `@EnableRedisWebSession` (reactive).
Điều này khiến auto-configuration back off.
Ngoài ra, có thể dependency trực tiếp vào Spring Session module tương ứng thay vì dùng một trong các Spring Boot starter cho Spring Session.
Với cả hai cách, Spring Session sau đó có thể được cấu hình bằng attribute của annotation thay vì các configuration property đã mô tả ở trên.
