[[web.spring-session]]
= Spring Session

Spring Boot cung cấp auto-configuration cho {url-spring-session-site}[Spring Session] trên nhiều data store.
Với mỗi data store, Spring Boot cung cấp một Spring Boot starter riêng.

Khi xây dựng servlet web application, các store sau có thể được auto-configure:

* Redis (`spring-boot-starter-session-data-redis`)
* JDBC (`spring-boot-starter-session-jdbc`)

Servlet auto-configuration loại bỏ nhu cầu sử dụng `@Enable*HttpSession`.

Khi xây dựng reactive web application, Redis store có thể được auto-configure bằng cách khai báo dependency vào `spring-boot-starter-session-data-redis`.
Điều này loại bỏ nhu cầu sử dụng `@EnableRedisWebSession`.

Mỗi store có các setting bổ sung riêng.
Ví dụ, có thể customize tên table cho JDBC store như trong ví dụ sau:

[configprops,yaml]
----
spring:
  session:
    jdbc:
      table-name: "SESSIONS"
----

Để đặt session timeout, có thể dùng property configprop:spring.session.timeout[].
Nếu property đó không được đặt trong servlet web application, auto-configuration sẽ fallback về value của configprop:server.servlet.session.timeout[].
Để cung cấp timeout programmatically, hãy định nghĩa một bean javadoc:org.springframework.boot.session.autoconfigure.SessionTimeout[].

Bạn có thể kiểm soát configuration của Spring Session bằng `@Enable*HttpSession` (servlet) hoặc `@EnableRedisWebSession` (reactive).
Điều này khiến auto-configuration back off.
Ngoài ra, thay vì dùng một trong các Spring Boot starter cho Spring Session, bạn có thể khai báo dependency trực tiếp vào Spring Session module tương ứng.
Với một trong hai cách này, Spring Session có thể được cấu hình bằng các attribute của annotation thay vì các configuration property đã mô tả ở trên.
