[[io.caching]]
= Caching

Spring Framework cung cấp support để thêm caching vào application một cách transparent.
Về core, abstraction áp dụng caching cho các method, nhờ đó giảm số lần thực thi dựa trên thông tin có trong cache.
Caching logic được áp dụng một cách transparent, không can thiệp vào caller.
Để biết thêm chi tiết, hãy xem {url-spring-framework-docs}/integration/cache.html[phần liên quan] trong reference documentation của Spring Framework.

Spring Boot auto-configure cache infrastructure miễn là caching support được enable bằng annotation javadoc:org.springframework.cache.annotation.EnableCaching[format=annotation].

TIP: Tránh thêm javadoc:org.springframework.cache.annotation.EnableCaching[format=annotation] vào application class chứa main method.
Việc này khiến caching trở thành feature bắt buộc, kể cả xref:io/caching.adoc#io.caching.testing[khi chạy test suite].

Để thêm caching vào một operation của service, hãy thêm annotation tương ứng vào method như trong ví dụ sau:

include-code::MyMathService[]

Ví dụ này minh họa việc dùng caching cho một operation có thể tốn nhiều chi phí.
Trước khi invoke `computePiDecimal`, abstraction tìm trong cache `piDecimals` một entry khớp với argument `precision`.
Nếu tìm thấy entry, content trong cache được trả ngay cho caller và method không được invoke.
Nếu không, method được invoke và cache được update trước khi trả về value.

CAUTION: Bạn cũng có thể dùng transparent các annotation JSR-107 (JCache) chuẩn, chẳng hạn javadoc:javax.cache.annotation.CacheResult[format=annotation].
Tuy nhiên, chúng tôi strongly advise bạn không trộn Spring Cache annotation với JCache annotation.

Nếu không thêm cache library cụ thể, Spring Boot auto-configure xref:io/caching.adoc#io.caching.provider.simple[simple provider] dùng concurrent map trong memory.
Khi cần cache, chẳng hạn `piDecimals`, provider này tạo cache cho bạn.
Simple provider không thực sự được khuyến nghị cho production, nhưng rất phù hợp để bắt đầu và đảm bảo bạn hiểu các feature.
Khi đã quyết định dùng cache provider nào, hãy đọc documentation của provider đó để biết cách configure các cache mà application sử dụng.
Gần như mọi provider đều yêu cầu bạn explicit configure từng cache được sử dụng trong application.
Một số provider cung cấp cách customize các cache mặc định được định nghĩa bởi configprop:spring.cache.cache-names[].

TIP: Cũng có thể transparent {url-spring-framework-docs}/integration/cache/annotations.html#cache-annotations-put[update] hoặc {url-spring-framework-docs}/integration/cache/annotations.html#cache-annotations-evict[evict] data trong cache.



[[io.caching.provider]]
== Các Cache Provider được hỗ trợ

Cache abstraction không cung cấp actual store mà dựa trên abstraction được materialize bởi các interface javadoc:org.springframework.cache.Cache[] và javadoc:org.springframework.cache.CacheManager[].

Nếu chưa định nghĩa bean có type javadoc:org.springframework.cache.CacheManager[] hoặc một javadoc:org.springframework.cache.interceptor.CacheResolver[] có tên `cacheResolver` (xem javadoc:org.springframework.cache.annotation.CachingConfigurer[]), Spring Boot sẽ thử detect các provider sau theo thứ tự:

. xref:io/caching.adoc#io.caching.provider.generic[]
. xref:io/caching.adoc#io.caching.provider.jcache[] (EhCache 3, Hazelcast, Infinispan và các provider khác)
. xref:io/caching.adoc#io.caching.provider.hazelcast[]
. xref:io/caching.adoc#io.caching.provider.infinispan[]
. xref:io/caching.adoc#io.caching.provider.couchbase[]
. xref:io/caching.adoc#io.caching.provider.redis[]
. xref:io/caching.adoc#io.caching.provider.caffeine[]
. xref:io/caching.adoc#io.caching.provider.cache2k[]
. xref:io/caching.adoc#io.caching.provider.simple[]

TIP: Nếu javadoc:org.springframework.cache.CacheManager[] được Spring Boot auto-configure, có thể _force_ một cache provider cụ thể bằng configprop:spring.cache.type[].

TIP: Dùng starter `spring-boot-starter-cache` để nhanh chóng thêm các caching dependency cơ bản.
Starter này kéo theo `spring-context-support`.
Nếu thêm dependency thủ công, bạn phải include `spring-context-support` để sử dụng JCache hoặc Caffeine support.

Nếu javadoc:org.springframework.cache.CacheManager[] được Spring Boot auto-configure, bạn có thể tune configuration trước khi nó được initialize hoàn toàn bằng cách expose một bean implement javadoc:org.springframework.boot.cache.autoconfigure.CacheManagerCustomizer[].
Ví dụ sau đặt một flag để các value `null` không được truyền xuống underlying map:

include-code::MyCacheManagerConfiguration[]

NOTE: Ví dụ trên giả định javadoc:org.springframework.cache.concurrent.ConcurrentMapCacheManager[] được auto-configure.
Nếu không phải trường hợp đó (bạn đã cung cấp config riêng hoặc một cache provider khác đã được auto-configure), customizer hoàn toàn không được invoke.
Bạn có thể có bao nhiêu customizer tùy ý và cũng có thể order chúng bằng javadoc:org.springframework.core.annotation.Order[format=annotation] hoặc javadoc:org.springframework.core.Ordered[].



[[io.caching.provider.generic]]
=== Generic

Generic caching được dùng nếu context định nghĩa _ít nhất_ một bean javadoc:org.springframework.cache.Cache[].
Một javadoc:org.springframework.cache.CacheManager[] wrap toàn bộ các bean có type đó sẽ được tạo.



[[io.caching.provider.jcache]]
=== JCache (JSR-107)

https://jcp.org/en/jsr/detail?id=107[JCache] được bootstrap thông qua sự hiện diện của javadoc:javax.cache.spi.CachingProvider[] trên classpath (tức là có một JSR-107 compliant caching library trên classpath), và javadoc:org.springframework.cache.jcache.JCacheCacheManager[] được cung cấp bởi starter `spring-boot-starter-cache`.
Có nhiều compliant library, và Spring Boot cung cấp dependency management cho Ehcache 3, Hazelcast và Infinispan.
Bạn cũng có thể thêm bất kỳ compliant library nào khác.

Có thể xảy ra trường hợp có nhiều provider, khi đó phải chỉ định rõ provider sẽ dùng.
Dù JSR-107 không enforce một cách chuẩn để định nghĩa location của configuration file, Spring Boot cố gắng accommodate việc setting cache với các implementation detail, như trong ví dụ sau:

[configprops,yaml]
----
    # Only necessary if more than one provider is present
	spring:
	  cache:
	    jcache:
	      provider: "com.example.MyCachingProvider"
	      config: "classpath:example.xml"
----

NOTE: Khi một cache library cung cấp cả native implementation và JSR-107 support, Spring Boot ưu tiên JSR-107 support để cùng các feature vẫn khả dụng nếu bạn chuyển sang một JSR-107 implementation khác.

TIP: Spring Boot có xref:io/hazelcast.adoc[general support cho Hazelcast].
Nếu có duy nhất một javadoc:com.hazelcast.core.HazelcastInstance[], instance đó cũng được tự động reuse cho javadoc:javax.cache.CacheManager[], trừ khi configprop:spring.cache.jcache.config[] được chỉ định.

Có hai cách customize underlying javadoc:javax.cache.CacheManager[]:

* Cache có thể được tạo khi startup bằng cách set configprop:spring.cache.cache-names[].
Nếu định nghĩa một custom javadoc:javax.cache.configuration.Configuration[] bean, bean đó được dùng để customize các cache.
* Các javadoc:org.springframework.boot.cache.autoconfigure.CacheManagerCustomizer[] bean được invoke với reference tới javadoc:javax.cache.CacheManager[] để full customization.

TIP: Nếu định nghĩa một javadoc:javax.cache.CacheManager[] bean chuẩn, bean đó được tự động wrap trong một implementation javadoc:org.springframework.cache.CacheManager[] mà abstraction yêu cầu.
Không áp dụng thêm customization nào cho bean đó.



[[io.caching.provider.hazelcast]]
=== Hazelcast

Spring Boot có xref:io/hazelcast.adoc[general support cho Hazelcast].
Nếu javadoc:com.hazelcast.core.HazelcastInstance[] được auto-configure và `com.hazelcast:hazelcast-spring` có trên classpath, instance đó được tự động wrap trong javadoc:org.springframework.cache.CacheManager[].

NOTE: Hazelcast có thể được dùng làm JCache-compliant cache hoặc Spring javadoc:org.springframework.cache.CacheManager[] compliant cache.
Khi đặt configprop:spring.cache.type[] thành `hazelcast`, Spring Boot sẽ dùng implementation dựa trên javadoc:org.springframework.cache.CacheManager[].
Nếu muốn dùng Hazelcast làm JCache-compliant cache, hãy đặt configprop:spring.cache.type[] thành `jcache`.
Nếu có nhiều JCache provider và muốn force Hazelcast, phải xref:io/caching.adoc#io.caching.provider.jcache[chỉ định rõ JCache provider].



[[io.caching.provider.infinispan]]
=== Infinispan

https://infinispan.org/[Infinispan] không có default configuration file location, nên phải chỉ định location đó một cách rõ ràng.
Nếu không, default bootstrap sẽ được dùng.

[configprops,yaml]
----
spring:
  cache:
    infinispan:
      config: "infinispan.xml"
----

Cache có thể được tạo khi startup bằng cách set configprop:spring.cache.cache-names[].
Nếu định nghĩa một custom javadoc:org.infinispan.configuration.cache.ConfigurationBuilder[] bean, bean đó được dùng để customize các cache.

Để biết thêm chi tiết, hãy xem https://infinispan.org/docs/stable/titles/spring/spring.html[tài liệu].


[[io.caching.provider.couchbase]]
=== Couchbase

Nếu Spring Data Couchbase có sẵn và Couchbase được xref:data/nosql.adoc#data.nosql.couchbase[cấu hình], javadoc:org.springframework.data.couchbase.cache.CouchbaseCacheManager[] được auto-configure.
Có thể tạo thêm cache khi startup bằng cách set configprop:spring.cache.cache-names[]; cache defaults có thể được configure bằng các property `spring.cache.couchbase.*`.
Ví dụ sau tạo các cache `cache1` và `cache2` với entry _expiration_ là 10 phút:

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
    couchbase:
      expiration: "10m"
----

Nếu cần kiểm soát nhiều hơn, hãy cân nhắc register một javadoc:org.springframework.boot.cache.autoconfigure.CouchbaseCacheManagerBuilderCustomizer[] bean.
Ví dụ sau minh họa một customizer configure expiration cụ thể cho các entry trong `cache1` và `cache2`:

include-code::MyCouchbaseCacheManagerConfiguration[]



[[io.caching.provider.redis]]
=== Redis

Nếu https://redis.io/[Redis] có sẵn và được cấu hình, javadoc:org.springframework.data.redis.cache.RedisCacheManager[] được auto-configure.
Có thể tạo thêm cache khi startup bằng cách set configprop:spring.cache.cache-names[]; cache defaults có thể được configure bằng các property `spring.cache.redis.*`.
Ví dụ sau tạo các cache `cache1` và `cache2` với _time to live_ là 10 phút:

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
    redis:
      time-to-live: "10m"
----

NOTE: Mặc định, một key prefix được thêm để nếu hai cache riêng biệt dùng cùng một key, Redis không có các key bị overlap và không thể trả về invalid value.
Chúng tôi strongly recommend giữ setting này nếu bạn tự tạo javadoc:org.springframework.data.redis.cache.RedisCacheManager[].

TIP: Có thể kiểm soát hoàn toàn default configuration bằng cách thêm một javadoc:org.springframework.data.redis.cache.RedisCacheConfiguration[] javadoc:org.springframework.context.annotation.Bean[format=annotation] của riêng bạn.
Điều này hữu ích nếu cần customize default serialization strategy.

Nếu cần kiểm soát configuration nhiều hơn, hãy cân nhắc register một javadoc:org.springframework.boot.cache.autoconfigure.RedisCacheManagerBuilderCustomizer[] bean.
Ví dụ sau minh họa một customizer cấu hình time to live riêng cho `cache1` và `cache2`:

include-code::MyRedisCacheManagerConfiguration[]



[[io.caching.provider.caffeine]]
=== Caffeine

https://github.com/ben-manes/caffeine[Caffeine] là bản rewrite cho Java 8 của Guava cache và thay thế support cho Guava.
Nếu Caffeine có mặt, javadoc:org.springframework.cache.caffeine.CaffeineCacheManager[] (được cung cấp bởi starter `spring-boot-starter-cache`) sẽ được auto-configure.
Cache có thể được tạo khi startup bằng cách set configprop:spring.cache.cache-names[] và có thể được customize theo thứ tự sau:

. Cache spec từ `spring.cache.caffeine.spec`
. Bean javadoc:com.github.benmanes.caffeine.cache.CaffeineSpec[]
. Bean javadoc:com.github.benmanes.caffeine.cache.Caffeine[]

Ví dụ sau tạo các cache `cache1` và `cache2` với maximum size là 500 và _time to live_ là 10 phút:

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
    caffeine:
      spec: "maximumSize=500,expireAfterAccess=600s"
----

Nếu định nghĩa một javadoc:com.github.benmanes.caffeine.cache.CacheLoader[] bean, bean đó sẽ được tự động associate với javadoc:org.springframework.cache.caffeine.CaffeineCacheManager[].
Vì javadoc:com.github.benmanes.caffeine.cache.CacheLoader[] sẽ được associate với _tất cả_ cache do cache manager quản lý, nó phải được định nghĩa là `CacheLoader<Object, Object>`.
Auto-configuration bỏ qua generic type khác.



[[io.caching.provider.cache2k]]
=== Cache2k

https://cache2k.org/[Cache2k] là một in-memory cache.
Nếu Cache2k Spring integration có mặt, `SpringCache2kCacheManager` sẽ được auto-configure.

Cache có thể được tạo khi startup bằng cách set configprop:spring.cache.cache-names[].
Cache defaults có thể được customize bằng một javadoc:org.springframework.boot.cache.autoconfigure.Cache2kBuilderCustomizer[] bean.
Ví dụ sau minh họa một customizer configure capacity của cache thành 200 entries, với expiration là 5 phút:

include-code::MyCache2kDefaultsConfiguration[]



[[io.caching.provider.simple]]
=== Simple

Nếu không tìm thấy provider nào khác, một simple implementation dùng javadoc:java.util.concurrent.ConcurrentHashMap[] làm cache store sẽ được configure.
Đây là default nếu application không có caching library.
Mặc định cache được tạo khi cần, nhưng có thể giới hạn danh sách cache bằng property `cache-names`.
Ví dụ chỉ cho phép `cache1` và `cache2`:

[configprops,yaml]
----
spring:
  cache:
    cache-names: "cache1,cache2"
----

Nếu application sử dụng một cache không có trong danh sách, application sẽ fail tại runtime khi cache đó được cần đến, nhưng không fail lúc startup.
Điều này tương tự cách các cache provider "thật" xử lý khi bạn sử dụng một cache chưa được khai báo.



[[io.caching.provider.none]]
=== None

Nếu cần dùng no-op cache thay cho cache manager được auto-configure trong một environment cụ thể, hãy đặt cache type thành `none`, như trong ví dụ sau:

[configprops,yaml]
----
spring:
  cache:
    type: "none"
----



[[io.caching.testing]]
== Testing

Khi chạy test suite, dùng no-op implementation thường hữu ích.
Phần này liệt kê một số strategy dành cho test.

Khi custom javadoc:org.springframework.cache.CacheManager[] được định nghĩa, tốt nhất đảm bảo caching configuration nằm trong class javadoc:org.springframework.context.annotation.Configuration[format=annotation] độc lập.
Điều này đảm bảo slice test không bắt buộc caching.
Với test enable full context như javadoc:org.springframework.boot.test.context.SpringBootTest[format=annotation], cần explicit configuration override regular configuration.

Nếu caching được auto-configure, có thêm option.
Test có thể annotate bằng javadoc:org.springframework.boot.cache.test.autoconfigure.AutoConfigureCache[format=annotation] để thay auto-configured javadoc:org.springframework.cache.CacheManager[] bằng no-op implementation.

include-code::MyIntegrationTests[]

Option khác là force no-op implementation cho auto-configured javadoc:org.springframework.cache.CacheManager[]:

[configprops,yaml]
----
spring:
  cache:
    type: "none"
----
