[[io.email]]
= Gửi email

Spring Framework cung cấp abstraction để gửi email bằng interface javadoc:org.springframework.mail.javamail.JavaMailSender[], còn Spring Boot cũng cung cấp auto-configuration cho abstraction này và một starter module.

TIP: Xem {url-spring-framework-docs}/integration/email.html[tài liệu tham khảo] để biết giải thích chi tiết về cách sử dụng javadoc:org.springframework.mail.javamail.JavaMailSender[].

Nếu `spring.mail.host` và các library liên quan (được định nghĩa bởi `spring-boot-starter-mail`) có sẵn, một javadoc:org.springframework.mail.javamail.JavaMailSender[] mặc định sẽ được tạo nếu chưa có.
Sender có thể được customize thêm bằng các config item trong namespace `spring.mail`.
Xem javadoc:org.springframework.boot.mail.autoconfigure.MailProperties[] để biết thêm chi tiết.

Một số giá trị timeout mặc định là vô hạn, và bạn có thể muốn thay đổi chúng để tránh một thread bị block bởi mail server không phản hồi, như trong ví dụ sau:

[configprops,yaml]
----
spring:
  mail:
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
----

Cũng có thể cấu hình javadoc:org.springframework.mail.javamail.JavaMailSender[] với một javadoc:jakarta.mail.Session[] có sẵn từ JNDI:

[configprops,yaml]
----
spring:
  mail:
    jndi-name: "mail/Session"
----

Khi đặt `jndi-name`, nó được ưu tiên hơn mọi setting khác liên quan đến Session.
