[[io.jta]]
= Distributed Transactions với JTA

Spring Boot hỗ trợ distributed JTA transaction trên nhiều XA resource bằng transaction manager được lấy từ JNDI.

Khi phát hiện JTA environment, Spring sử dụng javadoc:org.springframework.transaction.jta.JtaTransactionManager[] để quản lý transaction.
Các JMS, DataSource và JPA bean được auto-configure sẽ được nâng cấp để hỗ trợ XA transaction.
Bạn có thể sử dụng các Spring idiom tiêu chuẩn, chẳng hạn như javadoc:org.springframework.transaction.annotation.Transactional[format=annotation], để tham gia distributed transaction.
Nếu đang ở trong JTA environment nhưng vẫn muốn sử dụng local transaction, bạn có thể đặt configprop:spring.jta.enabled[] thành `false` để disable JTA auto-configuration.



[[io.jta.jakartaee]]
== Sử dụng Jakarta EE Managed Transaction Manager

Nếu đóng gói Spring Boot application thành file `war` hoặc `ear` và deploy lên Jakarta EE application server, bạn có thể sử dụng built-in transaction manager của server.
Spring Boot cố gắng auto-configure transaction manager bằng cách kiểm tra các JNDI location phổ biến (`java:comp/UserTransaction`, `java:comp/TransactionManager`, v.v.).
Khi sử dụng transaction service do application server cung cấp, thông thường bạn cũng nên đảm bảo rằng tất cả resource đều do server quản lý và được expose qua JNDI.
Spring Boot cố gắng auto-configure JMS bằng cách tìm javadoc:jakarta.jms.ConnectionFactory[] tại JNDI path (`java:/JmsXA` hoặc `java:/XAConnectionFactory`), và bạn có thể sử dụng xref:data/sql.adoc#data.sql.datasource.jndi[configprop:spring.datasource.jndi-name[]] để cấu hình javadoc:javax.sql.DataSource[].



[[io.jta.mixing-xa-and-non-xa-connections]]
== Kết hợp XA và Non-XA JMS connection

Khi sử dụng JTA, primary JMS javadoc:jakarta.jms.ConnectionFactory[] bean có khả năng nhận biết XA và tham gia distributed transaction.
Bạn có thể inject vào bean mà không cần sử dụng javadoc:org.springframework.beans.factory.annotation.Qualifier[format=annotation]:

include-code::primary/MyBean[]

Trong một số trường hợp, bạn có thể muốn xử lý một số JMS message bằng non-XA javadoc:jakarta.jms.ConnectionFactory[].
Ví dụ, JMS processing logic của bạn có thể mất nhiều thời gian hơn XA timeout.

Nếu muốn sử dụng non-XA javadoc:jakarta.jms.ConnectionFactory[], bạn có thể dùng bean `nonXaJmsConnectionFactory`:

include-code::nonxa/MyBean[]

Để nhất quán, bean `jmsConnectionFactory` cũng được cung cấp thông qua bean alias `xaJmsConnectionFactory`:

include-code::xa/MyBean[]



[[io.jta.supporting-embedded-transaction-manager]]
== Hỗ trợ Embedded Transaction Manager

Các interface javadoc:org.springframework.boot.jms.XAConnectionFactoryWrapper[] và javadoc:org.springframework.boot.jdbc.XADataSourceWrapper[] có thể được sử dụng để hỗ trợ embedded transaction manager.
Các interface này chịu trách nhiệm wrap bean javadoc:jakarta.jms.XAConnectionFactory[] và javadoc:javax.sql.XADataSource[], expose chúng dưới dạng bean javadoc:jakarta.jms.ConnectionFactory[] và javadoc:javax.sql.DataSource[] thông thường, rồi tự động enroll vào distributed transaction.
DataSource và JMS auto-configuration sử dụng các JTA variant, với điều kiện bạn đã đăng ký một bean javadoc:org.springframework.transaction.jta.JtaTransactionManager[] và các XA wrapper bean phù hợp trong javadoc:org.springframework.context.ApplicationContext[].
