[[io.spring-batch]]
= Spring Batch

Spring Boot cung cấp nhiều tiện ích khi làm việc với {url-spring-batch-site}[Spring Batch], bao gồm chạy Job khi startup.

Khi xây dựng batch application, các store sau có thể được auto-configure:

* In-memory
* JDBC
* MongoDB

Mỗi store có setting bổ sung riêng.
Ví dụ có thể customize table prefix cho JDBC store:

[configprops,yaml]
----
spring:
  batch:
    jdbc:
      table-prefix: "CUSTOM_"
----

Khi dùng MongoDB store, có thể bật initialization cho Spring Batch job repository schema (collection và index):

[configprops,yaml]
----
spring:
  batch:
    data:
      mongodb:
        schema:
          initialize: true
----

Để disable Spring Boot auto-configuration và kiểm soát hoàn toàn Spring Batch configuration, thêm javadoc:org.springframework.batch.core.configuration.annotation.EnableBatchProcessing[format=annotation] vào một class javadoc:org.springframework.context.annotation.Configuration[format=annotation] hoặc extend javadoc:org.springframework.batch.core.configuration.support.DefaultBatchConfiguration[].
Điều này làm auto-configuration back off, bao gồm initialization database schema của Spring Batch (JDBC hoặc MongoDB).
Sau đó Spring Batch có thể được cấu hình bằng attribute của annotation `@Enable*JobRepository` thay vì các configuration property đã mô tả.

Để tìm hiểu thêm về manual configuration, xem API documentation:

* javadoc:org.springframework.batch.core.configuration.support.DefaultBatchConfiguration[]
* javadoc:org.springframework.batch.core.configuration.annotation.EnableBatchProcessing[format=annotation]
* javadoc:org.springframework.batch.core.configuration.annotation.EnableJdbcJobRepository[format=annotation]
* javadoc:org.springframework.batch.core.configuration.annotation.EnableMongoJobRepository[format=annotation]

Xem {url-spring-batch-site}[Spring Batch project page] để biết thêm.



[[io.spring-batch.running-jobs-on-startup]]
== Chạy Spring Batch Job khi Startup

Khi Spring Boot auto-configure Spring Batch và chỉ tìm thấy một bean javadoc:org.springframework.batch.core.job.Job[] trong application context, job đó được execute khi startup (xem javadoc:org.springframework.boot.batch.autoconfigure.JobLauncherApplicationRunner[]).
Nếu có nhiều bean javadoc:org.springframework.batch.core.job.Job[], job cần execute phải được chỉ định bằng configprop:spring.batch.job.name[].

Có thể disable việc chạy bean javadoc:org.springframework.batch.core.job.Job[] tìm thấy trong application context:

[configprops,yaml]
----
spring:
  batch:
    job:
      enabled: false
----

Xem {code-spring-boot-batch-src}/autoconfigure/BatchAutoConfiguration.java[`BatchAutoConfiguration`], {code-spring-boot-batch-jdbc-src}/autoconfigure/BatchJdbcAutoConfiguration.java[`BatchJdbcAutoConfiguration`] và {code-spring-boot-batch-data-mongodb-src}/autoconfigure/BatchDataMongoAutoConfiguration.java[`BatchDataMongoAutoConfiguration`] để biết thêm.
