[[io.webservices]]
= Web Services

Spring Boot cung cấp auto-configuration cho Web Services, nên tất cả những gì bạn cần làm là định nghĩa các bean javadoc:org.springframework.ws.server.endpoint.annotation.Endpoint[format=annotation].

Các {url-spring-webservices-docs}[tính năng của Spring Web Services] có thể dễ dàng được sử dụng với module `spring-boot-starter-webservices`.

Các bean javadoc:org.springframework.ws.wsdl.wsdl11.SimpleWsdl11Definition[] và javadoc:org.springframework.xml.xsd.SimpleXsdSchema[] có thể được tự động tạo tương ứng cho các WSDL và XSD.
Để thực hiện việc này, hãy cấu hình location của chúng như trong ví dụ sau:


[configprops,yaml]
----
spring:
  webservices:
    wsdl-locations: "classpath:/wsdl"
----



[[io.webservices.template]]
== Gọi Web Services bằng WebServiceTemplate

Nếu application cần gọi các remote Web services, bạn có thể sử dụng class {url-spring-webservices-docs}#client-web-service-template[`WebServiceTemplate`].
Vì các instance javadoc:org.springframework.ws.client.core.WebServiceTemplate[] thường cần được tùy chỉnh trước khi sử dụng, Spring Boot không cung cấp một bean javadoc:org.springframework.ws.client.core.WebServiceTemplate[] duy nhất được auto-configure.
Tuy nhiên, Spring Boot auto-configure một javadoc:org.springframework.boot.webservices.client.WebServiceTemplateBuilder[], có thể được dùng để tạo các instance javadoc:org.springframework.ws.client.core.WebServiceTemplate[] khi cần.

Đoạn code sau đây cho thấy một ví dụ điển hình:

include-code::MyService[]

Theo mặc định, javadoc:org.springframework.boot.webservices.client.WebServiceTemplateBuilder[] phát hiện một javadoc:org.springframework.ws.transport.WebServiceMessageSender[] dựa trên HTTP phù hợp, sử dụng các HTTP client library hiện có trên classpath.
Bạn cũng có thể tùy chỉnh read timeout và connection timeout cho từng builder như sau:

include-code::MyWebServiceTemplateConfiguration[]

TIP: Bạn cũng có thể thay đổi xref:io/rest-client.adoc#io.rest-client.clienthttprequestfactory.configuration[cấu hình HTTP client ở cấp global] được sử dụng khi không áp dụng code tùy chỉnh cụ thể cho template.
