[[security.oauth2]]
= OAuth2

https://oauth.net/2/[OAuth2] là một authorization framework được sử dụng rộng rãi.



[[security.oauth2.client]]
== Client

Nếu `spring-security-oauth2-client` có trên classpath, bạn có thể tận dụng một số auto-configuration để setup OAuth2/Open ID Connect client.
Configuration này sử dụng các property trong javadoc:org.springframework.boot.security.oauth2.client.autoconfigure.OAuth2ClientProperties[].
Các property này áp dụng cho cả servlet và reactive web application.

Mỗi registration phải chỉ định một OAuth 2 provider.
Khi được đặt, value của property `spring.security.oauth2.client.registration.<registration-id>.provider` được dùng để chỉ định provider của registration.
Nếu không đặt property `provider`, ID của registration được dùng thay thế.
Cả hai cách đều được minh họa trong ví dụ sau:

[configprops,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: "abcd"
            client-secret: "password"
            provider: "example"
          example:
            client-id: "abcd"
            client-secret: "password"
----

Cả hai registration `my-client` và `example` đều sử dụng provider có ID `example`.
Registration đầu tiên sử dụng provider này do value của property `spring.security.oauth2.client.registration.my-client.provider`.
Registration thứ hai sử dụng provider này do ID của nó là `example` và không có property `provider` nào được cấu hình cho registration.

Provider được chỉ định có thể là một tham chiếu đến provider được cấu hình bằng các property `spring.security.oauth2.client.provider.<provider-id>.*` hoặc một trong các xref:security/oauth2.adoc#security.oauth2.client.common-providers[common provider đã biết].

Bạn có thể register nhiều OAuth2 client và provider dưới prefix `spring.security.oauth2.client`, như trong ví dụ sau:

[configprops,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          my-login-client:
            client-id: "abcd"
            client-secret: "password"
            client-name: "Client for OpenID Connect"
            provider: "my-oauth-provider"
            scope: "openid,profile,email,phone,address"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"

          my-client-1:
            client-id: "abcd"
            client-secret: "password"
            client-name: "Client for user scope"
            provider: "my-oauth-provider"
            scope: "user"
            redirect-uri: "{baseUrl}/authorized/user"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"

          my-client-2:
            client-id: "abcd"
            client-secret: "password"
            client-name: "Client for email scope"
            provider: "my-oauth-provider"
            scope: "email"
            redirect-uri: "{baseUrl}/authorized/email"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"

        provider:
          my-oauth-provider:
            authorization-uri: "https://my-auth-server.com/oauth2/authorize"
            token-uri: "https://my-auth-server.com/oauth2/token"
            user-info-uri: "https://my-auth-server.com/userinfo"
            user-info-authentication-method: "header"
            jwk-set-uri: "https://my-auth-server.com/oauth2/jwks"
            user-name-attribute: "name"
----

Trong ví dụ này có ba registration.
Theo thứ tự khai báo, ID của chúng là `my-login-client`, `my-client-1` và `my-client-2`.
Ngoài ra còn có một provider duy nhất với ID `my-oauth-provider`.

Với các OpenID Connect provider hỗ trợ https://openid.net/specs/openid-connect-discovery-1_0.html[OpenID Connect discovery], configuration có thể được đơn giản hóa hơn nữa.
Provider cần được cấu hình với một `issuer-uri`, là URI mà provider công bố là Issuer Identifier của mình.
Ví dụ, nếu `issuer-uri` được cung cấp là `+https://example.com+`, một "`OpenID Provider Configuration Request`" sẽ được gửi đến `+https://example.com/.well-known/openid-configuration+`.
Kết quả được mong đợi là một "`OpenID Provider Configuration Response`".
Ví dụ sau cho thấy cách cấu hình một OpenID Connect Provider bằng `issuer-uri`:

[configprops,yaml]
----
spring:
  security:
    oauth2:
      client:
        provider:
          oidc-provider:
            issuer-uri: "https://dev-123456.oktapreview.com/oauth2/default/"
----

Theo mặc định, javadoc:org.springframework.security.oauth2.client.web.OAuth2LoginAuthenticationFilter[] của Spring Security chỉ xử lý các URL khớp với `/login/oauth2/code/*`.
Nếu muốn tùy chỉnh `redirect-uri` để sử dụng một pattern khác, bạn cần cung cấp configuration để xử lý pattern tùy chỉnh đó.
Ví dụ, với servlet application, bạn có thể thêm javadoc:org.springframework.security.web.SecurityFilterChain[] của riêng mình, tương tự như sau:

include-code::MyOAuthClientConfiguration[]

TIP: Spring Boot auto-configure một javadoc:org.springframework.security.oauth2.client.InMemoryOAuth2AuthorizedClientService[] được Spring Security sử dụng để quản lý các client registration.
javadoc:org.springframework.security.oauth2.client.InMemoryOAuth2AuthorizedClientService[] có capability hạn chế và chúng tôi khuyến nghị chỉ sử dụng nó trong development environment.
Với production environment, hãy cân nhắc sử dụng javadoc:org.springframework.security.oauth2.client.JdbcOAuth2AuthorizedClientService[] hoặc tạo implementation riêng của bạn cho javadoc:org.springframework.security.oauth2.client.OAuth2AuthorizedClientService[].



[[security.oauth2.client.common-providers]]
=== OAuth2 Client Registration cho Common Provider

Với các OAuth2 và OpenID provider phổ biến (Google, Github, Facebook, X và Okta), chúng tôi cung cấp một tập hợp default cho provider.
ID của các common provider này lần lượt là `google`, `github`, `facebook`, `x` và `okta`.

Nếu không cần tùy chỉnh các provider này, hãy đặt property `provider` của registration thành ID của một trong các common provider.
Ngoài ra, bạn có thể xref:security/oauth2.adoc#security.oauth2.client[sử dụng registration ID khớp với ID của provider].
Hai configuration trong ví dụ sau sử dụng common `google` provider:

[configprops,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: "abcd"
            client-secret: "password"
            provider: "google"
          google:
            client-id: "abcd"
            client-secret: "password"
----



[[security.oauth2.server]]
== Resource Server

Nếu `spring-security-oauth2-resource-server` có trên classpath, Spring Boot có thể setup một OAuth2 Resource Server.
Để configuration JWT, cần chỉ định JWK Set URI hoặc OIDC Issuer URI, như trong các ví dụ sau:

[configprops,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://example.com/oauth2/default/v1/keys"
----

[configprops,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://dev-123456.oktapreview.com/oauth2/default/"
----

NOTE: Nếu authorization server không hỗ trợ JWK Set URI, bạn có thể cấu hình resource server bằng Public Key được sử dụng để verify chữ ký của JWT.
Bạn có thể thực hiện việc này bằng property configprop:spring.security.oauth2.resourceserver.jwt.public-key-location[], trong đó value phải trỏ đến một file chứa public key ở định dạng x509 được mã hóa PEM.

Property configprop:spring.security.oauth2.resourceserver.jwt.audiences[] có thể được sử dụng để chỉ định các value dự kiến của claim `aud` trong JWT.
Ví dụ, để yêu cầu JWT chứa claim `aud` với value `my-audience`:

[configprops,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences:
            - "my-audience"
----

Các property này áp dụng cho cả servlet và reactive application.
Ngoài ra, bạn có thể định nghĩa bean javadoc:org.springframework.security.oauth2.jwt.JwtDecoder[] của riêng mình cho servlet application hoặc javadoc:org.springframework.security.oauth2.jwt.ReactiveJwtDecoder[] cho reactive application.

Trong trường hợp sử dụng opaque token thay vì JWT, bạn có thể cấu hình các property sau để validate token thông qua introspection:

[configprops,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: "https://example.com/check-token"
          client-id: "my-client-id"
          client-secret: "my-client-secret"
----

Một lần nữa, các property này áp dụng cho cả servlet và reactive application.

Kết quả là một introspector được auto-configure. Đó là javadoc:org.springframework.security.oauth2.server.resource.introspection.SpringOpaqueTokenIntrospector[] hoặc, trong reactive application, javadoc:org.springframework.security.oauth2.server.resource.introspection.SpringReactiveOpaqueTokenIntrospector[].
Các introspector được auto-configure này có thể được tùy chỉnh tương ứng bằng các bean javadoc:org.springframework.boot.security.oauth2.server.resource.autoconfigure.SpringOpaqueTokenIntrospectorBuilderCustomizer[] và javadoc:org.springframework.boot.security.oauth2.server.resource.autoconfigure.reactive.SpringReactiveOpaqueTokenIntrospectorBuilderCustomizer[].

Để kiểm soát hoàn toàn introspection, hãy định nghĩa bean javadoc:org.springframework.security.oauth2.server.resource.introspection.OpaqueTokenIntrospector[] hoặc javadoc:org.springframework.security.oauth2.server.resource.introspection.ReactiveOpaqueTokenIntrospector[] của riêng bạn.



[[security.oauth2.authorization-server]]
== Authorization Server

Nếu `spring-security-oauth2-authorization-server` có trên classpath, bạn có thể tận dụng một số auto-configuration để setup một Servlet-based OAuth2 Authorization Server.

Bạn có thể register nhiều OAuth2 client dưới prefix `spring.security.oauth2.authorizationserver.client`, như trong ví dụ sau:

[configprops,yaml]
----
spring:
  security:
    oauth2:
      authorizationserver:
        client:
          my-client-1:
            registration:
              client-id: "abcd"
              client-secret: "{noop}secret1"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "https://my-client-1.com/login/oauth2/code/abcd"
                - "https://my-client-1.com/authorized"
              scopes:
                - "openid"
                - "profile"
                - "email"
                - "phone"
                - "address"
            require-authorization-consent: true
            token:
              authorization-code-time-to-live: 5m
              access-token-time-to-live: 10m
              access-token-format: "reference"
              reuse-refresh-tokens: false
              refresh-token-time-to-live: 30m
          my-client-2:
            registration:
              client-id: "efgh"
              client-secret: "{noop}secret2"
              client-authentication-methods:
                - "client_secret_jwt"
              authorization-grant-types:
                - "client_credentials"
              scopes:
                - "user.read"
                - "user.write"
            jwk-set-uri: "https://my-client-2.com/jwks"
	        token-endpoint-authentication-signing-algorithm: "RS256"
----

NOTE: Property `client-secret` phải ở format có thể được match bởi javadoc:org.springframework.security.crypto.password.PasswordEncoder[] đã cấu hình.
Instance mặc định của javadoc:org.springframework.security.crypto.password.PasswordEncoder[] được tạo thông qua `PasswordEncoderFactories.createDelegatingPasswordEncoder()`.

Auto-configuration mà Spring Boot cung cấp cho Spring Authorization Server được thiết kế để giúp bắt đầu nhanh chóng.
Hầu hết application sẽ cần customization và sẽ muốn định nghĩa một số bean để override auto-configuration.

Các component sau có thể được định nghĩa thành bean để override auto-configuration dành riêng cho Spring Authorization Server:

* javadoc:org.springframework.security.oauth2.server.authorization.client.RegisteredClientRepository[]
* javadoc:org.springframework.security.oauth2.server.authorization.settings.AuthorizationServerSettings[]
* javadoc:org.springframework.security.web.SecurityFilterChain[]
* `com.nimbusds.jose.jwk.source.JWKSource<com.nimbusds.jose.proc.SecurityContext>`
* javadoc:org.springframework.security.oauth2.jwt.JwtDecoder[]

TIP: Spring Boot auto-configure một javadoc:org.springframework.security.oauth2.server.authorization.client.InMemoryRegisteredClientRepository[] được Spring Authorization Server sử dụng để quản lý các registered client.
javadoc:org.springframework.security.oauth2.server.authorization.client.InMemoryRegisteredClientRepository[] có capability hạn chế và chúng tôi khuyến nghị chỉ sử dụng nó trong development environment.
Với production environment, hãy cân nhắc sử dụng javadoc:org.springframework.security.oauth2.server.authorization.client.JdbcRegisteredClientRepository[] hoặc tạo implementation riêng của bạn cho javadoc:org.springframework.security.oauth2.server.authorization.client.RegisteredClientRepository[].

Bạn có thể tìm thêm thông tin trong chapter {url-spring-security-docs}/servlet/oauth2/authorization-server/getting-started.html[Getting Started] của Spring Security Reference Documentation.
