[[security.saml2]]
= SAML 2.0

https://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0.html[SAML v2.0] là một framework được áp dụng rộng rãi để trao đổi security information giữa các online business partner.



[[security.saml2.build]]
== Cấu hình Build
SAML 2.0 support được xây dựng trên thư viện OpenSAML, thư viện này https://shibboleth.atlassian.net/wiki/spaces/DEV/pages/1123844333/Use+of+Maven+Central#Publishing-to-Maven-Central[yêu cầu cấu hình repository bổ sung].



[[security.saml2.build.maven]]
=== Sử dụng Maven
Với Maven, cần thêm một element `repository` vào POM như sau:

[source,xml,subs="verbatim,attributes"]
----
<repositories>
	<repository>
		<id>shibboleth-releases</id>
		<name>Shibboleth Releases Repository</name>
		<url>https://build.shibboleth.net/maven/releases</url>
		<snapshots>
			<enabled>false</enabled>
		</snapshots>
	</repository>
</repositories>
----


[[security.saml2.build.gradle]]
=== Sử dụng Gradle
Với Gradle, nên thêm một element repository vào build script:

[source,gradle,subs="verbatim,attributes"]
----
repositories {
    maven { url "https://build.shibboleth.net/maven/releases" }
}
----



[[security.saml2.relying-party]]
== Relying Party

Nếu `spring-security-saml2-service-provider` có trên classpath, bạn có thể tận dụng một số auto-configuration để thiết lập một SAML 2.0 Relying Party.
Configuration này sử dụng các property trong javadoc:org.springframework.boot.security.saml2.autoconfigure.Saml2RelyingPartyProperties[].

Một relying party registration biểu diễn một paired configuration giữa Identity Provider (IDP) và Service Provider (SP).
Bạn có thể register nhiều relying party dưới prefix `spring.security.saml2.relyingparty`, như trong ví dụ sau:

[configprops,yaml]
----
spring:
  security:
    saml2:
      relyingparty:
        registration:
          my-relying-party1:
            signing:
              credentials:
              - private-key-location: "path-to-private-key"
                certificate-location: "path-to-certificate"
            decryption:
              credentials:
              - private-key-location: "path-to-private-key"
                certificate-location: "path-to-certificate"
            singlelogout:
               url: "https://myapp/logout/saml2/slo"
               response-url: "https://remoteidp2.slo.url"
               binding: "POST"
            assertingparty:
              verification:
                credentials:
                - certificate-location: "path-to-verification-cert"
              entity-id: "remote-idp-entity-id1"
              sso-url: "https://remoteidp1.sso.url"

          my-relying-party2:
            signing:
              credentials:
              - private-key-location: "path-to-private-key"
                certificate-location: "path-to-certificate"
            decryption:
              credentials:
              - private-key-location: "path-to-private-key"
                certificate-location: "path-to-certificate"
            assertingparty:
              verification:
                credentials:
                - certificate-location: "path-to-other-verification-cert"
              entity-id: "remote-idp-entity-id2"
              sso-url: "https://remoteidp2.sso.url"
              singlelogout:
                url: "https://remoteidp2.slo.url"
                response-url: "https://myapp/logout/saml2/slo"
                binding: "POST"
----

Với SAML2 logout, theo mặc định, javadoc:org.springframework.security.saml2.provider.service.web.authentication.logout.Saml2LogoutRequestFilter[] và javadoc:org.springframework.security.saml2.provider.service.web.authentication.logout.Saml2LogoutResponseFilter[] của Spring Security chỉ process các URL khớp với `/logout/saml2/slo`.
Nếu muốn customize `url` mà AP-initiated logout request được gửi đến hoặc `response-url` mà AP gửi logout response đến để sử dụng một pattern khác, bạn cần cung cấp configuration để process custom pattern đó.
Ví dụ, với các servlet application, bạn có thể thêm một javadoc:org.springframework.security.web.SecurityFilterChain[] riêng tương tự như sau:

include-code::MySamlRelyingPartyConfiguration[]
