[[appendix.executable-jar.launching]]
= Khởi chạy executable jar

Class javadoc:org.springframework.boot.loader.launch.Launcher[] là một bootstrap class đặc biệt, được dùng làm main entry point của executable jar.
Đây chính là `Main-Class` thực tế trong JAR của bạn, được dùng để thiết lập javadoc:java.lang.ClassLoader[] phù hợp rồi cuối cùng gọi method `main()` của bạn.

Có ba launcher subclass (javadoc:org.springframework.boot.loader.launch.JarLauncher[], javadoc:org.springframework.boot.loader.launch.WarLauncher[] và javadoc:org.springframework.boot.loader.launch.PropertiesLauncher[]).
Mục đích của chúng là load resource (file `.class` và các file khác) từ nested JAR hoặc WAR trong các thư mục (thay vì các file được chỉ định tường minh trên classpath).
Với javadoc:org.springframework.boot.loader.launch.JarLauncher[] và javadoc:org.springframework.boot.loader.launch.WarLauncher[], các nested path là cố định.
javadoc:org.springframework.boot.loader.launch.JarLauncher[] tìm trong `BOOT-INF/lib/`, còn javadoc:org.springframework.boot.loader.launch.WarLauncher[] tìm trong `WEB-INF/lib/` và `WEB-INF/lib-provided/`.
Bạn có thể thêm các JAR khác vào những location đó nếu cần.

javadoc:org.springframework.boot.loader.launch.PropertiesLauncher[] mặc định tìm trong `BOOT-INF/lib/` của application archive.
Bạn có thể thêm các location khác bằng cách set environment variable có tên `LOADER_PATH` hoặc set `loader.path` trong `loader.properties` (đây là danh sách các thư mục, archive hoặc thư mục bên trong archive, được phân tách bằng dấu phẩy).



[[appendix.executable-jar.launching.manifest]]
== Manifest của Launcher

Bạn cần chỉ định javadoc:org.springframework.boot.loader.launch.Launcher[] phù hợp làm attribute `Main-Class` của `META-INF/MANIFEST.MF`.
Class bạn thực sự muốn khởi chạy (tức class chứa method `main`) nên được chỉ định trong attribute `Start-Class`.

Ví dụ sau minh họa một `MANIFEST.MF` điển hình cho executable jar:

[source,manifest]
----
Main-Class: org.springframework.boot.loader.launch.JarLauncher
Start-Class: com.mycompany.project.MyApplication
----

Với war file, nội dung sẽ như sau:

[source,manifest]
----
Main-Class: org.springframework.boot.loader.launch.WarLauncher
Start-Class: com.mycompany.project.MyApplication
----

NOTE: Bạn không cần chỉ định các entry `Class-Path` trong manifest file.
Classpath được suy ra từ các nested JAR.
