[[appendix.executable-jar.nested-jars]]
= Nested JARs

Java không cung cấp cách chuẩn nào để load các nested jar file (tức là các jar file nằm bên trong một jar khác).
Điều này có thể gây khó khăn khi bạn cần phân phối một application self-contained có thể chạy từ command line mà không cần giải nén.

Để giải quyết vấn đề này, nhiều developer sử dụng jar "`shaded`".
Một shaded jar package tất cả class từ tất cả jar vào một "`uber jar`" duy nhất.
Vấn đề với shaded jar là khó biết library nào thực sự có trong application.
Điều này cũng có thể gây rắc rối nếu cùng một filename được sử dụng (nhưng có nội dung khác nhau) trong nhiều jar.
Spring Boot sử dụng một cách tiếp cận khác và cho phép bạn nest jar trực tiếp.



[[appendix.executable-jar.nested-jars.jar-structure]]
== Cấu trúc Executable Jar File

Các jar file tương thích với Spring Boot Loader nên có cấu trúc như sau:

[source]
----
example.jar
 |
 +-META-INF
 |  +-MANIFEST.MF
 +-org
 |  +-springframework
 |     +-boot
 |        +-loader
 |           +-<spring boot loader classes>
 +-BOOT-INF
    +-classes
    |  +-mycompany
    |     +-project
    |        +-YourClasses.class
    +-lib
       +-dependency1.jar
       +-dependency2.jar
----

Các application class nên được đặt trong thư mục nested `BOOT-INF/classes`.
Các dependency nên được đặt trong thư mục nested `BOOT-INF/lib`.



[[appendix.executable-jar.nested-jars.war-structure]]
== Cấu trúc Executable War File

Các war file tương thích với Spring Boot Loader nên có cấu trúc như sau:

[source]
----
example.war
 |
 +-META-INF
 |  +-MANIFEST.MF
 +-org
 |  +-springframework
 |     +-boot
 |        +-loader
 |           +-<spring boot loader classes>
 +-WEB-INF
    +-classes
    |  +-com
    |     +-mycompany
    |        +-project
    |           +-YourClasses.class
    +-lib
    |  +-dependency1.jar
    |  +-dependency2.jar
    +-lib-provided
       +-servlet-api.jar
       +-dependency3.jar
----

Các dependency nên được đặt trong thư mục nested `WEB-INF/lib`.
Mọi dependency cần thiết khi chạy embedded nhưng không cần khi deploy lên một web container truyền thống nên được đặt trong `WEB-INF/lib-provided`.



[[appendix.executable-jar.nested-jars.index-files]]
== Index Files

Các jar và war archive tương thích với Spring Boot Loader có thể chứa thêm các index file trong thư mục `BOOT-INF/`.
Một file `classpath.idx` có thể được cung cấp cho cả jar và war, và file này cung cấp thứ tự các jar được thêm vào classpath.
File `layers.idx` chỉ có thể được dùng cho jar, và cho phép chia một jar thành các logical layer để tạo Docker/OCI image.

Các index file tuân theo cú pháp tương thích với YAML để các third-party tool có thể dễ dàng parse.
Tuy nhiên, các file này _không_ được parse nội bộ dưới dạng YAML và phải được viết chính xác theo các format được mô tả bên dưới thì mới có thể sử dụng.



[[appendix.executable-jar.nested-jars.classpath-index]]
== Classpath Index

File classpath index có thể được cung cấp tại `BOOT-INF/classpath.idx`.
Thông thường, file này được sinh tự động bởi Maven và Gradle build plugin của Spring Boot.
File này cung cấp danh sách tên jar (bao gồm cả thư mục) theo thứ tự các jar được thêm vào classpath.
Khi được sinh bởi build plugin, thứ tự classpath này khớp với thứ tự build system dùng để chạy và test application.
Mỗi dòng phải bắt đầu bằng dấu gạch ngang và dấu cách (`"-&#183;"`), đồng thời tên phải nằm trong dấu nháy kép.

Ví dụ, với jar sau:

[source]
----
example.jar
 |
 +-META-INF
 |  +-...
 +-BOOT-INF
    +-classes
    |  +...
    +-lib
       +-dependency1.jar
       +-dependency2.jar
----

Index file sẽ có dạng như sau:

[source]
----
- "BOOT-INF/lib/dependency2.jar"
- "BOOT-INF/lib/dependency1.jar"
----

NOTE: Spring Boot chỉ sử dụng file classpath index khi jar hoặc war file được execute bằng `java -jar`.
File này không được sử dụng khi chạy application từ IDE hoặc khi dùng `spring-boot:run` của Maven hay `bootRun` của Gradle.

NOTE: Khi bật reproducible build, các entry trong file classpath index được sắp xếp theo thứ tự alphabet.



[[appendix.executable-jar.nested-jars.layer-index]]
== Layer Index

File layer index có thể được cung cấp tại `BOOT-INF/layers.idx`.
File này cung cấp danh sách các layer và những phần của jar cần được chứa trong từng layer.
Các layer được ghi theo thứ tự chúng được thêm vào Docker/OCI image.
Tên layer được ghi dưới dạng quoted string có tiền tố là dấu gạch ngang và dấu cách (`"-&#183;"`), cùng hậu tố là dấu hai chấm (`":"`).
Layer content là tên file hoặc tên thư mục được ghi dưới dạng quoted string có tiền tố là dấu cách dấu cách gạch ngang dấu cách (`"&#183;&#183;-&#183;"`).
Tên thư mục kết thúc bằng `/`, còn tên file thì không.
Khi sử dụng tên thư mục, điều đó có nghĩa là tất cả file bên trong thư mục đó đều nằm trong cùng một layer.

Một ví dụ điển hình về layer index là:

[source]
----
- "dependencies":
  - "BOOT-INF/lib/dependency1.jar"
  - "BOOT-INF/lib/dependency2.jar"
- "application":
  - "BOOT-INF/classes/"
  - "META-INF/"
----
